### ISSUE TITLE
Quesition: How can dbowner account & reovery model  be validated ?

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#1007]
Details of the scenario :
How can I validate  the below two scenarios ?
Ensure DBOwner for all SQL Databases Is not set to your service Account
Ensure SQL Recovery model is set to to FULL->SSMS

The DSC configuration : n/a

Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:
Windows 2016, sqlserver dsc 10.0.0.0

**Comment by johlju** [comment]
Look at the resources SqlDatabaseRecoveryModel and SqlDatabaseOwner to see if the do what you are looking for.

**Comment by rsganta** [comment]
I looked at sqldatabaserecoverymodel and it talks about setting it. I just want to validate it was properly set or not. .Does ensure parameter help in this block ?

SqlDatabaseRecoveryModel Set_SqlDatabaseRecoveryModel_Adventureworks 
39         { 
40             Name                 = 'Adventureworks' 
41             RecoveryModel        = 'Full' 
42             ServerName           = 'sqltest.company.local' 
43             InstanceName         = 'DSC' 
44             PsDscRunAsCredential = $SqlAdministratorCredential 
45         }

**Comment by johlju** [comment]
If you look at the documentation there are no Ensure parameter to set; https://github.com/PowerShell/SqlServerDsc/blob/dev/README.md#sqldatabaserecoverymodel

**Comment by rsganta** [comment]
@johlju ,
As suggested, I have used SQLDatabaserecoverymodel and sqldatabaseowner but have seen error below.

VERBOSE: [DSC-SP12]:                            [[SqlDatabaseOwner]Set_SqlDatabaseOwner_SQLAdmin] Testing owner Officedog\SP997FRM of 
database SP2019_Content
VERBOSE: [DSC-SP12]:                            [[SqlDatabaseOwner]Set_SqlDatabaseOwner_SQLAdmin] Getting owner of database SP2019_Con
tent
VERBOSE: [DSC-SP12]:                            [[SqlDatabaseOwner]Set_SqlDatabaseOwner_SQLAdmin] Information: PowerShell module SqlSe
rver not found, trying to use older SQLPS module.
VERBOSE: [DSC-SP12]: LCM:  [ End    Test     ]  [[SqlDatabaseOwner]Set_SqlDatabaseOwner_SQLAdmin]  in 0.8900 seconds.
PowerShell DSC resource MSFT_SqlDatabaseOwner  failed to execute Test-TargetResource functionality with error message: 
System.InvalidOperationException: Neither PowerShell module SqlServer or SQLPS was found. Unable to run SQL Server cmdlets. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Recovery model:

VERBOSE: [DSC-SP12]:                            [[SqlDatabaseRecoveryModel]Set_SqlDatabaseRecoveryModel_ContentDB] Information: PowerS
hell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [DSC-SP12]: LCM:  [ End    Test     ]  [[SqlDatabaseRecoveryModel]Set_SqlDatabaseRecoveryModel_ContentDB]  in 0.8910 seconds.
PowerShell DSC resource MSFT_SqlDatabaseRecoveryModel  failed to execute Test-TargetResource functionality with error message: 
System.InvalidOperationException: Neither PowerShell module SqlServer or SQLPS was found. Unable to run SQL Server cmdlets. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Configurations : 
 SqlDatabaseOwner Set_SqlDatabaseOwner_SQLAdmin 
         { 
             Name                 = 'Officedog\SP997FRM' 
             Database             = 'SP2019_Content' 
             ServerName           = $AllNodes.where{ $_.Role.Contains("SQ") }.NodeName 
             InstanceName         = 'MSSQLSERVER' 
             PsDscRunAsCredential = $domjoincreds #$SqlAdministratorCredential
             DependsOn = @("[SPContentDatabase]SP2019_Content") 
         } 

 SqlDatabaseRecoveryModel Set_SqlDatabaseRecoveryModel_ContentDB 
         { 
             Name                 = 'SP2019_Content' 
             RecoveryModel        = 'Full' 
             ServerName           = $AllNodes.where{ $_.Role.Contains("SQ") }.NodeName 
             InstanceName         = 'MSSQLSERVER'  #$AllNodes.where{ $_.Role.Contains("SQ") }.NodeName 
             PsDscRunAsCredential = $domjoincreds #$SqlAdministratorCredential
             DependsOn = @("[SPContentDatabase]SP2019_Content") 
         }

**Comment by rsganta** [comment]
Additional info: I have both sqlserver versions on my target node 9.0.0.0 and 10.0.0.0

**Comment by johlju** [comment]
This is related to the error you submitted in issue #1015. Closing this issue since the original question was answered.
