### ISSUE TITLE
Quesition:How to enable mixed mode authentication using DSC?

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#1009]
I have encountered an issue on sql authentication. I have set the authmode to mixed on sql instance manually. However , it is resetting back to windows authentication. Any idea, how we can set mixed mode auth using DSC.

VERBOSE: [DSC-SP12]:                            [[SPAccessServiceApp]AccessServices] Leaving BeginProcessing Method of New-SPAccessSer
vicesApplication.
A connection could be established to the Application Database Server but mixed mode authentication isn't enabled.
    + CategoryInfo          : ObjectNotFound: (Access Services Application:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Office.Access.Services.PowerShell.NewSPAccessServicesApplication
    + PSComputerName        : localhost

Sqlserver dsc version: 1.9.0.0

**Comment by imarambiocatan** [comment]
I'm not sure I agree with that last part. It sould be posible to monitor the parameter and change it back if someone modifies the setting. Otherwise how can we assure the configuration is as we set it up over time?
DSC is the kind of tool i should be able to rely on to make sure my administrators are not messing up with my environment

**Comment by johlju** [comment]
@imarambiocatan I agree, there should be a resource that does this, like SqlServerSecurity or SqlServerAuthentication. The resource SqlSetup is "restricted" to only do what setup.exe can do, more information here https://github.com/PowerShell/SqlServerDsc/issues/37#issuecomment-330443544. 

Please submit a new issue for the ability to monitor and change the authentication mode.

**Comment by quillypowers** [comment]
I'd just do it with a registry configuration, sorry 6 years late.

Registry ChangeSqlLoginMode
{
	Ensure      = "Present"
	Key         = "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSSQLServer\MSSQLServer"
	ValueType   = "Dword"
	ValueName   = "LoginMode"
	ValueData   = "1"
}
