### ISSUE TITLE
SqlServerDsc: AppVeyor status badge does reflect tests that fail

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#1012]
**Details of the scenario you tried and the problem that is occurring:**
Latest merge into dev failed to pass the tests, but the status badge still shows the tests passing.

@kwirkykat can you see if the token changed in AppVeyor when we renamed the repository? Previous token was `mxn453y284eab8li`.

>You can see a badge image URL and sample markup on the Badges tab of project settings. Badge URLs for both private and public projects contain a security token.
>https://www.appveyor.com/docs/status-badges/

![image](https://user-images.githubusercontent.com/7189721/34785235-cfac39e4-f630-11e7-9389-610564f396a3.png)

*The reason for the tests to fail was because of the timing issue submitted in issue #1008.*

**Comment by kwirkykat** [comment]
@johlju Yes it did change. New token is `b3g8f7kftx64n26l`

**Comment by johlju** [comment]
@kwirkykat Thanks! I will update the README.md with the new token.

/cc @PlagueHO another thing to verify when you rename "your" resource modules.
