### ISSUE TITLE
Question: SQLPS module gives no match found error

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#1015]
The below scenario used to work in the past.  When I try to execute couple of SQLServerDSC cmdlets, it throws an error that it could not find either sql server or sqpls. .I have tried to install SQLPS module but fails. i

PS C:\Users\sankarg_adm> Find-Module -Name sqlps|Install-Module
PackageManagement\Find-Package : No match was found for the specified search criteria and module name 'sqlps'. Try Get-PSRepository 
to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1397 char:3
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage
 

SQLServer DSC

**Comment by johlju** [comment]
The module SQLPS does not exist in PowerShell Gallery. It’s installed as part of SQL Server. You can also download it from SQL Server Feature Pack (make sure it’s the correct SQL version) and install the needed components.

**Comment by rsganta** [comment]
Thank you @johlju
