### ISSUE TITLE
Help wanted - DSC resource for configuring SQL server maintenance plan ?

### ISSUE THREAD

**Issue by matt6697** [PowerShell/SqlServerDsc#1017]
Version : SqlServerDsc v10.0.0.0

Is there a way to automate the configuration of SQL server maintenance plans using a DSC resource ? The aim is to automate backup and transaction logs cleanup in an Always On AG scenario.

**Comment by johlju** [comment]
No, not currently, but would an awesome addition. Issue #832 was raised a while back proposing a resource for this. It you have a suggestion on how a that resource would look like, then please comment on issue #832, and feel free to contribute the resource.

Let's track this in issue #832. Closing this issue. Please, feel free to reopen if there are any unanswered questions.
