### ISSUE TITLE
Error On Adding Database to Availability Group

### ISSUE THREAD

**Issue by mohamednazar** [PowerShell/SqlServerDsc#1028]
**Error adding DB on SQL Availability Group:**

**xSQLServer:**

**Windows 2012 R2:**

**xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership:**

** 9.0.0.0:**

I am getting following error while adding DB to availability group. 

Code that I am trying:

dsc_resource 'database_membership' do
  resource :xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership
  property :AvailabilityGroupName, "#{node['sqlserver']['MyAG']}"
  property :BackupPath, '\\PrimaryNode\Backup'
  property :DatabaseName, ["#{node['sqlserver']['Dbname']}"]
  property :Ensure, 'Present'
  property :SQLInstanceName, 'MSSQLSERVER'
  property :SQLServer, "#{node['hostname']}"
  property :PsDscRunAsCredential, ps_credential("#{node['sqlserver']['Username']}", "#{node['sqlserver']['Password']}")
end

Error that I am getting:

[2018-01-21T04:16:39+00:00] FATAL: Chef::Exceptions::PowershellCmdletException: dsc_resource[database_membership] (SqlServer::dsc_avail_memb_primary line 7) had an error: Chef::Exceptions::PowershellCmdletException: Powershell Cmdlet failed: PowerShell DSC resource MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership  failed to executeSet-TargetResource functionality with error message: The operation on the database 'PVSCTXPRO' failed with the
following errors: Microsoft.SqlServer.Management.Smo.SmoException: System.Data.SqlClient.SqlError: Cannot open backupdevice 'E:\SQLDatabaseFiles\Backup\PrimaryNode\Backup\TestDB_Full_20180121041639.bak'. Operating system error3(The system cannot find the path specified.).   at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQueryWithMessage(StringCollection queries,ServerMessageEventHandler dbccMessageHandler, Boolean errorsAsMessages)
   at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSql(Server server, StringCollection queries)   at Microsoft.SqlServer.Management.Smo.Backup.SqlBackup(Server srv).
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

The backup path \\AZV-DBS4E-BDBTP\Backup is accessible from all nodes like PrimaryNode and SecondaryNode. 

I dont know why its finding backup file under 'E:\SQLDatabaseFiles\Backup\PrimaryNode\Backup\TestDB_Full_20180121041639.bak'. this location instead of  \\AZV-DBS4E-BDBTP\Backup this location. Please see the error.

Please help

Regards,
Mohamed Nazar

**Comment by johlju** [comment]
You have the following in the configuration.
```
property :BackupPath, '\PrimaryNode\Backup'
```

and the path 'E:\SQLDatabaseFiles\Backup' is maybe taken from the default backup location path in the instance server properties?

The full path should be 'E:\SQLDatabaseFiles\Backup\AZV-DBS4E-BDBTP\Backup'?

**Comment by mohamednazar** [comment]
@johlju 

Waiting for your assistance on my above issue.

**Comment by randomnote1** [comment]
@mohamednazar, I think the issue could be that there is not a double backslash before the primary node in the path since this appears to be a network path from your description.

Does this work?

`property :BackupPath, '\\PrimaryNode\Backup'`

**Comment by mohamednazar** [comment]
No not working with following property value as well. Same error.

> property :BackupPath, '\\PrimaryNode\Backup'

**Comment by randomnote1** [comment]
One thing that is commonly missed is ensuring the SQL Server Services have permission to the backup path. This can be accomplished by granting full control to the SQL Server service account or service SID to that directory.

**Comment by mohamednazar** [comment]
yeah, that folder has shared with everyone full access.

**Comment by randomnote1** [comment]
How about the NTFS permissions? If you run a manual backup from SQL to that directory (full w/ copyonly) does that work?

**Comment by johlju** [comment]
Is the path a shared resource that is accessed using `\\PrimaryNode\Backup`? The shared resource have everyone as full control for both resource permission and file permission?
Can you log in with the account and access the resource folder?
Do you see any errors in the event logs (Security log) or server logs?

Next step is manually trying to run the command that is failing to see if that works.

**Comment by mohamednazar** [comment]
\\Primary\Backup share is accessible from both servers. I have tried backup and restored using that path those are working successfully. 

When I try via script, it tooks the path 'E:\SQLDatabaseFiles\Backup\Primary\Backup' like this.

Please help

**Comment by johlju** [comment]
The code that uses the `BackupPath` is this what I can gather. Is it possible for you to run this code manually to see if there is any point where the path changes? Or if the cmdlet `Backup-SqlDatabase` does something.

https://github.com/PowerShell/SqlServerDsc/blob/a04c542da2ccc3970085e6c1fb04358b4a00db8a/DSCResources/MSFT_SqlAGDatabase/MSFT_SqlAGDatabase.psm1#L400-L430
