### ISSUE TITLE
SQLServerPermission dont work on multiple permissions

### ISSUE THREAD

**Issue by werton13** [PowerShell/SqlServerDsc#1029]
Hi there!
I'm using DSC module SqlServerDsc v. 10.0.0.0 on Windows Server 2012R2
Powershell version 4.0

I'm trying to setup SQL permissions for 'NT AUTHORITY\SYSTEM' and 'NT SERVICE\ClusSvc' like in example. Near the part of my configuration regarding SQLServerPermission:

SQLServerPermission 'SQLPermissionAAAG-SYSTEM'
                                {
                                    Ensure = 'Present'
                                    ServerName = $Node.NodeName
                                    InstanceName  = $Node.SQLInstanceName
                                    Principal = 'NT AUTHORITY\SYSTEM'
                                    Permission           = 'AlterAnyAvailabilityGroup', 'ViewServerState'
                                    #PsDscRunAsCredential = $SysAdminAccount
                                }

so I'm trying to grant two permissions, but I get this error:

SqlServerDsc\SQLServerPermission : **'AlterAnyAvailabilityGroup ViewServerState'** is not a valid value for property 'Permission' on class 'SqlServerPermission'. Please change the value to one of the following strings: ConnectSql, AlterAnyAvailabilityGroup, ViewServerState, AlterAnyEndPoint.

 I faced with this issue in xSQLServer v.9.0.0.0, and decided to look for changes in SqlServerDsc  but no luck.. please advice

**Comment by randomnote1** [comment]
Hi @werton13!

I wonder if Permission needs to be explicitly defined as an array since you're in PowerShell v4. It's possible this would work:

```PowerShell
SQLServerPermission 'SQLPermissionAAAG-SYSTEM'
{
    Ensure = 'Present'
    ServerName = $Node.NodeName
    InstanceName = $Node.SQLInstanceName
    Principal = 'NT AUTHORITY\SYSTEM'
    Permission = @('AlterAnyAvailabilityGroup', 'ViewServerState')
    #PsDscRunAsCredential = $SysAdminAccount
}
```

The other thing I should mention is SqlServerDsc is "officially" supported on PowerShell v5+. PowerShell v4 support was dropped a while back around the time the Availability Group resources were updated.

**Comment by werton13** [comment]
Hi Dan! Thank a lot for your answer. Unfortunately your first suggestion did not help, but then I installed powershell 5 - and this fixed the problem.

**Comment by randomnote1** [comment]
Awesome! Good to confirm the PowerShell v5 requirement. Thanks!

**Comment by johlju** [comment]
Maybe we should add a note about this WMF v5.x requirement, I think we only have it in the change log and in the module manifest now - any suggestions where such note would be best to add to make it more visible?

**Comment by randomnote1** [comment]
It is documented in the [README ](https://github.com/PowerShell/SqlServerDsc#requirements) already. I'm not sure there would be any additional value in adding it anywhere else.

I thought that by specifying the PowerShell version in the module manifest it would throw an error if the version was too low. I wonder why this didn't occur in this example.

**Comment by johlju** [comment]
@randomnote1 forgot about the README.md thanks for pointing it out! I also thought about the manifest when I read the issue description, also thought it would throw. But guess out-of-scope for this resource module 😄 

Closing this issue since the initial question was resolved.
