### ISSUE TITLE
SqlSetup: SQLSvcAccount failing on domain account

### ISSUE THREAD

**Issue by joshan1120** [PowerShell/SqlServerDsc#1042]
Are there any known issues around installing with a domain account? I did it this same exact way with this same account on xSqlServer and now it fails with this new package.

The account is valid and I can RDP to the server with that account and creds.

Error:
01) 2018-02-02 11:26:30 Slp: Validation for setting 'SQLSVCACCOUNT' failed. Error message: The SQL Server service account login or password is not valid. Use SQL Server Configuration Manager to update the service account.

Log File:
  SQLSVCACCOUNT:                 Dev2x.Azure.xxx.net\svc-sqlserverxx
  SQLSVCPASSWORD:                *****

**Comment by joshan1120** [comment]
I tried changing to this format. No difference.

  SQLSVCACCOUNT:                 Dev2x\svc-sqlserverxx
  SQLSVCPASSWORD:                *****

**Comment by johlju** [comment]
No that should work. I just did an install a couple of hours ago using a domain account, and the integration tests installs using a local account (to mimic installing as a domain account).

**Comment by joshan1120** [comment]
ya this one is throwing me. I can run in xSqlServer and it works perfect. When I use the newest SqlServerDsc it fails.

**Comment by johlju** [comment]
That sound strange.

Can ypu post your configuration? 
What version of SQL Server are you installing?
Are you using SQLPS or SqlServer?

**Comment by joshan1120** [comment]
SQL Server 2014 right now.

I had to put xxx for some entries, but nothing important for the install. If I did not give enough let me know!

SqlSetup SqlServerSetup {
			BrowserSvcStartupType = 'Automatic'
			Features = $environmentNode.sqlInstallFeatures
			InstallSharedDir = $roleNode.installSharedDir
			InstallSharedWOWDir = $roleNode.installSharedWowDir
			InstallSQLDataDir = $roleNode.installSqlDataDir
			InstanceName = $environmentNode.sqlInstanceName
			InstanceDir = $roleNode.sqlInstanceDir
			SAPWd = $sqlSaAccountCreds
			SecurityMode =  $roleNode.securityMode
			PsDscRunAsCredential = $adminCreds
			SourcePath = $roleNode.sourcePath
			# SourceFolder = $roleNode.sqlSourceFolder
			SQLBackupDir = $roleNode.sqlBackupDir
			SQLCollation = $roleNode.sqlCollation
			SQLSvcAccount = $SQLServiceCreds
			SQLSysAdminAccounts = $environmentNode.sqlSysAdminAccounts
			SQLTempDBDir = $roleNode.sqlTempDbDir
			SQLTempDBLogDir = $roleNode.sqlTempDbLogDir
			SQLUserDBDir = $roleNode.sqlUserDbDir
			SQLUserDBLogDir = $roleNode.sqlUserDbLogDir
			UpdateSource = $roleNode.updateSource
			UpdateEnabled = $roleNode.updateEnabled
			SuppressReboot = $False
			ForceReboot = $False
			#TODO: Need to come up with non hard coded solution
			DependsOn = '[WaitForVolume]WaitForISO','[Disk]CreateDrivesSQLTemp','[Disk]CreateDrivesSQLLog','[Disk]CreateDrivesSQLSystem','[Disk]CreateDrivesSQLData'
		}


PSD1:

@{
			environment = 'infra'
			diskDrives = @(
				@{
					diskFriendlyName = 'SQLData'
					driveLetter = 'F'
					driveSize = 2100GB
				},
				@{
					diskFriendlyName = 'SQLLog'
					driveLetter = 'L'
					driveSize = 1500GB
				},
				@{
					diskFriendlyName = 'SQLSystem'
					driveLetter = 'E'
					driveSize = 25GB
				},
				@{
					diskFriendlyName = 'SQLTemp'
					driveLetter = 'T'
					driveSize = 1500GB
				}
			)
			domainName = 'Dev2x.Azure.xxx.net'	
			octopusEnvironment = 'Infrastructure'
			ouPath = 'OU=SQL,OU=USA,OU=Servers,OU=NA,OU=Regions,DC=dev2x,DC=azure,DC=xxx,DC=net'
			remoteUsers = @('NAAG-xxx-Deploy', 'NAAG-xxx-dba')
			sqlCred1 = 'dbmaintlrs'
			sqlIdentity1 = 'xxxdbmaintlrs'
			sqlCred2 = 'dbmaintragrs'
			sqlIdentity2 = 'xxxdbmaintstdrgrs'
			sqlCred3 = 'dbmaintzrs'
			sqlIdentity3 = 'xxxbackupsstdzrs'
			sqlInstallFeatures = 'SQLENGINE,SSMS,ADV_SSMS,IS,FULLTEXT,BC,CONN'
			sqlInstanceName = 'INFRA01'
			sqlIso = 'en_sql_server_2014_developer_edition_with_service_pack_1_x64_dvd_6668542.iso'
			sqlSysAdminAccounts = @('NAAG-xxx-Admin','NAAG-xxx-Deploy','NAAG-xxx-DBA','NT AUTHORITY\SYSTEM','NT SERVICE\Winmgmt','Svc-SQLServerFA1','svc-WinServerFA1')
			sqlServerDomainAccounts = @('Dev2i\NAAG-xxx-Deploy', 'Dev2i\svc-xxxIIS')
			tcpPort = 'xxx'
			VaultName = "xxx-weu-infra"
			virtualDiskLayoutType = 'Simple'
		},

**Comment by joshan1120** [comment]
Role = @(
		@{
			Role = 'SqlServer'
			installSharedDir = 'C:\Program Files\Microsoft SQL Server'
			installSharedWOWDir = 'C:\Program Files (x86)\Microsoft SQL Server'
			installSqlDataDir = 'E:\TRPMSINFRA01'
			octopusListenPort = '10933'
			octopusRole = 'New-DB'
			octopusServerUrl = 'https://deploy.xxx.com'
			RequiredDirectories = @('T:\BatchFiles','T:\MSSQLJobLogs','T:\SSISPackages')
			saUserName = 'sa'
			securityMode = 'SQL'
			sqlSourceFolder = ""
			sourcePath = "G:\"
			sqlAuthUsers = @(
				@{
					userName = 'xxx'
					keyVaultKey = 'SQL-xxx'
					roleName = 'sysadmin'
				},
				@{
					userName = 'Hangfire'
					keyVaultKey = 'SQL-Hangfire'
					roleName = 'sysadmin'
				},
				@{
					userName = 'OctopusDeploy'
					keyVaultKey = 'SQL-OctopusDeploy'
					roleName = 'sysadmin'
				},
				@{
					userName = 'TDE-Local-Principal'
					keyVaultKey = 'SQL-TDE-Local-Principal'
					roleName = 'sysadmin'
				},
				@{
					userName = 'TDE-Prod-Principal'
					keyVaultKey = 'SQL-TDE-Prod-Principal'
					roleName = 'sysadmin'
				}
			)
			sqlBackupDir = 'T:\Backups'
			sqlCollation = 'SQL_Latin1_General_CP1_CI_AS'
			sqlInstanceDir ='E:\Microsoft SQL Server'
			sqlIsoDriveAssignment = 'G'
			sqlServiceUserName = 'svc-sqlserverxx'
			sqlTempDbDir = 'd:\TRPMSINFRA01'
			sqlTempDbLogDir = 'd:\TRPMSINFRA01'
			sqlUserDbDir = 'F:\TRPMSINFRA01'
			sqlUserDbLogDir = 'L:\TRPMSINFRA01'
			storageSpaceName = 'MS-SQL-Drives'
			SoftwareList = (
				@{
					Type = 'SelfInstall'
					Key = 'vcredist_x64'
					Name = "Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501"
					Archive = 'vcredist_x64.zip'
				},
					@{
					Type = 'SelfInstall'
					Key = 'DLMAutomation'
					Name = "RedGate DLM Automation Suite"
					Archive = 'DLMAutomation.zip'
				},
				@{
					Type = 'SelfInstall'
					Key = 'curl'
					Name = "curl"
					Archive = 'curl.zip'
				},
				@{
					Type = 'MsiPackage'
					Key = 'AzureKeyVaultConnector'
					Name = "SQL Server Connector for Microsoft Azure Key Vault"
					Archive = 'SQLServerConnectorforMicrosoftAzureKeyVault.msi'
					File = 'SQLServerConnectorforMicrosoftAzureKeyVault.msi'
					Args = '/passive'
					ProductId = "2F17A369-AE10-4D0A-B897-D432C257A0CA"
				}
			)
			updateEnabled = 'False'
			updateSource = 'MU'
			virtualDiskProvisioningType = 'Thin'
		}
	);

**Comment by joshan1120** [comment]
Still trying to figure this one out....

I generate my SVC creds with this:
$sqlServicePw = (Get-AzureKeyVaultSecret -VaultName $vaultName -Name $nonNodeData.sqlServiceSecretName).SecretValue
	$sqlServiceCreds = New-Object System.Management.Automation.PSCredential("$($environmentNode.DomainName)\$($roleNode.sqlServiceUserName)", $sqlServicePw)

Which I than pass into:
SqlSetup SqlServerSetup {
  SQLSvcAccount = $SQLServiceCreds
}

Which gives this Error:

2018-02-02 11:26:30 Slp: Validation for setting 'SQLSVCACCOUNT' failed. Error message: The SQL Server service account login or password is not valid. Use SQL Server Configuration Manager to update the service account.
Log File:
SQLSVCACCOUNT: Dev2x.Azure.xxx.net\svc-sqlserverxx
SQLSVCPASSWORD: *****

Everything seems correct when I run the commands in powershell and verify the results. This is the same process I used in xSqlServer which zero changes, which worked. I am kind of at a loss right now.

**Comment by joshan1120** [comment]
it seems my PsDscRunAsCredential was causing this. Not sure why it worked before, but I changed this to a network account and it is working. Having the RunAs as a local account and the installer as a network account was not working :)
