### ISSUE TITLE
SqlServerNetwork: Cannot index into null array

### ISSUE THREAD

**Issue by tbollhofer** [PowerShell/SqlServerDsc#1051]
**Details of the scenario you tried and the problem that is occurring:**
Using version 11.0.0.0. Receiving a  "Cannot index into a null array." 

```
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] Importing the module MSFT_SqlServerNetwork in force mode.
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] SQL major version is 13.
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] SQL major version is 13.
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] Creating application domain 'SqlServerDscHelper'.
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] Loading assembly 'Microsoft.SqlServer.Smo, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'.
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] Loading assembly 'Microsoft.SqlServer.SqlWmiManagement, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91'.
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] Getting network protocol [Tcp] for SQL instance [MSSQLSERVER].
[[SqlServerNetwork]ChangeTcpIpOnDefaultInstance] Unloading application domain 'SqlServerDscHelper'.
Cannot index into a null array.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NullArray
    + PSComputerName        : SOMETESTMACHINE
Cannot index into a null array.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NullArray
    + PSComputerName        : SOMETESTMACHINE
```

**The DSC configuration that is using the resource (as detailed as possible):**
```
SQLServerNetwork 'ChangeTcpIpOnDefaultInstance'
                {
                    InstanceName = 'MSSQLSERVER'
                    ProtocolName = 'Tcp'
                    IsEnabled = $true
		    TCPDynamicPort = $false
                    TCPPort = '12345 
                    RestartService = $true
                }
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
11.0.0.0

**Comment by johlju** [comment]
@tbollhofer Thanks for sending in this issue! Could you please provide the first columns of the verbose log that says what resource and what function it's currently in? It will help narrowing down what causing this. 
It's a strange error. Thought that it was the helper function `Unregister-SqlAssemblies`, but that helper function will not allow null values, so it can't be it. Something else is throwing this error.

**Comment by johlju** [comment]
Only row I can see, so far, that is causing this would be line 343. But as mentioned above already, the full verbose (all columns) will help narrow it down, so that it is actually Test-TargetResource function that is cause this error.

https://github.com/PowerShell/SqlServerDsc/blob/a8cb7528153eb7d7246a41b97c7a28b831686ac5/DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1#L336-L346

**Comment by tbollhofer** [comment]
[SqlServerNetwork.log](https://github.com/PowerShell/SqlServerDsc/files/1744324/SqlServerNetwork.log)

Thank you Gentleman, attached the full output.

**Comment by tbollhofer** [comment]
> Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running

: Windows Server 2016 Standard Edition, SQL Server 2016 Standard Edition, PowerShell 5.x

> What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running

: SqlServer, version 21.0.17224
