### ISSUE TITLE
SqlDatabase Enhancement

### ISSUE THREAD

**Issue by HealisticEngineer** [PowerShell/SqlServerDsc#1098]
'SqlDatabase: Enhancement Request'

For those of us using data warehouse and VLDB's, it would be nice if we could specify the number of data files and the file group as this would help with performance and this is a large reason we end up with custom modules.

**Comment by johlju** [comment]
There are two new resource proposed in issue #57 (SqlDatabaseFile) and issue #657 (SqlDatabaseFileGroup) that nobody started working on yet. Could you look at them and see if you can suggest any improvements (or SqlDatabase or maybe another new resources) that make what you suggest work as you would like. Do they cover what you looking for?

**Comment by HealisticEngineer** [comment]
@johlju  The look they would cover what I'm looking for.
since they don't exist I'll have to create my own anyway mind if I take a run that them ?

**Comment by johlju** [comment]
That is great! You are more than welcome to run with them! Just comment on the issue that you are working on it an I will label them as “in progress”.  I will review once you send in a PR(s). Let me know if I can help in anyway during the process.
Thank you! :smile:

**Comment by johlju** [comment]
Closing this issue as there are other issues tracking this.
