### ISSUE TITLE
SQLServerDSC 11.1.0.0 fails to run

### ISSUE THREAD

**Issue by noendscripting** [PowerShell/SqlServerDsc#1113]
ISSUE TITLE:
    SQLSetup: module not found error
    ISSUE DESCRIPTION (this template):
   When attempting to execute DSC configuration with SQLServerDSC 11.1.0.0 module and not other SQLServerDSC modules installed. Execution fails with following error:
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQL2014SCCM with user sid S-1-5-21-4168930975-2842902173-3084205817-500.
VERBOSE: [SQL2014SCCM]: LCM:  [ Start  Set      ]
VERBOSE: [SQL2014SCCM]: LCM:  [ End    Set      ]
The PowerShell DSC resource MSFT_SqlSetup from module <SqlServerDsc,11.0.0.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC resource.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : DscResourceNotFound
    + PSComputerName        : sql2014sccm.eastus2.cloudapp.azure.com

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 5.185 seconds#### Details of the scenario you tried and the problem that is occurring
Simply running start-dscconfiguration 
#### The DSC configuration that is using the resource (as detailed as possible)
```
Configuration ConfigurationSQL
{
    [CmdletBinding()]

	Param
	(
		[string]$NodeName = 'localhost',
		#[PSCredential]$DriveCredentials,
        #[PSCredential]$DomainCredentials,
		[string]$DataDriveLetter = "F",
        [string]$SQLSourceFolder  = "C:\SQLCD"

	)


$PlainPassword = "1hfxLwbLsT4PbE4JztmeLOm+4I6eEmPMUnlgB0x4tHTN6qMQ4Hdb56oNLZuKIhOnm+uf8lbDMBXl7QdxtSPj/Q=="
$SecurePassword = $PlainPassword | ConvertTo-SecureString -AsPlainText -Force
$UserName = "101filepoc"
$DriveCredentials = New-Object System.Management.Automation.PSCredential -ArgumentList $UserName, $SecurePassword


$SQLServerDomainPassword = ConvertTo-SecureString -AsPlainText -Force "P2ssw0rd"
$SQLServerAccountuser = "Contosoad\cmSQLsvc"
$SQLServerAccountCredentials = New-Object System.Management.Automation.PSCredential -ArgumentList $SQLServerAccountuser , $SQLServerDomainPassword

$SQLAgentAccountuser = "Contosoad\cmSQLAgent"
$SQLAgentAccountCredentials = New-Object System.Management.Automation.PSCredential -ArgumentList $SQLAgentAccountuser , $SQLServerDomainPassword

$SQLRSAccountuser = "Contosoad\cmRSPacct"
$SQLRSAccountCredentials = New-Object System.Management.Automation.PSCredential -ArgumentList $SQLRSAccountuser , $SQLServerDomainPassword



Import-DscResource -ModuleName SQLServerDSC
Import-DscResource -ModuleName StorageDSC
Import-DscResource -Module PSDscResources -ModuleVersion 2.8.0.0
Import-DscResource -ModuleName xTimeZone -ModuleVersion 1.7.0.0
Node $NodeName {
    LocalConfigurationManager
		{
			ConfigurationMode = 'ApplyAndAutoCorrect'
			RebootNodeIfNeeded = $true
			ActionAfterReboot = 'ContinueConfiguration'
            AllowModuleOverwrite = $true
            DebugMode = "All"
        }

        xTimeZone TimeZoneEastern

        {
			isSingleInstance = 'Yes'
            TimeZone = 'Eastern Standard Time'

        }
        WindowsFeatureSet Framework
        {
            Name                    = @("AS-NET-Framework", "NET-Framework-Features")
            Ensure                  = 'Present'
            IncludeAllSubFeature    = $true
        }





        WaitForDisk Wait_Data_Disk
		{
			DiskId = "2"
			RetryCount = 3
			RetryIntervalSec = 30

		}

		Disk Data_Disk
		{
			DiskId = "2"
			DriveLetter = $DataDriveLetter
			AllocationUnitSize = 4096
			DependsOn = '[WaitforDisk]Wait_Data_Disk'
		}



        SqlSetup InstallNamedInstance_INST2014
        {

            Action                = 'Install'
            InstanceName          = 'MSSQLSERVER'
            Features              = 'SQLENGINE,FULLTEXT,RS,SSMS,ADV_SSMS'
            SQLCollation          = 'SQL_Latin1_General_CP1_CI_AS'
            SQLSvcAccount         = $SQLServerAccountCredentials
            AgtSvcAccount         = $SQLAgentAccountCredentials
            RSSvcAccount          = $SQLRSAccountCredentials
            SQLSysAdminAccounts   = ".\Administrators"
            InstallSharedDir      = "C:\Program Files\Microsoft SQL Server"
            InstallSharedWOWDir   = 'C:\Program Files (x86)\Microsoft SQL Server'
            InstanceDir           = 'C:\Program Files\Microsoft SQL Server'
            InstallSQLDataDir     = "$($DataDriveLetter):\Data"
            SQLUserDBDir          = "$($DataDriveLetter):\Data"
            SQLUserDBLogDir       = "$($DataDriveLetter):\Data"
            SQLTempDBDir          = "$($DataDriveLetter):\Data"
            SQLTempDBLogDir       = "$($DataDriveLetter):\Data"
            SQLBackupDir          = "$($DataDriveLetter):\Backup"
            SourcePath            = $SQLSourceFolder
            UpdateEnabled         = 'True'
            UpdateSource          = 'MU'
            ForceReboot           = $false
            BrowserSvcStartupType = 'Automatic'
            #PsDscRunAsCredential  = $SqlInstallCredential
            DependsOn             = '[WindowsFeatureSet]Framework','[WaitforDisk]Wait_Data_Disk'

        }

        SqlRS DefaultConfiguration

        {

            InstanceName         = 'MSSQLSERVER'
            DatabaseServerName   = 'sql2014sccm'
            DatabaseInstanceName = 'MSSQLSERVER'
            DependsOn = '[SqlSetup]InstallNamedInstance_INST2014'

        }




        Group AddADUserToLocalAdminGroup {
            GroupName='Administrators'
            Ensure= 'Present'
            MembersToInclude= "Contosoad\ConfigMgrAdmins"
            Credential = $SQLServerAccountCredentials
            #PsDscRunAsCredential = $DCredential
            DependsOn = '[SqlSetup]InstallNamedInstance_INST2014'
        }


        SqlDatabaseRecoveryModel Set_SqlDatabaseRecoveryModel_ReportsServer
        {
            Name                 = 'ReportServer'
            RecoveryModel        = 'Simple'
            ServerName           = 'localhost'
            InstanceName         = 'MSSQLSERVER'
            #PsDscRunAsCredential = $SqlAdministratorCredential
            DependsOn = '[SqlSetup]InstallNamedInstance_INST2014'
        }

        SqlDatabaseRecoveryModel Set_SqlDatabaseRecoveryModel_ReportServerTempDB
        {
            Name                 = 'ReportServerTempDB'
            RecoveryModel        = 'Full'
            ServerName           = 'localhost'
            InstanceName         = 'MSSQLSERVER'
            #PsDscRunAsCredential = $SqlAdministratorCredential
            DependsOn = '[SqlSetup]InstallNamedInstance_INST2014'
        }








    }
}
```
#### Version of the operating system and PowerShell the target node is running
Caption                                     OSArchitecture Version  MUILanguages $PSVersionTable.PSVersion
-------                                     -------------- -------  ------------ -------------------------
Microsoft Windows Server 2012 R2 Datacenter 64-bit         6.3.9600 {en-US}      5.1.14409.1005           

#### SQL Server edition and version the target node is running
None

#### What SQL Server PowerShell modules, and which version, are present on the target node.
None
#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
11.1.0.0

**Comment by johlju** [comment]
The error says `<SqlServerDsc,11.0.0.0>`, not version 11.1. Could it be that it isn't finding v11.1?

**Comment by noendscripting** [comment]
Hi Johan
It may be possible  but my reasons for thinking there is something else:

  1.  I would expect the error at the point when I import module and have the whole module fail
  2.  It fails when a specific submodule, far down the list of modules attempts to load

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by johlju** [comment]
Have you run this configuration before using SqlServerDsc v11.0.0.0, and now trying to use the same configuration with v11.1.0.0?

To me it looks like it is trying to call SqlSetup resource from SqlServerDsc v11.0.0.0, but it cannot find SqlServerDsc v11.0.0.0. 
```
The PowerShell DSC resource MSFT_SqlSetup from module <SqlServerDsc,11.0.0.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC resource.
```

Will it work if you have SqlServerDsc v11.0.0.0 on the target node? 
Maybe you need to recompile the configuration? 🤔

**Comment by noendscripting** [comment]
Hi Johan
I followed your advise and tested on clean VM. After going over my mof I realized that my dev workstation, where I run compile my DSC config, was never updated to version 11.1.0.0 and MOF file had references  to 11.0.0.0 while on server where I applied configuration I would install 11.1.0.0.

You can close the ticket, though I think we should have some sort of backward compatibility, this is a very likely scenario in enterprise.
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by johlju** [comment]
I'm glad you found the problem! 

You can have several version of the same module on the target node, and you can point you configuration to use an older version. But I think a configuration should not use a newer version than it was compiled for, if you would get a newer module on your production system with breaking changes, and you haven't tested it in UAT environment, that could have serious consequences. But I could see this option in a lab environment where you would want the latest every time. I suggest you [add your proposal as a uservoice](https://windowsserver.uservoice.com/forums/301869-powershell/?query=LCM), if it doesn't already exist,  so PoweShell DSC Team can consider it if it get enough votes. 🙂
