### ISSUE TITLE
SQLServerDSC.psd1 file name is not consistent

### ISSUE THREAD

**Issue by glennsarti** [PowerShell/SqlServerDsc#1116]
The file `SQLServerDsc.psd1` name is not consistent with the rest of this module.  Through the documentation etc. the module is referred to as `SqlServerDsc`.  This may also cause issues for people on case-sensitive file systems e.g. Mac.

Perhaps this file should be renamed to `SqlServerDsc.psd1`

**Comment by johlju** [comment]
I agree, let's rename it! I totally missed that. Thanks for catching it. Labeling this as easy fix and help wanted so someone can pick it up and run with it!

**Comment by glennsarti** [comment]
PR Raised.
