### ISSUE TITLE
SqlSetup: Missing Configuration Options

### ISSUE THREAD

**Issue by SQLCanuck** [PowerShell/SqlServerDsc#1122]
#### Details of the scenario you tried and the problem that is occurring
SqlSetup is missing the following configuration options for SQL 2016+
SQLSVCINSTANTFILEINIT
SQLTEMPDBFILECOUNT
SQLTEMPDBFILESIZE
SQLTEMPDBFILEGROWTH
SQLTEMPDBLOGFILESIZE
SQLTEMPDBLOGFILEGROWTH

SQLTempDBDir would also need to accept the multiple paths for each possible data file.

SqlSetup is also missing these configuration options for all versions
AGTSVCSTARTUPTYPE
ISSVCSTARTUPTYPE
SQLSVCSTARTUPTYPE

#### The DSC configuration that is using the resource (as detailed as possible)
Options not available to show in DSC

#### Version of the operating system and PowerShell the target node is running
Windows Server 2016 Datacenter
PowerShell v5.1

#### SQL Server edition and version the target node is running

Edition  : Enterprise Edition
Version  : 13.1.4474.0
Language : 1033

#### What SQL Server PowerShell modules, and which version, are present on the target node.

SqlServer 21.0.17240

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch

SqlServerDsc 11.1.0.0

**Comment by johlju** [comment]
@SQLCanuck Thanks for reporting this. I think some of these are duplicate to issue #459, but this issue also request additional configuration options not mentioned in #459.

Labeling this as help wanted to someone in the community can run with this one.

**Comment by SQLCanuck** [comment]
@johlju Thanks.  Essentially, looking to have all options available in a SQL configuration file available in SqlSetup as well.

**Comment by johlju** [comment]
Getting more options in SqlSetup would be great, it would close issues. Someone in the community has to have time to run with it though. 🙂

**Comment by banditkd** [comment]
I would love to help as I would like to see a couple more options in the setup, ideally everything in the configuration.ini, but small steps. I'll have a look at the guides and see if I can work out how to contribute

**Comment by johlju** [comment]
@banditkd would be awesome if you could contribute. If you have question or if you need any pointers just tag me here or ping me on Twitter. Happy to help!

**Comment by mdaniou** [comment]
I could have a look at this. I need some time though.
Any more options that need to be added ?

**Comment by johlju** [comment]
@mdaniou Take all the time you need. 🙂 You can look on the [open issues for SqlSetup](https://github.com/PowerShell/SqlServerDsc/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+SqlSetup%3A) to see if there are any more requested options. *In the end it would be good to support as many as we can.*

**Comment by banditkd** [comment]
@johlju Sorry for the delay - work got in the way. Finally got round to cloning the repo so now trying to get my head around it and see if i can do anything. I'm no developer but a DBA with an interest in PS and DSC so it might take me a while :)

**Comment by johlju** [comment]
@banditkd Awesome. 

@banditkd and  @mdaniou make sure you don't work on adding the same property 🙂

**Comment by banditkd** [comment]
@johlju no problem. I'll just have a look at the code offline and do a proper fork once i'm up to speed. i'll ping @mdaniou before starting anything in earnest

**Comment by mdaniou** [comment]
Hi,

I actually starting to work on it.

I would need some help on the options that should be added to the resource.
Could you please have a look at my Excel file here and share your thoughts ?
https://1drv.ms/x/s!AvtxRsEuoRL4ifE-TWb5UGaQ0Zdx1g

Then I think that there should be a project created to handle this so that anyone can pick the options he/she is working on.

I am working on those ones :
/AGTSVCSTARTUPTYPE
/SQLSVCSTARTUPTYPE
/ISSVCStartupType

There are other similar options that I would like to handle at the same time (AS, PB, RS)

Thanks

**Comment by mdaniou** [comment]
Ok, let's confirm all the options and I'll create the issues for each of them, no problem for me :)

**Comment by johlju** [comment]
@mdaniou I think the [Install SQL Server from the Command Prompt](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017) is a good source for the available parameters, although it doesn't say which one goes to which version. Tried changing the `view` query property on the url to '2016' but it seemed that didn't help :)

**Comment by mdaniou** [comment]
@johlju This is why I have creating the Excel file I referred in my previous message. It contains all the infomation. I only need it to be reviewed eventually.

https://1drv.ms/x/s!AvtxRsEuoRL4ifE-TWb5UGaQ0Zdx1g

**Comment by johlju** [comment]
@mdaniou The list you got so far seems promising, looked at all the work items that is labeled 'todo', and I have no comments around them what I can think of right now.  It looks like you made an awesome job with  that list! 😃

**Comment by mdaniou** [comment]
@johlju Cool thanks !
I'll create the issues from this then.

**Comment by mdaniou** [comment]
I excluded INSTANCEID and Express on purpose. Actualy I don't really get the point of the INSTANCEID.
However, as it is available, it should be added to at least give the choice.

For Express, I guess that I can create an issue for it as well so that there is at least a discussion about it.

**Comment by johlju** [comment]
@mdaniou Done! Not sure if you can move cards yourself on the board, but if you tag me in an issue and let me know your working on an item I will move it (wish there was some more automation in the projects boards, like label support).

**Comment by johlju** [comment]
Should we close this issue at this time, since this is being tracked in the other issues?

**Comment by johlju** [comment]
@mdaniou Yes I know, the GitHub permission model currently is not that granular so giving permission to contributors is not possible. 🙁 

I close this issue as this is being tracked in 13 other issues.
