### ISSUE TITLE
PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with 

### ISSUE THREAD

**Issue by wondisha** [PowerShell/SqlServerDsc#1127]
#### The DSC configuration that is using the resource (as detailed as possible)
```
<add configuration here>
```

**Comment by wondisha** [comment]
Configuration SQLInstall
{
     Import-DscResource -ModuleName SqlServerDsc
     node localhost
     {
          WindowsFeature 'NetFramework45'
          {
               Name   = 'NET-Framework-45-Core'
               Ensure = 'Present'
          }

          SqlSetup 'InstallDefaultInstance'
          {
               InstanceName        = 'Test_2017'
               Features            = 'SQLENGINE'
               SourcePath          = 'H:\SQL2017'
               SQLSysAdminAccounts = @('username')
               DependsOn           = '[WindowsFeature]NetFramework45'
          }
     }
}

**Comment by johlju** [comment]
The error means that Test-function did not find the correct desired state after install. Can you look at the bootstrap log (summary.txt) to see what the problem is?

See issue https://github.com/PowerShell/SqlServerDsc/issues/789

**Comment by smareano** [comment]
Hi, the issue happened to be the June update. Applied the latest update which has a fix for FIX PowerShell DSC Encrypted PSCredential property Issue and install went successfully. here is the link which tells about that in case some one needs it. 
https://www.anoopcnair.com/fix-powershell-dsc-encrypted-pscredential-issue/#:~:text=As%20per%20Microsoft%20documentation%2C%20the%20issues%20with%20PowerShell,11%20-%3E%20KB5015814%20Server%202022%2021H2%20-%3E%20KB5015827
