### ISSUE TITLE
The instance property should accept a * wildcard whenever possible

### ISSUE THREAD

**Issue by imarambiocatan** [PowerShell/SqlServerDsc#1144]
Being able to use a wildcard for the instance property would result in much more maintainable dsc powershell scripts and a lot less work for those that intend to use this module to enforce basic configuration standards. For example it would be possible to restrict the guest permissions for all the databases in all instances of a given host
Care should be taken to implement the wildcard in a way that lets users ignore certain databases (master, module and some others come to mind)

**Comment by johlju** [comment]
Labeling this as a discussion to see what the community thinks.
