### ISSUE TITLE
SqlSetup: Missing Configuration Feature/Options :  Tempdb File Configuration

### ISSUE THREAD

**Issue by mdaniou** [PowerShell/SqlServerDsc#1167]
#### Details of the scenario you tried and the problem that is occurring

This issue is created to bring some improvements to the SqlSetup DSC Configuration. The idea is to report all the missing options in the resource to be allow the installation of all the features and to use all the options available in the SQL Server installer.

Options to add to the DSC Resource :

/SQLTEMPDBFILECOUNT
/SQLTEMPDBFILESIZE
/SQLTEMPDBFILEGROWTH
/SQLTEMPDBLOGFILESIZE
/SQLTEMPDBLOGFILEGROWTH

#### The DSC configuration that is using the resource (as detailed as possible)

SqlSetup

#### Version of the operating system and PowerShell the target node is running

Windows Server 2012/2012R2/2016

#### SQL Server edition and version the target node is running

SQL Server 2016/2017

#### What SQL Server PowerShell modules, and which version, are present on the target node.

Most recent version

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch

Most recent version

**Comment by mdaniou** [comment]
@johlju could you please move this card to In Progress.
I am going to try to work on it.

**Comment by mdaniou** [comment]
👍

**Comment by SQLHorizons** [comment]
@mdaniou In my private repo I have a tempdb class that now using to configure tempdb, happy to bring this to the party but may need some assistance in meeting your code standards and converting it to run as DSC.  Happy to discuss

**Comment by SQLHorizons** [comment]
@johlju see [tempdb.ps1](https://github.com/SQLHorizons/.build/blob/master/.deploy/classes/tempdb.ps1)

**Comment by johlju** [comment]
@SQLHorizons love to look at that, but that link goes to a private repo (I got the invite, but haven't accepted yet) - since @mdaniou is working on this I think it would be better if you could share the code (and obfuscated any sensitive information) in a [public gist](https://gist.github.com/), and under MIT license (add a LICENSE.md file to the gist as well). Then @mdaniou could see if it help him in his work. 

@mdaniou how are your progression with this issue? No rush, just curious 😃

**Comment by mdaniou** [comment]
Hi @SQLHorizons @johlju,

I didn't start it yet. So feel free to take this on board. I was planning to work on it in October as I need to deploy a new environment under SQL2016

**Comment by adamrushuk** [comment]
Was looking for this feature, so would be awesome when it is supported. Keep up the good work guys :)

**Comment by mdaniou** [comment]
Don't worry I need it too asap so I'll get into this one during October hopefully.
I'm quite busy right now ... :)

**Comment by SQLHorizons** [comment]
@mdaniou @johlju gist can be found here: https://gist.github.com/SQLHorizons/74d1ca7856a5c243f0ddebb73dfeabf3

**Comment by mdaniou** [comment]
@johlju I love the way @SQLHorizons uses the class to configure tempdb. I'll see what I can pick from the code however, I don't want to over-engineer it. I think that I should just add few rows like for the other switches. The simpler the better.

**Comment by johlju** [comment]
@mdaniou Agreed. If we need maintain the tempdb there should be a new resource that does that.
