### ISSUE TITLE
MSFT_SqlSetup.psm1 is not digitally signed. You cannot run this script on the current system

### ISSUE THREAD

**Issue by cnilak** [PowerShell/SqlServerDsc#1170]
I am getting the below error, any idea? what's causing it?:
Importing module MSFT_SqlSetup failed with error - File C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\SqlServerDsc\11.2.0.0\DscResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1 cannot be
loaded. The file C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\SqlServerDsc\11.2.0.0\DscResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1 is not digitally signed. You cannot run this script on
the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
+ CategoryInfo : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
+ FullyQualifiedErrorId : ImportModuleFailed

Running this on Windows server 2012 R2 or Windows server 2016 (same issue)
PSVersion 5.1.14409.1012
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.14409.1012
CLRVersion 4.0.30319.34014
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

Execution Policy: RemoteSigned (can't have unrestricted)

**Comment by johlju** [comment]
Do you get the same error if you move the module to `C:\Program Files\WindowsPowerShell\Modules` and remove it from the `C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules`?

**Comment by cnilak** [comment]
Yes; I do
I also just tried to change the execution policy as below: and try again
 Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    RemoteSigned
   UserPolicy    RemoteSigned
      Process          Bypass
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted

But then I get this error ....
Importing module MSFT_SqlSetup failed with error - File C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\11.2.0.0\DscResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1 
cannot be loaded because you opted not to run this software now.

**Comment by johlju** [comment]
Maybe this is the problem? https://abelsquidhead.com/index.php/2015/06/06/dscimporting-module-failed/

**Comment by johlju** [comment]
Sorry, closed it by mistake.

**Comment by cnilak** [comment]
Tried that too, no luck 😑

**Comment by johlju** [comment]
It should just work by copying in the module in C:\Program Files\WindowsPowerShell\Modules\, this must be a configuration on your target node. Something must prevent it from loading. I have `RemoteSigned` on my lab servers and I just copy the module in to the folder. 

Did you remove the module from all other folders, and there is only one copy of the module in ` C:\Program Files\WindowsPowerShell\Modules\`? And those files is unblocked? 

If you remove the module from all Modules folders - and then run `Install-Module -Name SqlServerDsc``, does it work then?

**Comment by cnilak** [comment]
Tried both, still no luck :(

get-module -Name sqlserverdsc

ModuleType Version    Name                                ExportedCommands                                                                                                                    
---------- -------    ----                                ----------------                                                                                                                    
Manifest   11.2.0.0   sqlserverdsc

**Comment by cnilak** [comment]
![image](https://user-images.githubusercontent.com/17199975/42337201-fed55f90-8053-11e8-86af-c112e9a33dfd.png)

**Comment by johlju** [comment]
So copying should work. This is most likely due to that the folder and files needs to be unblocked (all files and folders), as of one of my previous links. Make sure the folder 'SqlServerDsc' is not blocked either.
See [`Unblock-File`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file).

```
Get-ChildItem -Path 'C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc' -Recurse | Unblock-File -Verbose
```

On the target node, this command must work before you can run any configuration. 

```powershell
Get-DscResource -Module SqlServerDsc
```

**Comment by cnilak** [comment]
grymt bra
That worked!! thanks mate, appreciated.

**Comment by sgbdev** [comment]
the unblock file think worked for me as well.
