### ISSUE TITLE
SqlServerEndpointPermission: Fails with "Grant failed for Endpoint..."

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#1176]
#### Details of the scenario you tried and the problem that is occurring
This error is only reported on the first run, and is successful on the second run. 

```
VERBOSE: [SQLTEST]: LCM:  [ Start  Set      ]  [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission]
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] Information: PowerShell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] Importing PowerShell module SQLPS.
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] Connected to SQL instance 'sqltest.company.local\SQL2016'.
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] 2018-07-04_17-38-38: Enumerating permissions for endpoint DefaultMirrorEndpoint
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] Information: PowerShell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] Importing PowerShell module SQLPS.
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] Connected to SQL instance 'sqltest.company.local\SQL2016'.
VERBOSE: [SQLTEST]:                            [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission] 2018-07-04_17-38-38: Grant permission to COMPANY\svc-SqlPrimary on endpoint DefaultMirrorEndpoint
Exception calling "Grant" with "2" argument(s): "Grant failed for Endpoint 'DefaultMirrorEndpoint'. "
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : FailedOperationException
    + PSComputerName        : sqltest.company.local

VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]  [[SqlServerEndpointPermission]SQL2016-HADREndpointPermission]  in 0.6720 seconds.
The PowerShell DSC resource '[SqlServerEndpointPermission]SQL2016-HADREndpointPermission' with SourceInfo 'E:\DSC\DSC-SQLTestConfig.ps1::1570::17::SqlServerEndpointPermission' threw one or more non-terminating errors while running the Set-TargetResource functi
onality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : sqltest.company.local

```
I have seen this error on one of my lab servers several times, but always tested something differently so ignored it. I have not looked into why the error occur, but submitting it here for reference and reminder.

#### The DSC configuration that is using the resource (as detailed as possible)
My lab servers is using a large configuration file to test a lot of different scenarios (toggles "on or off"). Gonna try posting it to a Gist when I have cleaned it up to test this error.

```
                SqlServerEndpointPermission $resourceConfigName
                {
                    Name = $Node.MirrorEndpointName
                    Ensure = 'Present'
                    ServerName = $Node.NodeName
                    InstanceName = $Node."$($currentSqlInstance)InstanceName"
                    Principal = $SqlServiceCredential.UserName
                    Permission = 'CONNECT'

                    PsDscRunAsCredential = $SqlAdministratorCredential

                    DependsOn = "[SqlServerEndpoint]$($currentSqlInstance)-HADREndpoint"
                }
```

#### Version of the operating system and PowerShell the target node is running
```
Caption                                     OSArchitecture Version  MUILanguages $PSVersionTable.PSVersion
-------                                     -------------- -------  ------------ -------------------------
Microsoft Windows Server 2012 R2 Datacenter 64-bit         6.3.9600 {en-US}      5.1.14409.1005
```

#### SQL Server edition and version the target node is running
```
Edition  : Enterprise Edition
Version  : 13.2.5026.0
Language : 1033

Edition  : Enterprise Edition
Version  : 12.1.4100.1
Language : 1033
```

#### What SQL Server PowerShell modules, and which version, are present on the target node.
```
Name         Version Path
----         ------- ----
SQLPS        1.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
SQLASCMDLETS 1.0     C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDL...
SQLPS        1.0     C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
Dev

**Comment by sqlbandit** [comment]
same issue here but mine does not succeed on the 2nd try!

**Comment by sqlbandit** [comment]
[[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] Preferred module SqlServer found.
VERBOSE: [UATLDNVMPBSQL13]:                            [[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] Importing PowerShell module SqlServer.
VERBOSE: [UATLDNVMPBSQL13]:                            [[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] Connected to SQL instance 'node1\instance,portnumber'.
VERBOSE: [node1]:                            [[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] 2018-07-19_16-36-02: Enumerating permissions for endpoint HADR_AlwaysON
VERBOSE: [node1]:                            [[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] Preferred module SqlServer found.
VERBOSE: [node1]:                            [[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] Importing PowerShell module SqlServer.
VERBOSE: [node1]:                            [[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] Connected to SQL instance 'node1\instancename,portnumber'.
VERBOSE: [node1]:                            [[SqlServerEndpointPermission]SQLConfigureEndpointPermission_instancename] 2018-07-19_16-36-02: Grant permission
to UK\svcAccount on endpoint HADR_AlwaysON
Exception calling "Grant" with "2" argument(s): "Grant failed for Endpoint 'HADR_AlwaysON'. "
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : FailedOperationException
    + PSComputerName        : node1

**Comment by johlju** [comment]
@sqlbandit looks similar except that you are using SqlServer module, and instance name has port number (?).

Can you provide the configuration you are running? 
If you add the permission manually using the same account that the resource are running as, does that work?
