### ISSUE TITLE
SQLSetup : SecurityMode  missing mixed authentication {SQL, Windows} ?

### ISSUE THREAD

**Issue by cnilak** [PowerShell/SqlServerDsc#1177]
I don't see an enum for mixed auth? am I missing something...

**Comment by johlju** [comment]
Setting the value to 'SQL' means mixed mode.

>Specifies the security mode for SQL Server.
>If this parameter is not supplied, then Windows-only authentication mode is supported.
>[Install SQL Server from the Command Prompt](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017#Install)

**Comment by SphenicPaul** [comment]
Also, might be woth noting this ... #1185
