### ISSUE TITLE
MSFT_SqlAGReplica  failed to execute Set-TargetResource functionality with error message: HADR is not enabled

### ISSUE THREAD

**Issue by cnilak** [PowerShell/SqlServerDsc#1182]
SqlServerLogin AddNTServiceClusSvc
        {
            Ensure               = 'Present'
            Name                 = 'NT SERVICE\ClusSvc'
            LoginType            = 'WindowsUser'
            ServerName           = $SqlNode
            InstanceName         = "MSSQLSERVER"
            PsDscRunAsCredential = $SqlInstallCredential
        }

        # Add the required permissions to the cluster service login
        SqlServerPermission AddNTServiceClusSvcPermissions
        {
            DependsOn            = '[SqlServerLogin]AddNTServiceClusSvc'
            Ensure               = 'Present'
            ServerName           = $SqlNode
            InstanceName         = "MSSQLSERVER"
            Principal            = 'NT SERVICE\ClusSvc'
            Permission           = 'AlterAnyAvailabilityGroup', 'ViewServerState'
            PsDscRunAsCredential = $SqlInstallCredential
        }

        SqlServerEndpoint HADREndpoint
        {
            EndPointName         = 'HADR'
            Ensure               = 'Present'
            Port                 = $portNumber
            ServerName           = $SqlNode
            InstanceName         = "MSSQLSERVER"
            PsDscRunAsCredential = $SqlInstallCredential
        }
  SqlAGReplica AddReplica
        {
            Ensure                     = 'Present'
            Name                       = $SqlNode
            AvailabilityGroupName      = $avgGroupName
            ServerName                 = $SqlNode
            InstanceName               = "MSSQLSERVER"
            PrimaryReplicaServerName   = $SqlPrimaryReplicaNode
            PrimaryReplicaInstanceName = "MSSQLSERVER"  
            PsDscRunAsCredential       = $SqlInstallCredential
            DependsOn                  = '[SqlSetup]InstallDefaultInstance'            
        }

**Comment by johlju** [comment]
You must enable AG with SqlAlwaysOnService resource.

**Comment by SphenicPaul** [comment]
I ran into this issue today.

Is it not worth adding this to the example [here](https://github.com/PowerShell/SqlServerDsc/blob/dev/Examples/Resources/SqlAG/1-CreateAvailabilityGroup.ps1) ?
