### ISSUE TITLE
MSFT_SqlSetup: Question - Providing $null values to non-required properties/parameters

### ISSUE THREAD

**Issue by SphenicPaul** [PowerShell/SqlServerDsc#1186]
Possibly more of a question rather than an issue...

I've been led to believe (although I've not verified this myself at present), that there are certain properties in the `SqlSetup` DSCResource that are only needed in certain cases but error when you pass them a $null value.

For example, the following...

- `ASSysAdminAccounts`
- `AsSvcAccount`

... properties/parameters are only needed when Analysis Services (AS) is installaed as part of the installation.

However, if you pass a `$null` value to them (rather than not setting them at all), these raise errors with the installations as it tries to use the `$null` value (e.g. tries to use `$null` as the Analysis Services (AS) service account/PSCredential).

Are there any thoughts on treating `$null` values in certain properties/parameters as if the properrty has not been used at all?

If I want to use the `SqlSetup` DSC resource in a configuration but then dynamically/programatically determine what features I'm installing (i.e. `SQL,` or **both** `SQL` and `AS`, for example) based on configuration data provided to it, then I **have** to setup the configuration to use the `ASSysAdminAccounts` property/parameter (it's needed for the `AS` installation) but passing a `$null` value (if I only install SQL and not AS) the SQL isntallation won't work (because it tries to use the `$null` credential).

Again, because I've not run this myself, I can't give you the error that stops the installation (unsure if it's a NULL username/credential or erroring because a credential value has been provided for AS service account but AS **isn't** being installed) but I'm unclear if this should really be stopping the installation (or if it's an unknown issue that is raised from an edge-case usage)?

The only workaround I can currently see is to create different configurations for different combinations of features and use the applicable `SqlSetup` properties where needed/required but this would create (in my view) a lot of duplication given that the majority of the other properties across configurations would be almost identical. There are also a significant number of combinations of available features which would mean a lot of configurations.

If anyone has any thoughts/suggestions that would be great.

**Comment by SphenicPaul** [comment]
Slightly related to my issue here (  #1185 ) as passing `$null` to the `SqlSetup` DSC resource's `SecurityMode` property/parameter actually then seems to "default" the value to `Windows` (rather than not using it at all).

**Comment by johlju** [comment]
If the parameter is used in a configuration then that is the desired state. If we would set a parameter to $null then $null is the desired state, so if anyone would manually set a value for that property then the configuration should set it back to $null (nothing). 
Leaving out a parameter from a configuration means that the property should be ignored when determining the desired state.
