### ISSUE TITLE
SQLAGReplica Failed to locate the AG Group

### ISSUE THREAD

**Issue by sqlbandit** [PowerShell/SqlServerDsc#1188]
Apologies if this is just lack of experience rather than an issue.

PowerShell DSC resource MSFT_SqlAGReplica  failed to execute Set-TargetResource functionality with error message: Unable to locate the availability group 'AGName' on the instance

My configuration data has 2 types of roles, PRIMARY and Secondary. I'm adding the AG on the PRIMARY (node1) and adding the Replica on the Secondary(node2)

I reckon the configuration on the secondary node is running first than the AG resource being added on the primary node. Is there a way to prevent this from happening ( wait for a resource on another machine?). 
Is there such thing like the xWaitForCluster while you are adding an AG replica?

#### Version of the operating system and PowerShell the target node is running
Caption                                   OSArchitecture Version  MUILanguages $PSVersionTable.PSVersion
-------                                   -------------- -------  ------------ -------------------------
Microsoft Windows Server 2012 R2 Standard 64-bit         6.3.9600 {en-US}      5.0.10586.117

#### SQL Server edition and version the target node is running
Edition  : Developer Edition
Version  : 11.4.7001.0
Language : 1033

Edition  : Developer Edition
Version  : 11.4.7001.0
Language : 1033

Edition  : Developer Edition
Version  : 14.0.1000.169
Language : 1033
-->

#### What SQL Server PowerShell modules, and which version, are present on the target node.
Name              Version
----              -------
SQLCheckCLR       1.0
SQLCheckCollation 1.0
SqlServer         21.0.17240
SQLASCMDLETS      1.0
SQLPS             1.0
SQLPS             14.0

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
Name         Version
----         -------
SqlServerDsc 11.2.0.0

**Comment by johlju** [comment]
Maybe `WaitForAll` can help with this scenario. https://docs.microsoft.com/en-us/powershell/dsc/waitforallresource

**Comment by sqlbandit** [comment]
@johlju  that did the trick, thank you :)
