### ISSUE TITLE
MSFT_SqlSetup - After install it does not seem to test the service accounts

### ISSUE THREAD

**Issue by wsmelton** [PowerShell/SqlServerDsc#1205]
#### Details of the scenario you tried and the problem that is occurring
Install SQL Server using a particular user name each for the SQL Server service and Agent. 

Then change the account to different user for both and recompile the MOF. Running this configuration again does not cause the service accounts to be tested and/or updated and LCM is returning that it is compliant.

#### The DSC configuration that is using the resource (as detailed as possible)
I'm using Azure Automation in this setup so I pull the credential object from Azure and it is returned to the variables below as a PSCredential object.
```
SqlSetup 'InstallInstance' {
            InstanceName         = $Node.InstanceName
            Features             = $Node.Features
            SQLCollation         = $Node.SQLCollation
            SQLSvcAccount        = $SqlServiceCredential
            AgtSvcAccount        = $SqlAgentServiceCredential
            PsDscRunAsCredential = $SqlInstallCredential
```

#### Version of the operating system and PowerShell the target node is running

```
Caption                                  OSArchitecture Version    MUILanguages $PSVersionTable.PSVersion
-------                                  -------------- -------    ------------ -------------------------
Microsoft Windows Server 2016 Datacenter 64-bit         10.0.14393 {en-US}      5.1.14393.2363
```
#### SQL Server edition and version the target node is running
```
Edition  : Developer Edition
Version  : 13.1.4001.0
Language : 1033
```

#### What SQL Server PowerShell modules, and which version, are present on the target node.
```
Name  Version Path
----  ------- ----
SQLPS 1.0     C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
```Name         Version  Path
----         -------  ----
SqlServerDsc 11.4.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\11.4.0.0\SqlServerDsc.psd1```

**Comment by wsmelton** [comment]
I'm adding the verbose output from `Update-DscConfiguration` that I run on the VM and you can see the setup is checked. Based on the output though it only seems to validate that the SQLENGINE is installed and then moves on to my next configuration.
[verbose.txt](https://github.com/PowerShell/SqlServerDsc/files/2318919/verbose.txt)

Should it do this or do I just need to start using the `MSFT_SqlServiceAccount` resource instead to make sure it is compliant to my requirements?

**Comment by johlju** [comment]
The `SqlSetup` resource only does what setup.exe can do. Once installed, and if installed with the wrong accounts, then `SqlServiceAccount` resource needs to be used to update those.

**Comment by wsmelton** [comment]
That is sad because I can't use the SqlServiceAccount that easily with Azure DSC. It depends on Server name being the actual server name, compared to something like `MSFT_SqlServerNetwork` that can handle using `localhost`. 

The `MSFT_SqlServiceAccount` passes in the name: https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/MSFT_SqlServiceAccount/MSFT_SqlServiceAccount.psm1#L279

Where the `MSFT_SqlServerNetwork` assumes localhost: https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/MSFT_SqlServerNetwork/MSFT_SqlServerNetwork.psm1#L38

Because I have Azure as my pull server it just causes more headache since they are not consistent.

**Comment by johlju** [comment]
It doesn't help setting `ServerName` to `'localhost'`? If not, then it seems we should change the helper function Get-ServiceObject to not pass in ServerName, since we always want to change this on current node. 🤔 
Please open a new issue for this.

**Comment by johlju** [comment]
@wsmelton thnaks for confirming that, I had no environment to test it in my self. Please open a new issue, so the resource SqlServiceAccount can be updated appropriately, and it a separate issue than the initial question of this issue.
