### ISSUE TITLE
MSFT_SqlAGReplica : Cannot use with non-standard, SQL instance ports?

### ISSUE THREAD

**Issue by SphenicPaul** [PowerShell/SqlServerDsc#1206]
#### Details of the scenario you tried and the problem that is occurring

Possibly related to issue #1189, but I'm trying to create some secondary replicas using the `SqlAGReplica` DSC resource within some configurations using non-standard ports. 

The SQL instances involved:
 - all use non-standard/default ports (i.e. not 1433) .. but are all the same as each other
 - have SQL Browser service DISABLED
 - all have the same (named) instance names (although, obviously on different nodes/hosts/servers)

(Security policy dictates the latter two are implemented within the organisation)

I've been able to create the Availability Group using the `SqlAG` DSC resource but adding the secondary replicas has been problematic (I'm suspecting because of the non-standard port). 

I can't currently see any example of how to successfully use this `SqlAGReplica` DSC resource with a non-standard port (if it is possible) and have tried a number of combinations of trying to add the port onto a number of the properties in the use of the resource - I keep receiving "Cannot connect" errors and "Replica not found" errors depending upon the values specified in the properties (some I expect are incorrect usages but I'm unclear of the correct usage).

Is it possible to confirm if this is possible or not? ...and if so, provide an example of how this can be done?

If it can't be done, through this DSC resource, is there a good alternative to this? - I suspect that similar functionality can be implemented with parameterised, T-SQL scripts (using the `SqlScript` DSC Resrouce) but that seems a little awkward to implement it that way.

Note: I HAVE been able to add the secondaries to the Availability Group via the SMSS GUI/wizard (in this method I can specify the `,(PortNo)` on the end of the named instance name when connecting) so I know that I can create the AG group manually, but not, as of yet, via a DSC configuration.

#### The DSC configuration that is using the resource (as detailed as possible)
```
(No example - Just standard use of the SqlAGReplica DSC resource)
```

#### Version of the operating system and PowerShell the target node is running
Wndows Server 2016 Core, PowerShell v5.1

#### SQL Server edition and version the target node is running
SQL Server 2016 Enterprise Core

#### What SQL Server PowerShell modules, and which version, are present on the target node.
SqlServer 21.0.17279

#### Version of the DSC module you're using, or write 'dev' if you're using current dev branch
SqlServerDsc 11.2.0.0

**Comment by johlju** [comment]
SqlAGReplica is using the helper function Connect-Sql to connect to the SQL instance, and what I'm seeing it should be possible to add port number to the InstanceName. Although, i can be something else that prevents it to connect.

What if you manually call the helper function `Connect-Sql` using port number to the instance name, does it connect?
https://github.com/PowerShell/SqlServerDsc/blob/dev/SqlServerDscHelper.psm1#L27

Can you provide the obfuscates verbose logs so we can see how far it come before it fails? And any error messages it fails with.

**Comment by SphenicPaul** [comment]
OK. So I've a few updates to this...


Firstly, using the `Connect-Sql` helper method (part1)...

Running from my own workstation  and running under my own user account (a 'sysadmin' on the SQL instances in the AG cluster), I **CAN** use `Connect-Sql` to connect to both SQL instances on my AG cluster using the port appended (with a comma) to the `SqlInstanceName` parameter value. For example...

```
$sqlPrimary = Connect-SQL -SQLServer $NodeNamePrimary -SQLInstanceName $($SQLInstanceName+","+$SQLTCPPort)

$sqlSecondary = Connect-SQL -SQLServer $NodeNameSecondary -SQLInstanceName $($SQLInstanceName+","+$SQLTCPPort)
```
...both connect to the the SQL instances. However, when I tried to use the `SetupCredential` parameter to run as a different credential, I kept receiving an exception relating to a missing library, like so...

```
Exception calling "Connect" with "0" argument(s): "Failed to load assembly Microsoft.SqlServer.ConnectionInfoExtended.dll. Error message: Could not load file or assembly 'microsoft.sqlserver.ConnectionInfoExtended, Version=14.100.0.0, Culture=neutral, 
PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified."
```

... although I'm actually trying to install this on a SQL2016 instance (not SQL2017) so was a little unclear where the requirement for that library was coming from and why importing the "SqlServerDsc" PSModule hadn't imported those (if, indeed, they were required). It doesn't look like this function gets called with the `SetupCredential` from the `SqlAGReplica` DSC resource anyway, so I've not looked at this any further.


Secondly, I had tried to PSRemote onto the secondary node (using my own credential) and tried the above again. This time,  I **COULD** connect to the SQL instance on the secondary node (the box I was PSRemoted onto) but, interestingly, could **NOT** connect to the primary node's SQL instance from the secondary node.

I've been able to establish that the relevant ports (used by the SQL instances) on each node are "open" and accessible from the other nodes in the cluster so I'm suspecting it's related to the credential/user that is being used - I'm not sure (in this case) if there is a "double-hop" issue where I'm PSRemoting from my local workstation to the secondary node and then trying to connect to the primary node from the secondary one and this is failing due to some "lack of delegation rights" sort of issue. This may be a slight misnomer to my actual issue because this doesn't exactly represent what will happen in the intended/attempted setup - This would be as follows:

- MOF files are generated and applied under the local system account on each node (primary and secondaries (only 1 secondary at present)).
- MOF file for each target ('localhost') is generated and applied on each target node from the same configuration data
- The "SqlAGReplica" step (which will only run on the secondaries) specifies a `PsDscRunAsCredential` property with a Windows domain, service account credential that is (currently) 'sysadmin' on all SQL instances in the HA cluster (WSFC).

The DSC resource is setup as below...

```
	# Add the availability group replica to the availability group
	SqlAGReplica 'AddSecondaryAgReplica'
	{

		ServerName                 = $NodeNameShort
		InstanceName               = $SQLInstanceName
					 
		AvailabilityGroupName      = $SqlAgName
		Name                       = $NodeNameShort + "\$SQLInstanceName"                 # Use $NodeNameShort name (non-FQDN of node/host this is being applied to) with port of SQL instance appended
		PrimaryReplicaServerName   = $SqlAgPrimaryNodeName
		PrimaryReplicaInstanceName = $SQLInstanceName + ",$SQLTCPPort"
					
		ProcessOnlyOnActiveNode    = $SqlAgProcessOnlyOnActiveNode
					
		EndpointHostName           = $NodeNameLong                                        # Use $NodeNameLong name (FQDN of node/host this is being applied to)

		Ensure                     = 'Present'
		DependsOn                  = "[SqlWaitForAG]$SqlWaitForAgResourceReferenceName"

		PsDscRunAsCredential       = $SQLDeploymentCredential                             # Note: Assumes SQL deployment account is identical on this (secondary) node/instance and primary node/instance (currently in 'sysadmin' role)

	}

			
```

When run as above (on the secondary node), the verbose output is as follows (Note: NodePrimary and NodeSecondary are the two node names, 'SQL' is the instance name and 25000 is the port used in the example (changed from the actual values))...

```
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer NodeSecondary with user sid <removed>.
VERBOSE: [NodeSecondary]: LCM:  [ Start  Set      ]
VERBOSE: [NodeSecondary]: LCM:  [ Start  Resource ]  [[SqlAGReplica]TestSqlAGReplica]
VERBOSE: [NodeSecondary]: LCM:  [ Start  Test     ]  [[SqlAGReplica]TestSqlAGReplica]
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Preferred module SqlServer found.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Importing PowerShell module SqlServer.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Connected to SQL instance 'NodeSecondary\SQL'.
VERBOSE: [NodeSecondary]: LCM:  [ End    Test     ]  [[SqlAGReplica]TestSqlAGReplica]  in 38.1690 seconds.
VERBOSE: [NodeSecondary]: LCM:  [ Start  Set      ]  [[SqlAGReplica]TestSqlAGReplica]
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Preferred module SqlServer found.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Importing PowerShell module SqlServer.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Preferred module SqlServer found.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Importing PowerShell module SqlServer.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Connected to SQL instance 'NodeSecondary\SQL'.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] The recommended account 'NT SERVICE\ClusSvc' is missing one or more of the following permissions: Trying with 'NT AUTHORITY\SYSTEM'.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Getting the effective permissions for the login 'NT AUTHORITY\SYSTEM' on 'SQL'.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Preferred module SqlServer found.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Importing PowerShell module SqlServer.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Connected to SQL instance 'NodeSecondary\SQL'.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] The cluster login 'NT AUTHORITY\SYSTEM' has the required permissions.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Preferred module SqlServer found.
VERBOSE: [NodeSecondary]:                            [[SqlAGReplica]TestSqlAGReplica] Importing PowerShell module SqlServer.
VERBOSE: [NodeSecondary]: LCM:  [ End    Set      ]  [[SqlAGReplica]TestSqlAGReplica]  in 9.0410 seconds.
PowerShell DSC resource MSFT_SqlAGReplica  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Failed to connect to SQL instance 'NodePrimary\SQL,25000'. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [NodeSecondary]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 59.637 seconds

```

...and having had a look a the PowerShell in the `SqlAGReplica` DSC resource, I suspect the exception is raised from/on the connection to the primary node/instance...

```
# Connect to the instance that is supposed to house the primary replica
                $primaryReplicaServerObject = Connect-SQL -SQLServer $PrimaryReplicaServerName -SQLInstanceName $PrimaryReplicaInstanceName

```


I am now suspecting it's more of a user/credential/delegation sort of problem/issue (i.e. the environment/setup I'm using), rather than the DSC resource itself, but I doubt there would be a double-hop in the actual/desired workings/setup and I'm presuming that the `Connect-SQL` function will be being called as the user/credential set as the `PsDscRunAsCredential` so I'm still a little unclear what the issue might be.

Any further thoughts/ideas?

**Comment by johlju** [comment]
Thank you for the detailed run through! Since you can connect to the instances from your workstation, then it should work from the servers, right? 🤔 

> I kept receiving an exception relating to a missing library

v14 of the .dll's are distributed with the SqlServer module, but I can't see that one part of the module downloaded from PowerShell Gallery, so that explains the error about missing module. Not part of this problem though, I think, as you mentioned.
SqlServerDsc runs the helper function Import-SQLP0 (we should change the name), which will load SqlServer module, which in turn loads the required assemblies it needs (the ones distributed with it self).

>  I'm presuming that the Connect-SQL function will be being called as the user/credential set as the PsDscRunAsCredential so I'm still a little unclear what the issue might be

Yes it should be, and either way you should have been able to run `Connect-SQL` from the primary and connect to secondary, or vice-verse when you did that manually, like you could from your workstation.

If it we strip it down even further, then this must be able to work.

```
Import-Module SqlServer
$sql = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList 'NodeSecondary\SQL,25000'
$sql.Status -match '^Online$' # This will try to connect, and should return $true if successful
```

If the account it is connecting with is not allowed access the above will not return an error. `$sql.Status` will just return `$null`. 

The above seems to fais over a PS Remoting session. I tested using the above when remoting from DEV, into SQLTEST, and in the remote session on SQLTEST, connect an instance on SQLTEST2 (without changing account, and account is sysadmin on the instance, and local admin on all nodes).
Please note that Browser service is running, so not accurate test compared to your environment, just tested to specify port number.

**Run in RDP session on server DEV**:
```
PS > Enter-PSSession sqltest
[sqltest]: PS > import-module sqlserver
[sqltest]: PS > $sql = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -Ar
gumentList 'SQLTEST2\MYTEST,52558'
[sqltest]: PS > $sql.Status -match '^Online$'
False
```

**Run in RDP session on server SQLTEST**:
It connects successfully.
```
PS > import-module sqlserver
PS > $sql = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList 'SQLTEST2\MYTEST,52558'
PS > $sql.Status -match '^Online$'
True
```

Maybe `SetupCredential` is necessary here instead, but since the initial problem with missing assembly, SQLPS should be tried. Currently I don't have the environment to test that. Could you verify with SQLPS and see if it behaves differently in remote session when using credentials?
Start this in a clean PS session so that the worng versions of assemblies are not loaded into the session.

```
Import-Module SQLPS
$SetupCredential = Get-Credential
$sql = New-Object -TypeName Microsoft.SqlServer.Management.Smo.Server -ArgumentList 'NodeSecondary\SQL,25000'
$sql.ConnectionContext.ConnectAsUser = $true
$sql.ConnectionContext.ConnectAsUserPassword = $SetupCredential.GetNetworkCredential().Password
$sql.ConnectionContext.ConnectAsUserName = $SetupCredential.GetNetworkCredential().UserName
$sql.ConnectionContext.Connect()
```
