### ISSUE TITLE
SqlScriptQuery: Could not find mandatory property GetQuery.

### ISSUE THREAD

**Issue by Anand-chenepalli** [PowerShell/SqlServerDsc#1250]
I am trying to use this example inhttps://github.com/PowerShell/SqlServerDsc/blob/dev/Examples/Resources/SqlScriptQuery/3-RunScriptCompleteExample.ps1  However, am getting an error as below.

Could not find mandatory property GetQuery. Add this property and try again.
    + CategoryInfo          : ObjectNotFound: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 6
    + PSComputerName        : localhost

**Comment by johlju** [comment]
Can you please add some more information to this issue,

* Verbose logs showing the problem
* SQL Server edition and version the target node is running
* SQL Server PowerShell modules present on the target node
* The operating system the target node is running
* Version and build of PowerShell the target node is running
* Version of the DSC module that was used

Please see the new [issue template](https://github.com/PowerShell/SqlServerDsc/issues/new?template=Problem_with_resource.md) for some help getting this information.
