### ISSUE TITLE
SqlServerEndpoint : Should let us choose the owner

### ISSUE THREAD

**Issue by mdaniou** [PowerShell/SqlServerDsc#1251]
#### Details of the scenario you tried and the problem that is occurring

I am configuring the endpoint and realise that its owner is the default one.
It seems to be advised that the owner would be 'sa'

I think that the resource should allow us to define that.

#### Suggested solution to the issue

The object Microsoft.SqlServer.Management.Smo.Endpoint has the property 'Owner' so I assume than adding a block like this one would do the job :

if ($PSBoundParameters.ContainsKey('Owner'))
{
	$endpointObject.Owner = $Owner
}

#### Version and build of PowerShell the target node is running

12.1.0.0

**Comment by johlju** [comment]
Sounds like a good addition to the resource! 🙂

**Comment by johlju** [comment]
Awesome. Looking forward to the PR. Once the PR is sent in I will label this as in progress.
