### ISSUE TITLE
SqlSetup : Doesn't support dynamics parameters (dynamic features)

### ISSUE THREAD

**Issue by mdaniou** [PowerShell/SqlServerDsc#1279]
#### Details of the scenario you tried and the problem that is occurring

I can't compile the configuration when I have the feature SQLENGINE in one node and SSAS in another one.
I can't use the same occurence of the SqlSetup to install either SQLENGINE or SSAS.

I can't have the parameters related to SSAS if the feature AS specified. It generates an error.
This is annoying when I want to use the same configuration script for my environment.

#### Verbose logs showing the problem

	PSDesiredStateConfiguration\Configuration : '' is not a valid value for property 'ASServerMode' on class 'SqlSetup'. Please change the value to one of the following strings: MULTIDIMENSIONAL, TABULAR, POWERPIVOT.
	At C:\Users\mdaniou\Downloads\Configuration.ps1:106 char:1
	+ Configuration InstallSqlServer
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
		+ FullyQualifiedErrorId : InvalidValueForProperty,Configuration

#### Suggested solution to the issue

It would be nice if the resource ignored the parameters if the feature is not to be installed.
It means removing some validation Sets and add the checks in the if blocks where the feature has to be installed.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

	if (!$Credentials)
	{
		$Credentials = Get-Credential
	}
	$TestDrive = $PSScriptRoot
	$configData = @{
		AllNodes = @(
			#region AllNodes
			@{
				NodeName                    = '*'
				Environment                 = 'Development'
				EnvironmentLetter           = 'D'

				#region Local Manager Configuration
					PSDscAllowDomainUser        = $true
					PsDscAllowPlainTextPassword = $true
					CertificateFile             = ''
					Thumbprint                  = ''
				#endregion

				#region Sql Server Instance and AvailabilityGroups
					SQLServerInstances =

						#region INST2016
						@{
							#region Sql Instance installation
							InstanceName                  = 'INST2016'
							CompatibilityLevel            = 130
							Features                      = 'SQLENGINE,BC,CONN'
														  
							ForceReboot                   = $true
							UpdateEnabled                 = 'false'
							SourcePath                    = '\\FileServer\iso\BINARIES\SQLSERVER2016\en_sql_server_2016_developer_with_service_pack_2_x64_dvd_12194995'
														  
							SQLCollation                  = 'Latin1_General_CI_AS'
							SQLSysAdminAccounts           = 'DOMAIN\AdminAccount'
							#endregion
								
							#region Service Startup types	      
							SqlSvcStartupType             = 'Automatic'
							AgtSvcStartupType             = 'Automatic'
							BrowserSvcStartupType         = 'Automatic'
							#endregion
														  
							#region Sql Server directories			      
							InstallSQLDataDir             = 'E:\MSSQL\Data'
							SQLUserDBDir                  = 'F:\MSSQL\Data'
							SQLUserDBLogDir               = 'G:\MSSQL\Log'
							SQLTempDBDir                  = 'H:\MSSQL\Temp'
							SQLTempDBLogDir               = 'G:\MSSQL\Temp'
							#endregion
						}, #endregion
						
						#region TABULAR
						@{
							#region Sql Instance installation
							InstanceName                  = 'TABULAR2017'
							ASServerMode                  = 'TABULAR'
							CompatibilityLevel            = 140
							Features                      = 'AS'
							TCPPort                       = ''
														  
							ForceReboot                   = $true
							UpdateEnabled                 = 'false'
							SourcePath                    = '\\Si-filer-app\iso\SQLSERVER\BINARIES\SQLSERVER2017\en_sql_server_2017_developer_x64_dvd_11296168'
														  
							ASCollation                   = 'Latin1_General_CI_AS'
							ASSysAdminAccounts            = 'DOMAIN\AdminAccount'
							#endregion
								
							#region Service Startup types
							AsSvcStartupType              = 'Automatic'
							#endregion
														  
							#region Sql ssas directories
							ASConfigDir                   = 'I:\OLAP\config'
							ASDataDir                     = 'J:\OLAP\Data'
							ASLogDir                      = 'K:\OLAP\Log'
							ASTempDir                     = 'L:\OLAP\Temp'
							#endregion
						} #endregion
				#endregion	
			}, #endregion

			#region INST2016
			@{
				NodeName                    = 'Server1'
				SqlServerInstancesCfg =
					@{
						InstanceName			        = 'INST2016'
					}
			}, #endregion

			#region TABULAR
			@{
				NodeName                    = 'Server2'
				SqlServerInstancesCfg =
					@{
						InstanceName			        = 'TABULAR'
					}
			} #endregion
		)
	}

	Configuration InstallSqlServer
	{
		param(
			[Parameter(Mandatory = $true)]
			[PSCredential]
			$ActiveDirectoryAdministratorCredential
		)

		Import-DscResource -ModuleName SqlServerDsc

		node $AllNodes.Nodename
		{
			#region Install SQL Server

			Foreach ($SQLServerInstance in ($Node.SqlServerInstances | Where-Object {$Node.SqlServerInstancesCfg.InstanceName -contains $_.InstanceName}))
			{
				SqlSetup 'InstallDefaultInstance'
				{
					# global param
					InstanceName           = $SqlInst.InstanceName
					Features               = $SqlInst.Features
					SourcePath             = $SqlInst.SourcePath
					UpdateEnabled          = $SqlInst.UpdateEnabled
					ForceReboot            = $SqlInst.ForceReboot

					# sqlengine param
					SQLCollation           = $SqlInst.SQLCollation
					SQLSysAdminAccounts    = $SqlInst.SQLSysAdminAccounts
					InstallSQLDataDir      = $SqlInst.InstallSQLDataDir
					SQLUserDBDir           = $SqlInst.SQLUserDBDir
					SQLUserDBLogDir        = $SqlInst.SQLUserDBLogDir
					SQLTempDBDir           = $SqlInst.SQLTempDBDir
					SQLTempDBLogDir        = $SqlInst.SQLTempDBLogDir

					# ssas param
					ASCollation            = $SqlInst.ASCollation
					ASSysAdminAccounts     = $SqlInst.ASSysAdminAccounts
					ASServerMode           = $SqlInst.ASServerMode
					ASConfigDir            = $SqlInst.ASConfigDir
					ASDataDir              = $SqlInst.ASDataDir
					ASLogDir               = $SqlInst.ASLogDir
					ASTempDir              = $SqlInst.ASTempDir

					PsDscRunAsCredential   = $SqlInstallCredential
				}
			}
			#endregion Install SQL Server
		}
	}

	$param =
	@{
		
	}

	$configurationParameters = 
	@{
		OutputPath                             = $TestDrive
		ConfigurationData                      = $configData
		ActiveDirectoryAdministratorCredential = $Credentials
	}
	InstallSqlServer @configurationParameters

#### SQL Server edition and version the target node is running

Not version related

#### SQL Server PowerShell modules present on the target node

12.0.0.0

#### The operating system the target node is running

Not related to OS version

#### Version and build of PowerShell the target node is running

not related

#### Version of the DSC module that was used ('dev' if using current dev branch)

master

**Comment by johlju** [comment]
I understand what you looking for, but I rather it fails if the user provides a parameter that does not work, otherwise the user could be unware that the setting in the configuration does nothing when the resource configuration is ran. I think it is better if throws an error saying the configuration is wrong. 

Instead you could add an if-block in the node-block to test what features is to be installed, and change the configuration block accordingly.

**Comment by mdaniou** [comment]
Well, I understand your point.

Then I have as many configuration blocks as I have combinations of Features ...

**Comment by johlju** [comment]
@mdaniou You could have a smarter helper function that builds entire configuration blocks from a specification of the roles you have defined, where each role have a set of features. In my opinion I don't think it should be one configuration that have code-logic to build different resulting configuration (different roles), but instead code-logic that builds the different role configurations. 🤔

**Comment by gaelcolas** [comment]
If I understand your concern correctly, @mdaniou you can use splatting (or more accurately, pseudo-splatting) in your configurations to avoid all those blocks.
Shameless plug of [my article](https://gaelcolas.com/2017/11/05/pseudo-splatting-dsc-resources/) and [piece of code here](https://github.com/gaelcolas/DscBuildHelpers/blob/master/DscBuildHelpers/ScriptsToProcess/Get-DscSplattedResource.ps1).

**Comment by mdaniou** [comment]
hi @gaelcolas,

This is indeed the first article I found and I tried it out.
It think that the workaround is nice however I kind of find it a bit counter-intuitive.
I need to ensure that my code is as understandable as possible for the next IT coming up to get it and not being an expert in PowerShell and DSC.
This is only my point-of-view ofc.

I guess splatting should simply be supported ...

**Comment by johlju** [comment]
I will close this issue at this time as 'not fixed'. Thanks for the discussion @mdaniou! 🙂

**Comment by mdaniou** [comment]
Thanks
