### ISSUE TITLE
SQLSetup Ressource Combines InstallSQLDataDir and  SQLUserDBDir for systemdatabases

### ISSUE THREAD

**Issue by ChristophHannappel** [PowerShell/SqlServerDsc#1287]
#### Details of the scenario you tried and the problem that is occurring
I've installed a SQL Server 2017 with the following Settings
```
InstallSQLDataDir      = 'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
SQLUserDBDir           = 'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
```

The systemdatabase files are at `F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data\MSSQL14.MSSQLSERVER\MSSQL\DATA` which should be at `F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data`.

Also the Folders for `Jobs` and `Log` are at `F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data\MSSQL14.MSSQLSERVER\MSSQL`

I've checked the Paths via SMS
 
|Name|Path|
|---|---|
|Root Directory|E:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL|
|Default Data location|F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data\|
|Default Log Location|G:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data\|
|Backup|F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Backup|

I've also checked the `ConfigurationFile.Ini` at `C:\Program Files\Microsoft SQL Server\140\Setup Bootstrap\Log\20190222_110425` and all paths are as declared.

#### Verbose logs showing the problem
n/a
#### Suggested solution to the issue
n/a
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SqlSetup 'SQL-DefaultInstance'
        {
            InstanceName = 'MSSQLSERVER'
            Features = 'SQLENGINE'
            SQLCollation = 'Latin1_General_CI_AS_KS_WS'
            SQLSvcAccount = $SQLServerDBEAccount
            AgtSvcAccount = $SQLServerAgentAccount
            SQLSysAdminAccounts = 'Domain\Group'
            InstallSharedDir       = 'E:\Program Files\Microsoft SQL Server'
            InstallSharedWOWDir    = 'E:\Program Files (x86)\Microsoft SQL Server'
            InstanceDir            = 'E:\Program Files\Microsoft SQL Server'
            InstallSQLDataDir      = 'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
            SQLUserDBDir           = 'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
            SQLUserDBLogDir        = 'G:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
            SQLTempDBDir           = 'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
            SQLTempDBLogDir        = 'G:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data'
            SQLBackupDir = 'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Backup'
            SourcePath = $node.SQLServerSetupPath
            UpdateEnabled = $true
            SqlTempdbFileCount     = 2
            SqlTempdbFileSize      = 1024
            SqlTempdbFileGrowth    = 512
            SqlTempdbLogFileSize   = 128
            SqlTempdbLogFileGrowth = 64
        }
```

#### SQL Server edition and version the target node is running
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node
|Name|Version|Path|
|---|---|---|
|SqlServer|21.1.18080|C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18080\SqlServer.psd1|
|SQLPS|14.0|E:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1|

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2828.amd64fre.rs1_release_inmarket.190216-1457
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
|Name                           |Value|
|---|---|
|PSVersion|5.1.14393.2828|
|PSEdition|Desktop|
|PSCompatibleVersions|{1.0, 2.0, 3.0, 4.0...}|
|BuildVersion|10.0.14393.2828|
|CLRVersion|4.0.30319.42000|
|WSManStackVersion|3.0|
|PSRemotingProtocolVersion|2.3|
|SerializationVersion|1.1.0.1|

#### Version of the DSC module that was used ('dev' if using current dev branch)
|Name|Version|Path|
|---|---|---|
|SqlServerDsc |12.3.0.0|C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\12.3.0.0\SqlServerDsc.psd1|

**Comment by johlju** [comment]
@ChristophHannappel Thanks for reporting this! Just so that I'm following you. The path you specify as `InstallSQLDataDir` 

```
InstallSQLDataDir      = 'F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data
```

That path is ignored and is (wrongly) set to `F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data\MSSQL14.MSSQLSERVER\MSSQL\DATA`

**Comment by ChristophHannappel** [comment]
> That path is ignored and is (wrongly) set to `F:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Data\MSSQL14.MSSQLSERVER\MSSQL\DATA`

Yes, thats exactly the case.
If neccessary i can set up a new VM and run the same configuration again.

**Comment by johlju** [comment]
That seems to be the way SQL Server does it, so this is by (SQL Server) design. We cannot change this in this resource.

>If you set an installation path for the Database Engine feature, SQL Server Setup uses that path as the root directory for all instance-specific folders for that installation, including SQL Data Files. In this case, if you set the root to "C:\Program Files\MicrosoftSQL Server\MSSQL14.<InstanceName>\MSSQL\", instance-specific directories are added to the end of that path.
> https://docs.microsoft.com/en-us/sql/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server?view=sql-server-2017#specifying-file-paths

**Comment by johlju** [comment]
I added a reference to this issue in the integration tests for SqlSetup, that this particular issue (the normal behaviour described in this issue) is being tested in the integration test.
