### ISSUE TITLE
SqlServerLogin: Can I add multiple groups or a mix of types WindowsGroup and WindowsUser?

### ISSUE THREAD

**Issue by jfrahm1987** [PowerShell/SqlServerDsc#1297]

**Comment by jfrahm1987** [comment]
Example of adding multiple groups.

$Groups = 'Domain\Group1','Domain\Group2','Domain\Group3'

        SqlServerLogin Add_WindowsGroups
        {
            Ensure               = 'Present'
            Name                 = $Groups
            LoginType            = 'WindowsGroup'
            ServerName           = 'TestServer.company.local'
            InstanceName         = 'DSC'
            PsDscRunAsCredential = $SqlAdministratorCredential
        }

**Comment by johlju** [comment]
You add a SqlServerLogin per group

```powershell
 SqlServerLogin Add_WindowsGroup1
    {
        Ensure               = 'Present'
        Name                 = 'Domain\Group1'
        LoginType            = 'WindowsGroup'
        ServerName           = 'TestServer.company.local'
        InstanceName         = 'DSC'
        PsDscRunAsCredential = $SqlAdministratorCredential
    }

 SqlServerLogin Add_WindowsGroup2
    {
        Ensure               = 'Present'
        Name                 = 'Domain\Group2'
        LoginType            = 'WindowsGroup'
        ServerName           = 'TestServer.company.local'
        InstanceName         = 'DSC'
        PsDscRunAsCredential = $SqlAdministratorCredential
    }
```

You can see example here too which show all variants:
https://github.com/PowerShell/SqlServerDsc/blob/dev/Examples/Resources/SqlServerLogin/1-AddLogin.ps1

**Comment by jfrahm1987** [comment]
I understand that you can add them individually. However what I am doing is taking input from a user through a GUI which kicks of the SQL install. So the groups are entered in a text box and assigned to a variable which is passed to DSC for the configuration of the SQL install. So having the ability to add multiple groups or users as you can do for the resource SqlServerRole using MembersToInclude would be very beneficial.

        SqlServerRole Add_Members_To_ServerAdmin
        {
            DependsOn = ("[SqlServerLogin]Add_WindowsGroup")
            Ensure               = 'Present'
            ServerRoleName       = 'sysadmin'
            MembersToInclude     = $SysAdminMembers
            ServerName           = $InstallServer
            InstanceName         = $InstallInstance
        }

**Comment by johlju** [comment]
Understand what you are trying to do now, but I don’t think we can change the resource to support that. It is not possible to uniquely identify the login if there are an array of logins passed into it instance of SqlServerLogin, that could lead to ping-pong behavior if for example partial configuration tries to update, add or remove the same user. An array cannot be of the qualifier type Key either. 

In your scenario you could take the array of logins and use `foreach` and build the unique configuration for the target node.

**Comment by jfrahm1987** [comment]
Ok thank you. That was my work around. Thought it was worth asking. :-)

**Comment by johlju** [comment]
Closing this issue at this time.

**Comment by johlju** [comment]
@jfrahm1987 questions are always welcome :) Thanks for contributing trying to make the resource better! :smile:
