### ISSUE TITLE
SQLServerSecureConnection:Service running under localsystem

### ISSUE THREAD

**Issue by Teutenberg** [PowerShell/SqlServerDsc#1300]
#### Details of the scenario you tried and the problem that is occurring
Resource SqlServerSecureConnection. Warning thrown when SQL Service account is running under LocalSystem. Configuration succeeds but warning is thrown. I'm guessing it tries to grant read permission to the certificate but fails because it tries to lookup LocalSystem, instead of SYSTEM which already has access. It continues and setup succeeds.

#### Verbose logs showing the problem
[[SqlServerSecureConnection]DirectResourceAccess] Adding read permissions to  
certificate '3acc800cb6683ecb2993af078c490f72799163ea' for account  
'LocalSystem'. 
VERBOSE: [SETTSQLD05]:                             
[[SqlServerSecureConnection]DirectResourceAccess] Certificate private key is  
located at  
'C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\a002f75e513b55798e61e9ed626a6f 
15_348db1eb-50e7-4748-ba78-9b0e4b21fc85'. 
VERBOSE: [SQLD05]: LCM:  [ End    Set      ]   
[[SqlServerSecureConnection]DirectResourceAccess]  in 1.1100 seconds. 
PowerShell DSC resource MSFT_SqlServerSecureConnection  failed to execute  
VERBOSE: Operation 'Invoke CimMethod' complete. 
VERBOSE: Time taken for configuration job to complete is 1.368 seconds 
Set-TargetResource functionality with error message: Exception calling  
"AddAccessRule" with "1" argument(s): "Some or all identity references could  
not be translated."  
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationMan  
   ager:String) [], CimException 
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure 
    + PSComputerName        : localhost 

#### Suggested solution to the issue
If service account is LocalSystem, grant permission to SYSTEM 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
  $Params = @{
      InstanceName    = $Instance.Instance
      Thumbprint      = $CertificateThumbprint
      ForceEncryption = $false
      Ensure          = 'Present'
      ServiceAccount  = $Instance.Service
  }

Invoke-DscResource -ModuleName SqlServerDsc -Name SqlServerSecureConnection -Property $Params -Method Set -Verbose

#### SQL Server edition and version the target node is running
SQL Server 2017 Enterprise

#### SQL Server PowerShell modules present on the target node
21.1.18068 SqlServer
12.1.0.0   SqlServerDsc

#### The operating system the target node is running
Windows Server 2016

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14393.2636
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2636
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by johlju** [comment]
Thanks for sending this in! Basically we should translate `'LocalSystem'` to `'SYSTEM'`, that sounds like a easy enough change.

**Comment by johlju** [comment]
I label this as a bug and help wanted so that anyone can pick this up. Also label it as 'good first issue' so if someone is new to GitHub and want to give it a try this sounds like a good place to start. 
Tag me if any help or pointers is needed. 🙂

**Comment by james-flynn-ie** [comment]
I'd like to give it a try, Johan.

@johlju, I guess I need to add an, "If $ServiceAccount = 'LocalSystem' Then set it to 'SYSTEM'" in Set-TargetResource here?https://github.com/PowerShell/SqlServerDsc/blob/dfd32b3ca3a364996a2dd9908f77dfb4f7f5f507/DSCResources/MSFT_SqlServerSecureConnection/MSFT_SqlServerSecureConnection.psm1#L204

**Comment by johlju** [comment]
Yes I guess it’s in the Set-function we need to switch you SYSTEM when LocalSystem is the service account. 
Although, we should make an integration test that test this scenario if possible. 
It is not possible to actually specify “SYSTEM” as the service account in the configuration?

**Comment by james-flynn-ie** [comment]
Thanks @johlju !

I see this integration test uses a generated service account, will I duplicate it and replace the service account with LocalSystem? https://github.com/PowerShell/SqlServerDsc/blob/dfd32b3ca3a364996a2dd9908f77dfb4f7f5f507/Tests/Integration/MSFT_SqlServerSecureConnection.config.ps1#L21

The build config should be OK AFAIK.

**Comment by johlju** [comment]
Yes duplicate it, there is a configuration in that file that needs to be duplicated. 
Also in the ...integration.tests.ps1 file you need to duplicate the test running the configuration. 

But what if we instead replace the account with `’SYSTEM’`, would it fail?

**Comment by james-flynn-ie** [comment]
I think it should have the same behaviour because LocalSystem inherits from SYSTEM : https://docs.microsoft.com/en-us/windows/desktop/Services/localsystem-account

**Comment by johlju** [comment]
I can’t remember the resource in my head (not available so I can look now), so I’m just guessing here. 
But could it possible that there are a simpler solution than changing the code? The problem seems that it want to set permission for LocalSystem since that is what is passed in the parameter ServiceAccount? If just the configuration instead would pass the user ‘SYSTEM’ in the parameter ServiceAccount then the code does not have to change? Meaning the user should make sure to translate LocalSystem to SYSTEM before passing it to the parameter ServiceAccount?

Does that make sense, or am I wrong on how this works? :)

**Comment by james-flynn-ie** [comment]
Sure Johan,

That sounds right to me, that the change isn't necessary if SYSTEM is used. I guess this defends against the LocalSystem account throwing an incorrect error. 

Do we need a documentation update instead, perhaps?

**Comment by johlju** [comment]
Yes I agree that this should be updated in the documentation. We could also add an example that shows it too. So please send in a PR for that :)

@Teutenberg could you please verify that changing to `’SYSTEM’` as the `ServiceAccount` solves this issue.

**Comment by james-flynn-ie** [comment]
https://github.com/PowerShell/SqlServerDsc/pull/1321
