### ISSUE TITLE
SqlDatabaseRecoveryModel: Can't use default instance with Invoke-SqlCmd

### ISSUE THREAD

**Issue by kungfu71186** [PowerShell/SqlServerDsc#1314]
In certain if not all resources, you have to specify InstanceName. When using Invoke-Sqlcmd, you can't set the instance name to MSSQLSERVER. It will timeout. 

```
SqlDatabaseRecoveryModel setModelRecoveryModel {
    Name          = 'model'
    ServerName    = 'SQLSERVER'
    InstanceName  = 'MSSQLSERVER'
    RecoveryModel = 'Simple'
}
```

Something like this will fail and if I specify an empty string I get this

`PowerShell DSC resource MSFT_SqlDatabaseRecoveryModel  failed to execute Test-TargetResource functionality with error message: Cannot validate argument on parameter 'InstanceName'. The argument is null 
or empty. Provide an argument that is not null or empty, and then try the command again`

A current workaround would be something like this:
```
SqlDatabaseRecoveryModel setModelRecoveryModel {
    Name         = 'model'
    ServerName   = 'SQLSERVER'
    InstanceName = ' ' #<---- space so it's not empty or null
    RecoveryModel = 'Simple'
}
```
Expected:
Should be able to connect to the default instance when using any resource that relies on invoke-sqlcmd.

Possible Solutions:
1. Check if instancename is MSSQLSERVER and replace the serverinstance parameter to sqlcmd to exclude the `.\MSSQLSERVER` piece.
2. Make InstanceName optional and if it's not specified, empty or null, leave that out of the command, so `SERVER\MYINSTANCE` will now become `SERVER` only without the `\MYINSTANCE` part

**Comment by johlju** [comment]
I think Option 1 is the best option, as it keeps the mandatory parameters and not introduce a breaking change. It sounds like an easy change. Anyone up fixing option 1? 🙂

**Comment by johlju** [comment]
This seems to only be a problem in this resource, the other resources using Invoke-Sqlcmd already handle this by using either option 1 (SqlRS) or option 2 (SqlScript, SqlScriptQuery).

Renaming the issue description to be SqlDatabaseRecoveryModel only.

**Comment by kungfu71186** [comment]
@johlji ok cool. I didn't really check the others, just assumed. Yeah I'll try to do a pull request later on

**Comment by kungfu71186** [comment]
So, I went to look at the code. It's using the common function Connect-SQL. Which does check for MSSQLSERVER. I tried it again and it's working. Maybe I just misspelled it or something. Looks like it was my mistake. Closing.
