### ISSUE TITLE
SqlScriptQuery - Output in Win_dsc ansible

### ISSUE THREAD

**Issue by SbalaCSC** [PowerShell/SqlServerDsc#1317]
ISSUE TITLE: 
     SqlScriptQuery - Output in Win_dsc ansible

    ISSUE DESCRIPTION (this template):
     I tried to incorporate SqlScriptQuery powershell example in Win_dsc ansible. It is working fine 
     but i am not seeing the success or error message in the output. 
   
    Code I am using: 
    - name: run sql DSC query
    win_dsc:
    resource_name: SqlScriptQuery
    ServerInstance: XXXXXXXXXX
    GetQuery: SELECT Name as DatabaseNAme FROM sys.databases WHERE Name = 'MyScriptDatabase1'
    TestQuery: If (select count(name) as DatabaseCount from sys.databases where name = 
     'MyScriptDatabase1') = 0
                BEGIN
                    RAISERROR ('Did not find database MyScriptDatabase1', 16, 1);
                END
                ELSE
                BEGIN
                    PRINT ('Found database MyScriptDatabase1');
                END
     SetQuery: CREATE DATABASE [MyScriptDatabase1]
     Credential_username: userN
     Credential_password: "{{ mssql_userN_password }}"
    
     My Output:
          ok: [XXXXXXX] => {
        "changed": false, 
        "module_version": "12.3.0.0", 
        "reboot_required": false
      }

       I am not getting stdout detail error message. Please let me know what i am doing wrong.

**Comment by johlju** [comment]
For the resource to return output you need to output the verbose messages. See example on line 3889 here https://ci.appveyor.com/project/johlju/sqlserverdsc/builds/23621150/job/nbm8rra0u8d3vjwj?fullLog=true#L3885

Although there is a bug that prevents the `PRINT` messages to show. The above links shows the output when the fix is used (I will send in a PR for the fix shortly).

**Comment by johlju** [comment]
@SbalaCSC I'm not sure how you would enable the verbose messages in Ansible. I have not used Ansible myself. If you get it to work, then please post the solution here. 

This issue will be closed when I merge the PR #1319. But please reopen this issue if you feel this needs to be discussed more.

**Comment by SbalaCSC** [comment]
@johlju Thanks for your reply. I will check and if i succeeded to enable the verbose messages in Ansible, i will definitely post the solution.
