### ISSUE TITLE
SqlAg: 'EndpointHostName' should be 'ComputerName' but is 'ComputerName.FQDN'

### ISSUE THREAD

**Issue by Teutenberg** [PowerShell/SqlServerDsc#1349]
#### Details of the scenario you tried and the problem that is occurring
Ag is configured correctly but DSC test method fails. 

$Params = @{
        Ensure               = 'Present'
        Name                 = $SqlAgName
        ServerName           = $env:COMPUTERNAME
        InstanceName         = $SqlInstanceName
        PsDscRunAsCredential = $SqlCred
    }
Invoke-DscResource -ModuleName SqlServerDsc -Name SqlAG -Property $Params -Method Test

#### Verbose logs showing the problem
[[SqlAG]DirectResourceAccess] 2019-04-30_14-25-53: 'EndpointHostName' should be 'SRV01' but is 'SRV01.DC.com'

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
$Params = @{
        Ensure               = 'Present'
        Name                 = $SqlAgName
        ServerName           = $env:COMPUTERNAME
        InstanceName         = $SqlInstanceName
        PsDscRunAsCredential = $SqlCred
    }
Invoke-DscResource -ModuleName SqlServerDsc -Name SqlAG -Property $Params -Method Test
```

#### SQL Server edition and version the target node is running
Microsoft SQL Server 2014 (SP3-CU3) (KB4491539) - 12.0.6259.0 (X64)   Apr  1 2019 22:19:54   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

#### SQL Server PowerShell modules present on the target node
Name         Version    Path                                                                                                   
----         -------    ----                                                                                                   
SqlServer    21.1.18102 C:\Program Files\WindowsPowerShell\Modules\SqlServer\SqlServer.psd1                                    
SQLASCMDLETS 1.0        C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLASCMDLETS\SQLASCMDLETS.psd1
SQLPS        1.0        C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1              

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19321.amd64fre.winblue_ltsb_escrow.190313-1806
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                                                                 
----                           -----                                                                                                                                                 
PSVersion                      5.1.14409.1018                                                                                                                                        
PSEdition                      Desktop                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                               
BuildVersion                   10.0.14409.1018                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                   
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used ('dev' if using current dev branch)
Name         Version  Path                                                                     
----         -------  ----                                                                     
SqlServerDsc 12.4.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\SqlServerDsc.psd1

**Comment by johlju** [comment]
I think it should not evaluate that property if it is not part of the configuration.

**Comment by Teutenberg** [comment]
This can be closed. The issue is due to having an EndpointHostName that was not configured by SqlServerDsc. I can pass the TEST method by passing parameter $EndpointHostName.
