### ISSUE TITLE
Incorrect capitalization of 'If' statement in MSFT_SqlSetup.psm1

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/SqlServerDsc#1387]
@johlju - I picked this up when implementing the new PSSA tests to check capitalization on statements:

This [line](https://github.com/PowerShell/SqlServerDsc/blob/dev/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L2391) has incorrect style (capital I in 'If').

**Comment by johlju** [comment]
Thanks for that! Looking forward to that common test!

**Comment by PlagueHO** [comment]
Yep, it should save us a fair amount of PR comments :grin:
