### ISSUE TITLE
sqlsetup

### ISSUE THREAD

**Issue by cosmos500** [PowerShell/SqlServerDsc#1390]
#### Details of the scenario you tried and the problem that is occurring
I am doing a script to install sql and also analysis services. SQL installs and analyisis service only partially in installs. It is listed in Object explorer but none of the services are installed.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
SqlSetup ($Node.NodeName)
           {
               #DependsOn = '[WindowsFeature]NET'
               SourcePath = $Node.SourcePath
               SourceCredential = $Node.InstallerServiceAccount
               InstanceName = $Node.InstanceName
               SQLCollation = $Node.Collation
               Features = $Node.Features
               SQLSysAdminAccounts = $Node.AdminAccount
               InstallSharedDir = $Node.BinaryPath
               InstallSharedWOWDir = $Node.BinaryPath86
               InstanceDir = $Node.InstancePath
               InstallSQLDataDir = $Node.SysDBPath
               SQLUserDBDir = $Node.UserDBPath
               SQLUserDBLogDir = $Node.UserDBLogPath
               SQLTempDBDir = $Node.TempDBPath
               SQLTempDBLogDir = $Node.TempDBLogPath
               SQLBackupDir = $Node.BackupPath
               ASServerMode = $Node.ASServerType
               ASSvcAccount = $node.InstallerServiceAccount
               ASSysAdminAccounts = $ServiceAccount
               ASConfigDir            = $Node.ASConfigPath
               ASDataDir              = $Node.ASDataPath
               ASLogDir               = $Node.ASLogPath
               ASBackupDir            = $Node.ASBackupPath
               ASTempDir              = $Node.ASTempPath
           }

#### SQL Server edition and version the target node is running
sql 2017

#### SQL Server PowerShell modules present on the target node
Import-DscResource –Module PSDesiredStateConfiguration
    Import-DscResource -Module SqlServerDsc
    Import-DscResource -Module xPSDesiredStateConfiguration
    Import-DscResource -Module xSQLServer
    Import-DscResource -Module xNetworking
    Import-DscResource -Module xCertificate

#### The operating system the target node is running
server 2016

#### Version and build of PowerShell the target node is running
5.1

**Comment by cosmos500** [comment]
ASConfigPath            = 'M:\OLAP\Config'
             ASDataPath              = 'M:\OLAP\Data'
             ASLogPath               = 'N:\OLAP\Log'
             ASBackupPath            = 'O:\OLAP\Backup'
             ASTempPath              = 'M:\OLAP\Temp'
             ASServerType            = "MULTIDIMENSIONAL"

**Comment by cosmos500** [comment]
When i run it a second time is does not see analysis services or reporting services. In object explorer they both show up but no services are installed.
Detecting Reporting Services feature.
VERBOSE: [MyServer]:                            [[SqlSetup]MyServer] Reporting Services feature not detected.
VERBOSE: [MyServer]:                            [[SqlSetup]MyServer] Detecting Analysis Services feature.
VERBOSE: [MyServer]:                            [[SqlSetup]MyServer] Analysis Services feature not detected.

**Comment by johlju** [comment]
Can you provide the full verbose logs from the first run?

**Comment by cosmos500** [comment]
I figured it out it was a problem with my list of Features
