### ISSUE TITLE
Install option Developer edition

### ISSUE THREAD

**Issue by tomfalk73** [PowerShell/SqlServerDsc#1415]
Maybe I'm missing it somewhere, but I haven't been able to find a way to install SQL under developer edition. If I leave out productkey, it installs an enterprise edition under evaluation. Not even sure if this is possible to do?

**Comment by johlju** [comment]
Are you using the media for Developer edition? It is a separate download from the free trial, see under Developer on this page https://www.microsoft.com/en-us/sql-server/sql-server-downloads 

Using the correct media it should install.

**Comment by tomfalk73** [comment]
I did, but turns out there were some leftover files from a previous installation. Once I cleared them, it installed dev edition. Thanks :)

**Comment by johlju** [comment]
Great that got it to work! Closing this issue.
