### ISSUE TITLE
SqlSetup: Get method called directly errors out

### ISSUE THREAD

**Issue by kjhosein** [PowerShell/SqlServerDsc#1423]
#### Details of the scenario you tried and the problem that is occurring

I have DSC code where the SqlSetup resource is throwing the error: 

> PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource function returned false when Set-TargetResource function verified the desired state. This indicates that the Set-TargetResource did not correctly set set the desired state, or that the function Test-TargetResource does not correctly evaluate the desired state. 

In walking through the DSC module's code, it appears that the `Set-TargetResource` function is calling the `Get-TargetResource` f'n, so I decided to install SQL Server manually using the same values as in my DSC code, then attempt to run `Get-TargetResource` directly to see what values it was getting:

```
$getTargetResourceParameters = @{
        Action                     = "InstallFailoverCluster"
        FailoverClusterNetworkName = "SQLNetName"
        InstanceName               = "MSSQLSERVER"
        SourcePath                 = "\\localhost\MSSQLmedia"
      }
Invoke-DscResource -Name SQLSetup -Method Get -Property $getTargetResourceParameters -Verbose -ModuleName SQLServerDSC
```

However, this throws an error and fails to return any info. See logs below.

I tried throwing in print statements and commenting out pieces of code in the `Get-TargetResource` function, even commenting out the `@return{}` completely (line 534) but it still threw the same error. There's a very good chance I'm leaving something out and/or doing something wrong, but I don't have any other pointers that can help me troubleshoot at this point.

#### Verbose logs showing the problem

Errors in console:

> VERBOSE: [ENC-SQLDB-DEV-1]:                            [[SqlSetup]DirectResourceAccess] Master Data Services (MDS) feature not detected.
>           A general error occurred that is not covered by a more specific error code.
>               + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
>               + FullyQualifiedErrorId : MI RESULT 1
>               + PSComputerName        : localhost
> 
> VERBOSE: Operation 'Invoke CimMethod' complete.
> VERBOSE: Time taken for configuration job to complete is 5.183 seconds

From the DSC Event Viewer logs:
        
> Message Unable to cast object of type 'System.String' to type 'System.Collections.IList'.
>         Parameter name: value 
>         HResult -2147024809 
>         StackTrack    at Microsoft.Management.Infrastructure.Internal.Data.CimPropertyOfInstance.set_Value(Object value)
>         at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetTargetResource(IntPtr resourceConfigurationInstanceHandle, IntPtr nonResourcePropetiesHandle, IntPtr metaConfigHandle, IntPtr regInstanceHandle, IStreamHandler plugInStreamsHandler, IntPtr& outputInstanceHandle, IntPtr& errorInstanceHandle)
>         at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, IntPtr instance, IntPtr nonResourcePropeties, IntPtr metaConfig, IntPtr regInstance, IntPtr outputInstance, IntPtr extendedError)

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### SQL Server edition and version the target node is running
Enterprise Edition 14.0.1000.169 (2017)

#### SQL Server PowerShell modules present on the target node
```
Name      Version    Path
----      -------    ----
SqlServer 21.1.18147 C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.18147\SqlServer.psd1
SQLPS     14.0       C:\Program Files (x86)\Microsoft SQL Server\140\Tools\PowerShell\Modules\SQLPS\SQLPS.psd1
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.503
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.503
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
`SqlServerDsc 13.1.0.0 C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.1.0.0\SqlServerDsc.psd1`

**Comment by johlju** [comment]
Could you change the block

https://github.com/PowerShell/SqlServerDsc/blob/2337c7cbaa9c47d5bf82802ec77167922ec892b6/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L534-L579

to

```powershell
$returnValue = @{
    SourcePath = $SourcePath
    Features = $features
    InstanceName = $InstanceName
    InstanceID = $instanceID
    InstallSharedDir = $installSharedDir
    InstallSharedWOWDir = $installSharedWOWDir
    InstanceDir = $instanceDirectory
    SQLSvcAccountUsername = $sqlServiceAccountUsername
    SqlSvcStartupType = $SqlSvcStartupType
    AgtSvcAccountUsername = $agentServiceAccountUsername
    AgtSvcStartupType = $AgtSvcStartupType
    SQLCollation = $sqlCollation
    SQLSysAdminAccounts = $sqlSystemAdminAccounts
    SecurityMode = $securityMode
    InstallSQLDataDir = $installSQLDataDirectory
    SQLUserDBDir = $sqlUserDatabaseDirectory
    SQLUserDBLogDir = $sqlUserDatabaseLogDirectory
    SQLTempDBDir = $null
    SQLTempDBLogDir = $null
    SqlTempdbFileCount = $SqlTempdbFileCount
    SqlTempdbFileSize = $SqlTempdbFileSize
    SqlTempdbFileGrowth = $SqlTempdbFileGrowth
    SqlTempdbLogFileSize = $SqlTempdbLogFileSize
    SqlTempdbLogFileGrowth = $SqlTempdbLogFileGrowth
    SQLBackupDir = $sqlBackupDirectory
    FTSvcAccountUsername = $fullTextServiceAccountUsername
    RSSvcAccountUsername = $reportingServiceAccountUsername
    RsSvcStartupType = $RsSvcStartupType
    RSInstallMode = $RSInstallMode
    ASSvcAccountUsername = $analysisServiceAccountUsername
    AsSvcStartupType = $AsSvcStartupType
    ASCollation = $analysisCollation
    ASSysAdminAccounts = $analysisSystemAdminAccounts
    ASDataDir = $analysisDataDirectory
    ASLogDir = $analysisLogDirectory
    ASBackupDir = $analysisBackupDirectory
    ASTempDir = $analysisTempDirectory
    ASConfigDir = $analysisConfigDirectory
    ASServerMode = $analysisServerMode
    ISSvcAccountUsername = $integrationServiceAccountUsername
    IsSvcStartupType = $IsSvcStartupType
    FailoverClusterGroupName = $clusteredSqlGroupName
    FailoverClusterNetworkName = $clusteredSqlHostname
    FailoverClusterIPAddress = $clusteredSqlIPAddress
}

foreach ($key in $returnValue.GetEnumerator())
{
    Write-Verbose "Key: $($key.Name); Value: $($key.Value)" -Verbose
}

return $returnValue
```

This will write out all the properties (when you run Invoke-DscResource) to see what values we have, please post them. Obfuscate any sensitive information, but don't remove for example multiple values (change the values to something else if they are sensitive). 

This would also interesting to see if it outputs all the values, then it gets that far at least.

**Comment by johlju** [comment]
According to your verbose logs is looks like this row is the last that is reporting a verbose message`

https://github.com/PowerShell/SqlServerDsc/blob/2337c7cbaa9c47d5bf82802ec77167922ec892b6/DSCResources/MSFT_SqlSetup/MSFT_SqlSetup.psm1#L449

What I'm looking for is if the error occurs after the `return`-statement or before.

**Comment by kjhosein** [comment]
Hi @johlju,

Thanks for the quick response. 
After I had posted this issue, I managed to get the SQLSetup DSC resource to run. Now running the `Invoke-DscResource` returns output without error. However, the only keys that have values are:

```
ModuleName                 : SQLServerDSC
ModuleVersion              : 13.1.0.0
InstanceName               : MSSQLSERVER
SourcePath                 : \\localhost\MSSQLmedia
PSComputerName             : localhost
```

I then modified the `MSFT_SqlSetup.psm1` code per your request and got the same results.

---

There's another wrinkle in all of this: Although the DSC resource ran and installed SQL Server, it did not do it flawlessly. It created the Cluster Role for SQL Server. However, it failed to bring the IP address online. I had to manually add a new IP Address cluster resource to the role, then make it a dependency, then bring it online, then bring the role online. 

The error at the end of the run was the same as in my original post: 
>PowerShell DSC resource MSFT_SqlSetup failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource function returned false when Set-TargetResource function verified the desired state. This indicates that the Set-TargetResource did not correctly set set the desired state, or that the function Test-TargetResource does not correctly evaluate the desired state.

This error message makes sense to me because the Get method isn't retrieving any values for FailoverClusterIPAddress or FailoverClusterNetworkName.

**Comment by johlju** [comment]
So the Get-method returns the expected values? Then I think we can close this issue?

Could you please create a new issue regarding the problem with the missing IP address cluster resource?

**Comment by kjhosein** [comment]
I'm still puzzled why the Get-method would fail when there is a working SQL Server install...

--
Sure, I'll open up a new issue for the missing values.

**Comment by johlju** [comment]
Yes, I agree, but if you can reproduce it now, it might be difficult to find the root cause?

**Comment by johlju** [comment]
That is great that you can reproduce the issue. Did you add the code change in https://github.com/PowerShell/SqlServerDsc/issues/1423#issuecomment-523864849 that I suggested? Could you please post the verbose logs from when you re-ran and got the issue. Obfuscate any sensitive data. I like to see how far it gets before it errors out so we can try to pin-point the root cause.

**Comment by kjhosein** [comment]
Sorry, I forgot to say that I had added the code change per your comment and _then_ re-ran the test. The error logs are exactly the same as what I had pasted in the original post. Did you want every single line of the console output? Everything prior to the error seemed fine.

**Comment by johlju** [comment]
So it fails before it can output the verbose messages you added? If so, since you can reproduce the issue, can you pin-point what row it fails on in the Get-TargetResource?

**Comment by kjhosein** [comment]
As I'm unable to pinpoint what row it fails on and I'm I can't _consistently_ reproduce this error, I'm closing this issue (at least for now).
