### ISSUE TITLE
SqlServerLogin: Unable to successfully run

### ISSUE THREAD

**Issue by erschef** [PowerShell/SqlServerDsc#1424]
I'm attempting to include a couple instances of SqlServerLogin within a DSC script to add SQL logins for a domain service account as well as the Domain Admins group, with the code below:

        # Add SQL logon for SQL service account
        SqlServerLogin Add_SQLService
        {
            Ensure                          = 'Present'
            Name                           = $sqlsvccreds.UserName
            LoginType                    = 'WindowsUser'
            ServerName                 = $serverFQDN
            InstanceName              = 'MSSQLSERVER'
            PsDscRunAsCredential = $LocalAdminCreds
        }
        
        # Add SQL logon for Domain Admins
        SqlServerLogin Add_DAGroup
        {
            Ensure                          = 'Present'
            Name                           = 'domain.name\Domain Admins'
            LoginType                    = 'WindowsGroup'
            ServerName                 = $serverFQDN
            InstanceName              = 'MSSQLSERVER'
            PsDscRunAsCredential = $LocalAdminCreds
            DependsOn                  = '[SqlServerLogin]Add_SQLService'
        }

The MOF compiles successfully, but when I apply the configuration with "Start-DscConfiguration -Path ".\" -Wait -Verbose -Force" I get the error below for both SqlServerLogin blocks (I've only posted one example for brevity):

PowerShell DSC resource MSFT_SqlServerLogin  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: Creation of the login 'agm.test\Domain Admins' failed. ---> 
System.Management.Automation.MethodInvocationException: Exception calling "Create" with "0" argument(s): "Create failed for Login 'agm.test\Domain Admins'. " ---> Microsoft.SqlServer.Management.Smo.FailedOperationException: 
Create failed for Login 'agm.test\Domain Admins'.  ---> Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch. ---> 
System.Data.SqlClient.SqlException: Windows NT user or group 'agm.test\Domain Admins' not found. Check the name again.
   at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)
   at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(StringCollection sqlCommands, ExecutionTypes executionType, Boolean retry)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ExecuteNonQuery(StringCollection queries, Boolean includeDbContext, Boolean executeForAlter)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.CreateImplFinish(StringCollection createQuery, ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.CreateImpl()
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.CreateImpl()
   at CallSite.Target(Closure , CallSite , Login )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace --- 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

The server is domain-joined, and I've confirmed that the referenced account and group exists. The PsDscRunAsCredential referenced already has a SQL login and is a member of the 'sysadmin' role, and I have no issues manually creating these SQL logins from SSMS with that credential. Am I doing this correctly or am I missing something? I've tried many different iterations of this code and have adhered to the examples posted in the Wiki with no success. I could definitely use some help here, thanks!

**Comment by johlju** [comment]
I wonder if it is because of `domain.name`. If I use the NetBIOS domain name it works. I don't get the same error, but might be the cause?

```
PS >   Invoke-DscResource -Name SqlServerLogin -Method Set -ModuleName SqlServerDsc -Property @{
    Ensure               = 'Present'
    Name                 = 'contoso.com\Domain Admins'
    LoginType            = 'WindowsGroup'
    ServerName           = 'localhost'
    InstanceName         = 'SQL2016'
    PsDscRunAsCredential = $mockDomainUserCredential
} -Verbose

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceSet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQLTEST with user sid S-1-5-21-2246212248-426023572-517575333-1441.
VERBOSE: [SQLTEST]:                            [DSCEngine] Importing the module C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.0.0.0\DscResources\MSFT_SqlServerLogin\MSFT_SqlServerLogin.psm1 in force mode.
VERBOSE: [SQLTEST]: LCM:  [ Start  Set      ]  [[SqlServerLogin]DirectResourceAccess]
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Importing the module MSFT_SqlServerLogin in force mode.
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Importing the module MSFT_SqlServerLogin in force mode.
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Preferred module SqlServer found. (SQLCOMMON0023)
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Importing PowerShell module 'SqlServer' with version '21.1.18102' from path 'C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.1810
2\SqlServer.psm1'. (SQLCOMMON0025)
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Connecting as current user 'contoso\johlju.admin' using integrated security. (SQLCOMMON0054)
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Connected to SQL instance 'localhost\SQL2016'. (SQLCOMMON0018)
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Creating the login 'contoso.com\Domain Admins', with the login type 'WindowsGroup', on the instance 'localhost\SQL2016'.
VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]  [[SqlServerLogin]DirectResourceAccess]  in 0.7970 seconds.
An internal error occurred. 
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x8007054f
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.085 seconds
```

```
PS >   Invoke-DscResource -Name SqlServerLogin -Method Set -ModuleName SqlServerDsc -Property @{
        Ensure                          = 'Present'
        Name                           = 'contoso\Domain Admins'
        LoginType                    = 'WindowsGroup'
        ServerName                 = 'localhost'
        InstanceName              = 'SQL2016'
        PsDscRunAsCredential = $mockDomainUserCredential
    } -Verbose

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = ResourceSet,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SQLTEST with user sid S-1-5-21-2246212248-426023572-517575333-1441.
VERBOSE: [SQLTEST]:                            [DSCEngine] Importing the module C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\13.0.0.0\DscResources\MSFT_SqlServerLogin\MSFT_SqlServerLogin.psm1 in force mode.
VERBOSE: [SQLTEST]: LCM:  [ Start  Set      ]  [[SqlServerLogin]DirectResourceAccess]
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Importing the module MSFT_SqlServerLogin in force mode.
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Importing the module MSFT_SqlServerLogin in force mode.
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Preferred module SqlServer found. (SQLCOMMON0023)
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Importing PowerShell module 'SqlServer' with version '21.1.18102' from path 'C:\Program Files\WindowsPowerShell\Modules\SqlServer\21.1.1810
2\SqlServer.psm1'. (SQLCOMMON0025)
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Connecting as current user 'contoso\johlju.admin' using integrated security. (SQLCOMMON0054)
VERBOSE: [SQLTEST]:                            [[SqlServerLogin]DirectResourceAccess] Connected to SQL instance 'localhost\SQL2016'. (SQLCOMMON0018)
VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]  [[SqlServerLogin]DirectResourceAccess]  in 1.9370 seconds.
VERBOSE: [SQLTEST]: LCM:  [ End    Set      ]    in  2.1870 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.

RebootRequired 
-------------- 
False          
VERBOSE: Time taken for configuration job to complete is 2.333 seconds
```

**Comment by erschef** [comment]
@johlju  Thanks for the update, yes, using the NETBIOS name seems to work, although I'll have to shuffle my variables around a little bit as I'm passing in the FQDN from an ARM template; I think this is the solution, let me modify some things on my end and hopefully clear it up, and I'll close the issue accordingly. Thanks for the suggestion, this was driving me crazy!

**Comment by johlju** [comment]
yes, since it is a space in the name it is not possible to write it as `'groupname@shamn.se'` either, not sure that works even without a space, not sure I have ever tried. 🤔

**Comment by erschef** [comment]
After juggling my input variables around this issue seems to be fixed, with the root cause being that the module does not support the use of FQDN, and only supports NETBIOS domain name. Lesson learned, thanks!

**Comment by johlju** [comment]
@erschef Glad you got it to work! Thanks for submitting the issue!
