### ISSUE TITLE
SqlServerDatabaseMail: New resource

### ISSUE THREAD

**Issue by SQLHorizons** [PowerShell/SqlServerDsc#155]
xdBmail is an additional resource I've been developing to setup the default database mail profile and account during SQL roll out.

Usage - configure a default mail profile for SQL agent jobs and alerts.

**Comment by johlju** [comment]
This is being worked on in pr #145. It is suggested to rename this resource to 'MSFT_xSQLServerDatabaseMail'

**Comment by johlju** [comment]
Renamed the title of this issue, and the title of the PR #145 (which has been submitted with a proposal). 

To everyone:
**Is anyone interested in running with this resource and continue the work in PR #145?**

Below is the proposed schema.mof as of today. Please give some feedback on this for improvements. 

For example, shouldn't ReplyToAddress be a string array? And how should the resource handle enabling and disabling of database mail? When the first 'Present' configuration it will enable database mail, and when the last is removed with 'absent' it should disable database mail? Or should it be an entire new resource to enable or disable database mail, and this proposed resource only adds "profiles"?

```
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabaseMail")]
class MSFT_xSQLServerDatabaseMail : OMI_BaseResource
{
    [Key, Description("None yet.")] String AccountName;
    [Key, Description("The name of the SQL instance to be configured.")] String SQLInstanceName;
    [Required, Description("None yet.")] String EmailAddress;
    [Required, Description("None yet.")] String MailServerName;
    [Required, Description("None yet.")] String ProfileName;
    [Write, Description("An enumerated value that describes if the database mail configuration should be added ('Present') or removed ('Absent'). Default value is 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The host name of the SQL Server to be configured.")] String SQLServer;
    [Write, Description("None yet. Default value is the same value assigned to parameter SQLServer.")] String DisplayName;
    [Write, Description("None yet. Default value is the same e-mail address assigned to parameter EmailAddress.")] String ReplyToAddress;
    [Write, Description("None yet. Default value is 'Mail account to send alerts for the DBAs'.")] String Description;
    [Write, Description("Type of mail server. Currently the only option is 'SMTP'. Default value is 'SMTP'."), ValueMap{"SMTP"}, Values{"SMTP"}] String MailServerType;
    [Write, Description("The TCP port used for communication. Default value is 25 (TCP port 25).")] UInt16 Port;
};
```

**Comment by johlju** [comment]
@randomnote1 and @nabrond Is `SqlServerDatabaseMail` the best and correct name for this resource, or should we change it?  The feature is called 'Database Mail' (?). So it might be that SqlServerDatabaseMail is best and correct name. What do you guys think? I'm I thinking correctly below.

`<Module Identifier>[<Component>][<Action>]<Scope>{<Feature>|<Property>}`

**Module Identifier:** Sql
**Component:**: -
**Action:** -
**Scope:** Server
**Feature:** DatabaseMail

Name: `SqlServerDatabaseMail`

*PR moving closer to the finish line, I should fix code for 'Absent' and make it localized, after that I think we can merge the resource, so it can be improved later on. Basic stuff works.*

**Comment by randomnote1** [comment]
@johlju, I think that looks right. I had to re-read the guidelines to make sure.

**Comment by johlju** [comment]
@randomnote1 Thanks!
