### ISSUE TITLE
Discussion: Get-method needs SourcePath for each push/pull to determine SQL major version

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#173]
Open this issue to discuss if we can solve getting the SQL major version from another place than using file version of the setup.exe in the source media folder.
After SQL major version are fetched from setup.exe the Get-method use the major version number in four instances (the `$SQLVersion` local variable).

 * Building the service name of the Integration Service. Ie. `MsDtsServer120`. This is later used to determine if the service installed or not (and adds 'IS' to the features list).
 * Used to determine if SSMS is installed. Each major version has different unique product identifiers. 
 * Used to determine if ADV_SSMS is installed. Each major version has different unique product identifiers. 
* Getting the paths to the Shared Directory and Shared WOW Directory.

We need to have another way to individually get the correct major version number for these, since each can be installed individually. I think the original coder used the setup.exe to know exactly what version was to be evaluated.

**Comment by johlju** [comment]
_@nabrond commented on this in the issue #167. To liberty to move his comment here,_

I like the idea of not relying on setup.exe for determining version information in the Get method. This should be fairly easy to get from the registry at `HKLM:\Software\Microsoft\Microsoft SQL Server\<Instance>\MSSQLServer\CurrentVersion` since the method would know the instance that should be installed.

**Comment by johlju** [comment]
@nabrond I know that the registry key you are referring to is not present when you install Integration Services as a standalone install (without the Database Engine). _But should the resource be able to install as a standalone install._ _I submitted an issue #174 to discuss that as well._

Since the registry is not present we need another way to determine version. I investigating what registry keys actually are present after a standalone install. Or if there are any files that can be used.

If anybody has knowledge about this, please chip in! 😄

**Comment by nabrond** [comment]
Being that IS is a shared feature, its version information is stored in a different location. Check the following registry value:  ````HKLM:\Software\Microsoft\Microsoft SQL Server\<Version>\DTS\Setup\Version````. It should give you the current patch level for that version of SSIS.

**Comment by johlju** [comment]
Yes, it does, for IS of SQL 2014 the following is set in the registry.
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\120\DTS\Setup]
"Version"="12.1.4100.1"
"PatchLevel"="12.1.4100.1"
```

But let say we have this scenario. 
We install Integration Services from SQL 2014 on one node successfully. 
On the same node we also want to install Integration Services from SQL 2016. The Test-method evaluates (using Get-method) the registry keys for each possible major version `HKLM:\Software\Microsoft\Microsoft SQL Server\<MajorVersion>\DTS\Setup\Version`. It finds the registry key for the SQL 2014 Integration Service and returns `'IS'` in the `Features` item of the hash table. Since the feature is "already installed" the Test-method will return `$true` and SQL 2016 IS will not be installed.
If we would change so that the Get-method also return the major version that was found, then we need something to compare that too, to see what major version we are expected to install. The Test-method does not have that information unless the user provide that in a parameter (or we hit the media as doing today).

I'm scratching my head to see if there is another way, but right now the only way I see to solve this would be that the user provides which SQL major version the resource are suppose to install. 

Is there another way? 🤔
