### ISSUE TITLE
Question about smo class if Management Studio is not installed

### ISSUE THREAD

**Issue by luigilink** [PowerShell/SqlServerDsc#216]
It's not (yet) an issue, but I have a few customer that don't install Management Studio Feature.
So what's happen with the function like connect-sql that uses 'Microsoft.SqlServer.Smo' ?

I start looking another way to manage sql object with PowerShell, we have T-SQL and WMI (but not recommended, CIMInstance is better)

What do you think about this question ?

**Comment by nabrond** [comment]
Regardless of whether Management Studio is installed, the SQLPS module is installed. This module is still used to support the PowerShell subsystem for SQL Agent jobs.

**Comment by johlju** [comment]
I agree, I don't have SSMS installed in my lab and it still can load both SQLPS and use SMO class objects.

@luigilink if you find a scenario that this is not the case, then absolutely we need another solution.

**Comment by luigilink** [comment]
It was a customer feedback, you're right it works without Management Studio feature.
You can closed thi issue for now, I'll re-open it when I'll have more details of the issue scenario.

**Comment by johlju** [comment]
Closing issue as per request.
