### ISSUE TITLE
SqlServerMemory: fails 'test' phase.

### ISSUE THREAD

**Issue by marcinbojko** [PowerShell/SqlServerDsc#342]
**Details of the scenario you try and problem that is occurring:**
When you try to run xSWQServerMemory with 'test' and 'set' phase, test phase ALWAYS fails, even if proper values are already set (manually).

> VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourcetest,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = 
> root/Microsoft/Windows/DesiredStateConfiguration'.
> VERBOSE: An LCM method call arrived from computer TEST-PUSQL with user sid S-1-5-21-3787406103-2630137757-1549065555-15829.
> VERBOSE: [TEST-PUSQL]: LCM:  [ Start  Test     ]  [[xSQLServerMemory]DirectResourceAccess]
> VERBOSE: [TEST-PUSQL]:                            [[xSQLServerMemory]DirectResourceAccess] 2017-01-25_14-27-37: Connected to SQL test-pusql
> VERBOSE: [TEST-PUSQL]: LCM:  [ End    Test     ]  [[xSQLServerMemory]DirectResourceAccess] False in 0.2030 seconds.
> The PowerShell DSC resource C:\Program Files\WindowsPowerShell\Modules\xSQLServer\4.0.0.0\DscResources\MSFT_xSQLServerMemory returned results in a format that is not 
> valid. The results from running Test-TargetResource must be the boolean value True or False.
>     + CategoryInfo          : InvalidResult: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : TestTargetResourceInvalidResultFormat
>     + PSComputerName        : localhost
>  
> VERBOSE: Operation 'Invoke CimMethod' complete.
> VERBOSE: Time taken for configuration job to complete is 0.703 seconds
> {"rebootrequired":false,"indesiredstate":null,"errormessage":""}
> 

**The DSC configuration that is using the resource (as detailed as possible):**

```powershell
$script:ErrorActionPreference = 'Stop'
$script:WarningPreference     = 'SilentlyContinue'

function new-pscredential
{
  [CmdletBinding()]
  param (
    [parameter(Mandatory=$true,
      ValueFromPipelineByPropertyName=$true)]
    [string]
    $user,

    [parameter(Mandatory=$true,
      ValueFromPipelineByPropertyName=$true)]
    [string]
    $password
  )

  $secpasswd   = ConvertTo-SecureString $password -AsPlainText -Force
  $credentials = New-Object System.Management.Automation.PSCredential ($user, $secpasswd)
  return $credentials
}

$response = @{
  indesiredstate = $false
  rebootrequired = $false
  errormessage   = ''
}

$invokeParams = @{
  Name          = 'xSQLServerMemory'
  Method        = 'test'
  Property      = @{
    dynamicalloc = $true
    minmemory = 1024
    maxmemory = 2048
    sqlserver = 'test-pusql'
    sqlinstancename = 'MSSQLSERVER'
  }
  Verbose=$true
  ModuleName = @{
    ModuleName      = "C:\Program Files\WindowsPowerShell\Modules\xSQLServer\4.0.0.0\xSQLServer.psd1"
    RequiredVersion = "4.0.0.0"
  }
}

try{
    $result = Invoke-DscResource @invokeParams
}catch{
  $response.errormessage   = $_.Exception.Message
  return ($response | ConvertTo-Json -Compress)
}

# keep the switch for when Test passes back changed properties
switch ($invokeParams.Method) {
  'Test' {
    $response.indesiredstate = $result.InDesiredState
    return ($response | ConvertTo-Json -Compress)
  }
  'Set' {
    $response.indesiredstate = $true
    $response.rebootrequired = $result.RebootRequired
    return ($response | ConvertTo-Json -Compress)
  }
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows 2016 Std, SQL Server 2016 Developers Edition, Powershell: 5.1.14393.693

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

tested with: 3.0.0.0 and 4.0.0.0 - both gave the same result,

**Comment by luigilink** [comment]
You set dynamicalloc = $true and minmemory/maxmemory are not null, It cannot work you have to choose dynamic or not.
I changed the code of Test-TargetResource (and Set-TargetResource), see the PR #343

**Comment by marcinbojko** [comment]
@luigilink 
I don't think so - i tried with a lots of settings.
For example:

```powershell
$invokeParams = @{
  Name          = 'xSQLServerMemory'
  Method        = 'test'
  Property      = @{
    dynamicalloc = $true
    #minmemory = 1024
    #maxmemory = 2048
    sqlserver = 'test-pusql'
    sqlinstancename = 'MSSQLSERVER'
  }
  Verbose=$true
```

and the effect is the same.

**Comment by luigilink** [comment]
@marcinbojko 
Could you test the code from PR #343  https://github.com/luigilink/xSQLServer/blob/01df106f1c253b20e00b87746f8cdc036299ebec/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1

**Comment by luigilink** [comment]
I tested with this configuration and it works great with the code of PR #343 

```
        xSQLServerMemory MIDDLEWARE_SqlMax8GB
        {
            Ensure = 'Present'
            DynamicAlloc = $false
            SQLServer = 'SP15DEV'
            SQLInstanceName = 'TEST'
            MinMemory = 2048
            MaxMemory = 8192
        }
```
Result of Test-DscConfiguration:

```
VERBOSE: [SPS15DEV]: LCM:  [ Start  Resource ]  [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB]
VERBOSE: [SPS15DEV]: LCM:  [ Start  Test     ]  [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB]
VERBOSE: [SPS15DEV]:                            [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB] Importing the module
MSFT_xSQLServerMemory in force mode.
VERBOSE: [SPS15DEV]:                            [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB] Testing the values of the
minimum and maximum memory server configuration option set to be used by the instance.
VERBOSE: [SPS15DEV]:                            [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB] 2017-02-17_15-39-48: Connected
 to SQL SPS15DEV\TEST
VERBOSE: [SPS15DEV]:                            [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB] Getting the value for minimum
and maximum SQL server memory.
VERBOSE: [SPS15DEV]: LCM:  [ End    Test     ]  [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB] True in 0.1400 seconds.
VERBOSE: [SPS15DEV]: LCM:  [ End    Resource ]  [[xSQLServerMemory]MIDDLEWARE_SqlMax8GB]
```

**Comment by marcinbojko** [comment]
@luigilink 
I have to wait for stable version to test it internally.

**Comment by johlju** [comment]
@marcinbojko Changes in PR #343 has been merged. Next release is planned for 03/08/2017. I labeled this in progress.
Please report back when you tested the new released version.

**Comment by marcinbojko** [comment]
Of course.

**Comment by johlju** [comment]
@marcinbojko Can you confirm that this issue is solved with the latest release of SqlServerDsc v.10?

**Comment by marcinbojko** [comment]
@johlju - Hi, I can confirm it works.I am able to set MEMORY as needed.

**Comment by johlju** [comment]
Closing this as solved.
