### ISSUE TITLE
SqlSetup: Can only install Analysis Services in the default (Multi-Dimensional Server Mode)

### ISSUE THREAD

**Issue by craigofnz** [PowerShell/SqlServerDsc#388]
**Unable to automate the installation of SSAS in TABULAR mode via Powershell DSC**

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
```
Windows 2016 Data Center: Version 1607 (OS Build 14393.729)
Powershell: 5.1.14393.693
```

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
5.0.0.0

**Notes:**
The command-line install has a parameter available for 
`/ASServerMode MULTIDIMENSIONAL|TABULAR|POWERPIVOT`

[See: MSDN](https://msdn.microsoft.com/en-us/library/hh231722.aspx)

This option does not appear to be available from the DSC Resource.

**Comment by johlju** [comment]
We need to add that support as soon as possible. If anyone feel they can take this on, then feel free. :)

**Comment by craigofnz** [comment]
Almost done

**Comment by johlju** [comment]
@craigofnz Awesome! Thank you! I label this one as in progress then. :smile:
