### ISSUE TITLE
SqlSetup: 'action' property should be key not write?

### ISSUE THREAD

**Issue by kewalaka** [PowerShell/SqlServerDsc#426]
You can not use the xSQLServerSetup, with the actions 'PrepareFailoverCluster' and 'CompleteFailoverCluster' in the same configuration files, as these are write properties in the schema, not key properties.

Testing on Azure Automation, you get the following error;

> A conflict was detected between resources '[xSQLServerSetup]PrepareMSSQLSERVER (::56::9::xSQLServerSetup)' and '[xSQLServerSetup]CompleteMSSQLSERVER (::161::13::xSQLServerSetup)' in node

>Resources have identical key properties but there are differences in the following non-key properties: 'Action'. Values 'PrepareFailoverCluster' don't match values 'CompleteFailoverCluster'. Please update these property values so that they are identical in both cases.

Tested using v5 on Windows 2016, checked and still present in dev branch.

xSQLServerFailoverClusterSetup works for now, but I note this is deprecated.

**Comment by johlju** [comment]
But isn't the whole purpose of prepare to do it in one configuration file, and the complete it in another configuration file? If you want to install a failover cluster in the same configuration file, why don't you use the action 'InstallFailoverCluster' instead?

**Comment by johlju** [comment]
I label this as a discussion for the time being.

**Comment by kewalaka** [comment]
@johlju Ah, good point.  Yes, 'installfailovercluster' makes more sense.  I was basing my approach on the examples, which separate these two activities, because xSQLServerFailoverSetup only supported prepare + complete.  I've got a specific scenario I'm testing on Azure Automation (S2D w/two node cluster), will report back if I hit any snags.

**Comment by johlju** [comment]
The examples should be updated, they are not up to date yet unfortunately. 

Please use the Dev version (will be release on the 8th) because there are fixes for cluster. And yes please, report any bugs you find :)

**Comment by johlju** [comment]
@kewalaka v6.0 was released yesterday. So please use that when you test 'InstallFailoverCluster'.  😄
