### ISSUE TITLE
SqlWindowsFirewall: Configuring FW rules for 2 DB engine instances fails

### ISSUE THREAD

**Issue by dhjensen** [PowerShell/SqlServerDsc#427]
**Details of the scenario you try and problem that is occurring:**
I try to configure DB engine firewall rules for 2 instances:
WEBQA
WEBPROD

In the code I pasted below you set the $ensure = 'Present' both for DB engine and SQL server browser.
Later in the code you only evalute on if $ensure = 'Present'
So no firewall rules are added if the SQL server browser FW rules is already there

**The DSC configuration that is using the resource (as detailed as possible):**
```
            xSqlServerFirewall ($instance.name) {
                DependsOn = ("[xSqlServerSetup]" + $instance.name), ("[xSQLServerNetwork]" + $instance.name)
                SourcePath = $Node.SourcePath
                InstanceName = $instance.name
                Features = $instance.Features
            }
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
SQL server 2016 
WMF 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
5.0.0.0

In this part of the code:
```
          'SQLENGINE'
            {
                if ($services | Where-Object {$_.Name -eq $databaseServiceName})
                {
                    $featuresInstalled += "$_,"

                    $pathToDatabaseEngineExecutable = Join-Path -Path (Get-SQLPath -Feature $_ -InstanceName $InstanceName) -ChildPath 'sqlservr.exe'
                    $databaseEngineFirewallRuleDisplayName = "SQL Server Database Engine instance $InstanceName"

                    $databaseEngineFirewallRuleParameters = @{
                        DisplayName = $databaseEngineFirewallRuleDisplayName
                        Program = $pathToDatabaseEngineExecutable
                        Enabled = 'True'
                        Profile = 'Any'
                        Direction = 'Inbound'
                    }

                    if (Test-IsFirewallRuleInDesiredState @databaseEngineFirewallRuleParameters)
                    {
                        $databaseEngineFirewall = $true
                        $ensure = 'Present'
                    }
                    else
                    {
                        $databaseEngineFirewall = $false
                    }

                    $browserFirewallRuleDisplayName = 'SQL Server Browser'

                    $browserFirewallRuleParameters = @{
                        DisplayName = $browserFirewallRuleDisplayName
                        Service = $browserServiceName
                        Enabled = 'True'
                        Profile = 'Any'
                        Direction = 'Inbound'
                    }

                    if (Test-IsFirewallRuleInDesiredState @browserFirewallRuleParameters)
                    {
                        $browserFirewall = $true
                        $ensure = 'Present'
                    }
                    else
                    {
                        $browserFirewall = $false
                    }
                }
            }
```

**Comment by johlju** [comment]
You are correct, when this [line](https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerFirewall/MSFT_xSQLServerFirewall.psm1#L131) evaluates to false it should set `$ensure = $false`. 

Now `$ensure = $false` is also set at the beginning of the Get-method, maybe it should always set `$ensure` to `$true` or `$false` depending on the evaluated result instead of assume it will be `$false` unless it can be set to `$true`.

**Comment by dhjensen** [comment]
Perhaps just change the order so browser is evaluated first? That would
also end up having the $ensure variable with the correct result in my
scenario?
However there might be other scenarios where the db engine  rule is present
and the browser is not...

**Comment by dhjensen** [comment]
Hi @johlju #479 fixed this issue so I think it can be closed.

**Comment by johlju** [comment]
@dhjensen awesome! Thanks for letting me know! 

Closing as per previous comment.
