### ISSUE TITLE
SqlServerDsc: Remove old examples in favor of new resource specific examples

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#462]
I suggest that we remove the below examples due to the fact that we can't keep up with changing these examples when other modules change. For example, I'm thinking that the steps for setting up LCM is well documented in docs.microsoft.com, and setting up a cluster must be documented in those modules that knows best how to do that with there resources. We might miss a step, or the resource change to behave in another way, or the user has a different environment or requirment, and then the examples won't work any way. 
Also the examples does not follow the template so that the common tests can test the examples. That can be fixed though.
I would rather point the user in our documentation (README.md or resource specific examples) to examples or/and documentation in other resources that would help setting up the prerequisites for using our resources.

I really want to here other views on this.

**Examples suggested to be removed:**
DSCClusterSqlBuild.ps1
DSCFCISqlBuild.ps1
DSCSqlBuild.ps1
DSCSQLBuildEncrypted.ps1
SQL-ClusterDB.ps1
SQL-Standalone.ps1
SQLPush_SingleServer.ps1

**Comment by johlju** [comment]
The examples here:
https://github.com/PowerShell/xSQLServer/tree/dev/Examples/Resources/xSQLServerSetup
I think they should replace examples here (remove these):

DSCFCISqlBuild
DSCSqlBuild
DSCSQLBuildEncrypted
SQL-ClusterDB
SQL-Standalone
SQLPush_SingleServer

And the examples here:
https://github.com/PowerShell/xSQLServer/tree/dev/Examples/Resources/xSQLServerAlwaysOnAvailabilityGroup
https://github.com/PowerShell/xSQLServer/tree/dev/Examples/Resources/xSQLServerAlwaysOnAvailabilityGroupReplica

I think they should replace this examples (remove these):
DSCClusterSqlBuild

**Comment by randomnote1** [comment]
Could we provide links in the documentation to the items that we're removing? I think it would be helpful for the beginner to have as much copy/paste material as possible.

**Comment by johlju** [comment]
Yes, you are right. Maybe we could add these as .md files instead under the Examples folder? Maybe write it up like a blog and link to various example throughout the DSC Resource Kit? It would then be easier for contributors to add (text) to that so we collect more knowledge into one place.

Then that might fix this one as well https://github.com/PowerShell/xSQLServer/issues/176
But it would be awesome if we could have that at docs.microsoft.com. Under PowerShell here maybe. https://docs.microsoft.com/sv-se/sql/sql-hub-menu?toc=%2fsql%2ftoc.json#pivot=sdkstools
Or maybe here https://github.com/PowerShell/PowerShell-Docs
I will try to remember to ask about this on the next community call.

**Comment by randomnote1** [comment]
Yup, I think you're spot on with the blog-style examples.

**Comment by johlju** [comment]
All the examples in the root of /Examples should be rewritten, because they reference resources that no longer exist or has been been updated with breaking changes. My thought was that I would have time to fix this during the month that went by. But other stuff needed to be done 
I'm looking at splitting these examples between xSQLServer and xFailOverCluster. Help is welcomed. :)

**Comment by johlju** [comment]
I think these examples should be implemented as configurations using the templates from the repository [DscConfigurations](https://github.com/PowerShell/DscConfigurations) instead. Then they are able to be integration tested by the users themselves with an already finished framework for production ready configurations. The configurations should be able to be linked to that DscConfigurations repository.

These exampled as they are today (linked in the issue description) is not production ready.

**Comment by johlju** [comment]
This will resolve issue #373 as well.
