### ISSUE TITLE
SqlServerDsc: Resources have Byte Order Mark (BOM) in .psm1 files

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#651]
**Details of the scenario you tried and the problem that is occurring:**
Resources have Byte Order Mark (BOM) in .psm1 files. These should be removed.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by cwegener** [comment]
I'd recommend to clarify BOM requirements in the File Encoding section of the Style Guide.
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-file-encoding

**Comment by johlju** [comment]
@cwegener Created issue https://github.com/PowerShell/DscResources/issues/285 and PR https://github.com/PowerShell/DscResources/pull/286.

**Comment by cwegener** [comment]
@johlju Sounds good. I think that's sufficient for clarification.

Next step would be to add an `.editorconfig` file into each DSC project to help contributors configure their editors.

**Comment by johlju** [comment]
Closing this one as this have been resolved and guidelines have been updated.
