### ISSUE TITLE
xSQLServer Fails when Azure DSC Extension attempt to unzip (Exceeds 260 chars Path/Filename)

### ISSUE THREAD

**Issue by willjr20** [PowerShell/SqlServerDsc#705]
**Attempting to configure SQL Server 2016 and setup Availability groups**

**Fail to unzip the DSC.zip file pull down from storage account blob, I am able to manually move the downloaded zip file to a less deep directory structure on Azure Virtual machine (C:\tmp) and unzip it without any issues, however when I attempt to manually unzip from the default Azure DSC extension folder (C:\Packages\Plugins\Microsoft.Powershell.DSC\<version>\DSCWork) it fails with path too long error.** 

**Version of the Azure VM Windows Server 2016, SQL Server 2016 and PowerShell 5.1**

**SqlServer version 8.0.0.0**

**Comment by johlju** [comment]
Ah. That was unfortunate. Does it work using it from any other folder than the default so you can work around this problem? 

The <version> how is that formatted? Do you have an example of the full (with version) `'C:\Packages\Plugins\Microsoft.Powershell.DSC<version>\DSCWork'` folder?

**Comment by johlju** [comment]
The longest path I can find is 230 chars. So there must be more folders that is is nested under the DSCWork folder?

This path is the longest 230 chars when _mocking_ the path you provided above.
```
C:\Packages\Plugins\Microsoft.Powershell.DSC<version>\DSCWork\xSQLServer\8.0.0.0\DSCResources\MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership\en-US\MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.strings.psd1
```

**Comment by willjr20** [comment]
That is correct. (nested folders under DSCWork folder) The actual full path is below;

C:\Packages\Plugins\Microsoft.Powershell.DSC\2.26.1.0\DSCWork

The entire issue is explained here in a MSDN post below; (I can paste this here, if that is the recommended approach)

https://social.msdn.microsoft.com/Forums/azure/en-US/b54d753d-90ed-49ad-af99-c24683974a1a/azure-dsc-extension-is-it-possible-to-change-pathdirectory-where-dscwork-is-created?forum=sqlgetstarted

It seems that the question was moved from the Azure Virtual machine forum to SQL Server, not sure why.

**Comment by willjr20** [comment]
It was not my intent to close this issue. 
 
The DSC zip file is downloaded to 
C:\Packages\Plugins\Microsoft.Powershell.DSC\2.26.1.0\DSCWork\prepare-sql-alwayson-server.ps1.zip

Next it is unzipped to
C:\Packages\Plugins\Microsoft.Powershell.DSC\2.26.1.0\DSCWork\prepare-sql-alwayson-server.ps1.0


Two files fail (greater than 260 chars) 
1.) MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.strings

C:\Packages\Plugins\Microsoft.Powershell.DSC\2.26.1.0\DSCWork\prepare-sql-alwayson-server.ps1.0\xSQLServer\8.0.0.0\DSCResources\MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership\en-US\MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.strings
2.) 4-RemoveConnectPremissionToAlwaysOnPrimaryAndSecondaryReplicaEachWithDifferentSqlServerAccounts.ps1

I counted the total length and it doesn't exceed 260 of item 1 and it's less than 260 chars.  It appears that Windows Explorer zip extraction function fails anyway.

Item 2 was in the examples and I removed it.

I have attached the zip file in question (contains no secrets)

**Comment by willjr20** [comment]
[prepare-sql-alwayson-server.ps2.zip](https://github.com/PowerShell/xSQLServer/files/1166283/prepare-sql-alwayson-server.ps2.zip)

DSC zip file

**Comment by willjr20** [comment]
As a work around, I reduced my zip filename to sqlag.ps1.zip.  However, further testing revealed that the maximum supported file name length including extension is (32 chars).

Filename = 123456789012345678901234.ps1.zip

**Comment by johlju** [comment]
You mean the is no file length problem when you kept the .zip filename (including extension) under 32 chars? 32 chars is a limitation of the unzip functionality, or the max number of chars the filename can be until you get the file length issue?

**Comment by willjr20** [comment]
32 Chars for the filename (including the extension).  
Additionally, installed WINRar and it extracted the DSC zip file without issue.  So the issue appears to be in Windows extract functionality as it gets close to the maximum path (including the filename and extension) limit.

**Comment by johlju** [comment]
We could change the name of the example filename, but I don't want to change the resource name. If there is a problem loading, and using, the resource when it's all zipped up, then we could raise the question to rename the resource(s). But if so, then we should also make common test to be used throughout the DSC Resource Kit making sure a resource name cannot be longer than a certain length. 

If he module can be loaded, and all resource can be used, when it is all zipped up, I think the problem lays in the unzip method.

Do you have a suggestion how to resolve this?

**Comment by willjr20** [comment]
I agree, the issue is in how unzip functions.  32 chars is sufficient for the DSC zip file name.  I don't see a solution short of fixing the unzip functionality.  Documentation indicating the users should shorten the DSC zip file name to 32 chars or less should they have an issue with unzipping by Azure DSC Extension should be good.

**Comment by johlju** [comment]
If we would have a longer resource name, or any other file, that would exceed 260 chars even when you shorten the zip file name (to let's say 'a.zip'). Would that be a problem? 

I'm curious, because I wonder if we need to make a unit test that check the length of the paths, so we don't exceed 260 chars.

**Comment by johlju** [comment]
@willjr20 If the problem still exist with the new SqlServerDsc v10.0.0.0 that was recently released to PowerShell Gallery then please reopen.
