### ISSUE TITLE
xSQLServerSetup doesnt show up when loading xSQLServer in Azure Automation

### ISSUE THREAD

**Issue by DdenBraver** [PowerShell/SqlServerDsc#713]
**Details of the scenario you tried and the problem that is occurring:**
Importing the module to Azure Automation fromthe PowerShell Gallery is succesfully, however not all DSC resources are imported. Only 26 out of 28 resources show up.
The same thing happends when I download the Module manually, zip it and upload it.

**The DSC configuration that is using the resource (as detailed as possible):**
the xSQLServerSetup and _xWaitForAvailabilityGroup resource do not populate on the Azure Automation account.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSqlServer 8.0.0.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
When attempting to upload manually, I used the dev branch.

**Comment by johlju** [comment]
Is this the same issue as issue #705?

**Comment by DdenBraver** [comment]
I am not entirely sure if this is related to a change in the xSQLServer resource, or a change in Azure Automation. It started happening after this weekend, and currently as it stands all older versions also have this issue.

I have just tested version 6.0.0.0 up to 7.1.0.0 and none of them seems to import the xSqlServerSetup resource.

**Comment by johlju** [comment]
If this worked for you with 8.0.0.0 (or older) before the weekend it doesn't sound like an issue with this module. Or, the way it is imported has changed (somekind of verification), and there a bug in those two resources that doesn't allow it to be imported. 

Does anyone else see the same problem?

**Comment by johlju** [comment]
@mbreakey3 or @kwirkykat this is very strange, do you know how the module is extracted in Azure Automation? Is something verified/evaluated during the "extracting activities" step that could explain the resources not to show up?

I have stripped everything except three resource (and essentials); xSQLServerScript, xSQLServerSetup and xWaitForAvailabilityGroup. Zipped and uploaded that stripped module manually to Azure Automation. Only xSQLServerScript shows up. For some reason the resources xSQLServerSetup and xWaitForAvailabilityGroup does not show.
I have tested SharePointDsc and xFailOverCluster. They both list all resources.

To all: Have someone used this module in Azure Automation that can say that it has worked at some point?

**Comment by shurick81** [comment]
I have noticed this behavior as well but then I created another Automation resource and all 28 resources were imported properly imported.

**Comment by johlju** [comment]
@shurick81 Hmm... That doesn't seem reliable. Created a a new Azure Automation resource and uploaded sam stripped version of the module, but only one was listed as in previous test. 😞

**Comment by DdenBraver** [comment]
@mgreenegit Is also looking at this issue:
https://twitter.com/migreene/status/890617502044114946

**Comment by shurick81** [comment]
@johlju, is this connected? https://github.com/PowerShell/xSQLServer/issues/716#issuecomment-323056385

**Comment by johlju** [comment]
No, it is not related, not directly anyway (see twitter conversation above with @mgreenegit) . A configuration using xSQLServerSetup (which does not show in the resource list) compiles correctly once a workaround from #716 has been applied.

**Comment by johlju** [comment]
I will keep this issue open to track this problem, but I will label this as on hold for the time being since we can't do anything in the module to resolve this.

**Comment by arcotek-ltd** [comment]
I'm having issues relating to DSC resources not showing up. In my case, it is a composite resource that calls xSQLServer resources.

After painstaking use of <# #> as soon as xSQLServerLogin is called, (which is the first xSQLServer resource) the composite resource goes missing.

I have already removed the (ridiculously named) `MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership` as it was causing headaches with VSTS  let alone Azure Automation.

I'm working on this issue as I write and made some progress. I've removed the Examples and Tests folder from xSQLServer and I have an instance of xSQLServerLogin which imports properly.
I have also updated all the public automation modules as they were rather old 1.0.x on some of them!

Commented in a second instance of xSQLServerLogin and FAIL.

It's now 04:50,, the sun is coming up, so to cut to the chase, I deleted a bunch more resources from xSQLServer with stupid file name lengths and my composite resource is now importing properly.

It doesn't explain why I got it to work with one call to xSQLServerLogin and no more...


It would help tremendously if MS would provide some logging on what is going on behind the scenes so we can see why a resource is not being imported. From looping `Get-AzureRmAutomationModule` every 3 seconds, it looks like MS are using a runbook:
```
VERBOSE: Provisioning state: Creating.
VERBOSE: Provisioning state: RunningImportModuleRunbook.
VERBOSE: Provisioning state: ConnectionTypeImported.
VERBOSE: Provisioning state: Succeeded.
```
Where is this runbook? Not in my AA.

Although Googling RunningImportModuleRunbook returns some interesting hits that may allow us to dig into what is happening: [ModuleProvisioningState Enum]( https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.automation.models.moduleprovisioningstate?view=azure-dotnet
)
`New-AzureRmAutomationModule` should not return `ProvisioningState : Succeeded` if it misses resources.

**Comment by arcotek-ltd** [comment]
As a post script, I tested the whole configuration in push mode on a test server, so having Azure throw a wobbly was most annoying to say the least.

**Comment by johlju** [comment]
@DdenBraver I talked with @mgreenegit at Ignite yesterday. They found the issue that causes this behavior. It had something to do with the Credentials parameters (if remembered correctly). There is currently no timeline when this gets resolved.  But this should not stop the module to be deployed to the target nodes. The entire module is there, it just not showing it, if i understood correctly.

@arcotek-ltd Please see issue #716.

**Comment by DdenBraver** [comment]
Thanks for the update @johlju. The biggest problem I currently have with this issue, is that since its not showing up I cannot let Azure Automation compile the configuration.
We have a temporary work-around where we compile the configurations locally to get this fixed, but this breaks some parts of our automation for DSC during server deployment.

**Comment by johlju** [comment]
@DdenBraver Could you please write about the problems you in issue #716, if it is relevant, so we track those issues in the same place?

**Comment by johlju** [comment]
@DdenBraver I mean about that parts that breaks the automation when you compile locally.

**Comment by DdenBraver** [comment]
@johlju Sorry, I may have typed that a bit unclear.
We have a setup that will use a runbook to compile the dsc resources on the fly for a server after a server was deployed in Azure. This runbook will initiate a compile of the DSC configuration in Azure Automation, which currently does not work, as described in #716.

Hence "our" automation breaks. The current work around is that we manually compile the configuration locally, and upload it to Azure automation. Doing this it will work, but this requires manual intervention.

**Comment by dead8171** [comment]
Am Facing the same issue, please tell me how can I compile a .mof file and install that onto the server, I heard that DSC extension needs to be installed onto the machine but tell me how can I generate the mof file, as I have the script that installs the sql server setup, but havent tested that yet.

**Comment by DdenBraver** [comment]
@dead8171 You would have to compile the dsc configuration locally.
Documentation for this can be found here: https://docs.microsoft.com/en-us/powershell/dsc/configurations

After you have the compiled 'configuration' and have a 'nodename.mof' file, you can upload them to Azure Automation by doing the following:
- go to your Azure Automation Account
- Select 'DSC Node Configurations' under 'Configuration Management'
- Select 'Add a Node Configuration' (+ at the top) and upload your 'nodename.mof'

You can now select this configuration for your DSC Nodes in Azure Automation, or specify it during deployment in your ARM Template using the DSC Extension.

**Comment by mgreenegit** [comment]
Just to chime in, I have definitely been tracking this issue and I think I have it narrowed down to a very specific repro for the service.  The local compile is the right short term answer (and I realize it is not ideal).  I will continue to track it until this has been corrected and I hope to use this thread to validate when it is resolved, if you don't mind.  Thank you for your patience.  cc @OaaSTeam

**Comment by dead8171** [comment]
@DdenBraver How can I configure the $credebtial part locally, since I was using the automation account credentials while configuring this from the powershell, but how to resolve this while configuring this locally???

**Comment by jonathaneckman** [comment]
+1 Just ran into this.

**Comment by johlju** [comment]
We hopefully just merged a fix in PR #902. That pull request has done a massive rename of all resources . Big thanks to @mgreenegit for doing the awesome work.
The resource module has been renamed to SqlServerDsc.  Since we are doing such a major breaking change we will make som other adjustments to parameter names as well.  So until that PR is merged we must wait to release the new module. But if you want to test it out you can download the Dev version and upload it manually. Please be aware that, as I said, another PR will rename some parameters.

**Comment by mgreenegit** [comment]
Version 9+ of SqlServerDsc resolve this issue. While you will not see SqlSetup listed in the extracted activities for the module (yet), configurations that use the resource will now compile successfully. I believe we can mark the issue as resolved?

**Comment by jonathaneckman** [comment]
I imported version 9.0.0.0 and still see errors during compilation:

Exception calling "NewScriptBlock" with "1" argument(s): "At line:206 char:9
 + xSqlServerSetup ConfigureSqlServer
 + ~~~~~~~~~~~~~~~ Undefined DSC resource 'xSqlServerSetup'. Use Import-DSCResource to import the resource.
 
 At line:223 char:3
 + xSQLServerLogin ConfigureSharePointSetupAccountSqlLogin
 + ~~~~~~~~~~~~~~~ Undefined DSC resource 'xSQLServerLogin'. Use Import-DSCResource to import the resource." (At line:206 char:9
 + xSqlServerSetup ConfigureSqlServer
 + ~~~~~~~~~~~~~~~ Undefined DSC resource 'xSqlServerSetup'. Use Import-DSCResource to import the resource.
 
 At line:223 char:3
 + xSQLServerLogin ConfigureSharePointSetupAccountSqlLogin
 + ~~~~~~~~~~~~~~~ Undefined DSC resource 'xSQLServerLogin'. Use Import-DSCResource to import the resource.)

**Comment by johlju** [comment]
It should have said version 10 which has not been released just yet. It will be released as SqlServerDsc. You can find it in the dev version here, which you can manually upload. 
Please note that resources has been renamed, see change log.
