### ISSUE TITLE
SqlScript: Store queries in configuration properties

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/SqlServerDsc#719]
**Details of the scenario you tried and the problem that is occurring:**
I believe xSQLServerScript should behave in a manner consistent with the [DSC Script resource](https://docs.microsoft.com/en-us/powershell/dsc/scriptResource) where the contents of the Get/Set/Test scripts are stored in the configuration, not in an external file. I do see the value in being able to execute the Get/Set/Test from external SQL files, so I believe that functionality should be retained.

I propose the following properties be added to the resource:
- GetScript
- SetScript
- TestScript

This will be consistent with the DSC Script resource. The logic of the resource should be updated to allow any combination of the Get*, Set*, and Test* properties (eg. GetScript, TestScript, SetFilePath), but throw an error if both Get*, Set*, or Test* properties are set. This would be easiest with parameter sets, however that functionality is not available yet.

**The DSC configuration that is using the resource (as detailed as possible):**
```
Configuration ExampleSqlScript
{
    param
    (
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $WindowsCredential,

        [Parameter(Mandatory = $false)]
        [System.String]
        $SaName = 'RenamedSa'
    )
    
    xSQLServerScript 'ChangeSaName'
    {
        ServerInstance = 'localhost\SQL2016'
        GetScript = 'SELECT Name FROM sys.server_principals WHERE principal_id = 1'
        SetScript = "
            DECLARE @saName sysname
            DECLARE @alterUser varchar(max)

            SELECT @saName = Name
            FROM sys.server_principals
            WHERE principal_id = 1

            SET @alterUser = 'ALTER LOGIN [' + @saName + '] WITH Name = [$SaName]'

            EXEC sp_executesql @alterUser
        "
        TestScript = "
            SELECT
                CASE
                    WHEN Name = '$SaName' THEN 1 
                    ELSE 0 
                END 
            FROM sys.server_principals
            WHERE principal_id = 1
        "
        PsDscRunAsCredential = $WindowsCredential
    }
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
N/A

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
v8.0.0.0/dev

**Comment by johlju** [comment]
@randomnote1 This looks good to me. But I think it should be possible to use, for example, GetScript and SetFilePath at the same time. But it should throw an error if both Get*, Test* or Set* parameters are set.

**Comment by randomnote1** [comment]
Yes, I was thinking the same thing. I updated the suggestion to reflect this.
