### ISSUE TITLE
SqlServerEndpoint: Integration test is missing for this resource

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#744]
**Details of the scenario you tried and the problem that is occurring:**
We should add an integration test for this resource.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by mdaniou** [comment]
@johlju I try to make that happen. ;)

Would you have a bit of code to allow me to test the integration test files created before merging anything ?
It would save me some time ...

**Comment by johlju** [comment]
You could run `Invoke-Pester <testfile>`and point out the integration test to run. 
But I usually use AppVeyor for this,  it my own AppVeyor account. I have added my _fork_ of SqlServerDsc as a project to my AppVeyor (free) account. 
Then I start of removing all unnecessary resources, examples, unit tests and integration tests (only save the essential that is needed for the new tests). Then I commit that to the branch as ‘debug-removal’. That way I speed up the testing in AppVeyor. 
Then I write the new tests and each push will run the test in AppVeyor on my own AppVeyor account (your personal account). 
When I’m ready and want to send in a PR, the first thing I do before that is to remove the commit “debug-removal” by running interactive rebase ‘git rebase -i my/dev’ (where my is the remote name to my fork). I will get en editor (vi) where I can say ‘drop’ the commit. Then the rebase will skip that commit and the branch is back to the original + the new tests, which I force push, and I can send in a PR of that branch. 

I like to do it that way. But if you have a lab server that you can run the integration test on you can start it manually. But I think it’s easier to know that the tests will work together with the other tests, since we need to run tests against the instance name that are installed as part of the integration tests. You could of course run those integration tests first, before the new ones you create. :)

I hope it helped answer your question, if not, please ask away again :)

**Comment by mdaniou** [comment]
Thanks for this.
I think I'm good now.
