### ISSUE TITLE
SqlSetup: fails if there are spaces in SourcePath

### ISSUE THREAD

**Issue by achern** [PowerShell/SqlServerDsc#779]
I suspect the offending line is here where the robocopy argument list is constructed without quotes:

https://github.com/PowerShell/xSQLServer/blob/4734f6657ce8ad90b0d216a7cbc7ca8325dc8bba/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L1889

Somehow in my case this actually caused xSQLServerSetup to confusingly report that robocopy determined that all the files were already present.

**Comment by johlju** [comment]
Thanks for reporting this!
