### ISSUE TITLE
SqlSetup: When running InstallFailoverCluster with BrowserSvcStartupType installation will fail

### ISSUE THREAD

**Issue by ld0614** [PowerShell/SqlServerDsc#811]
**Details of the scenario you tried and the problem that is occurring:**
When running a cluster installation (InstallFailoverCluster) with the BrowserSvcStartupType set the installation will fail with the following message in summary.txt:
The setting 'BROWSERSVCSTARTUPTYPE' is not allowed when the value of setting 'ACTION' is 'InstallFailoverCluster'.

While it would be simple in most circumstances to simply remove the setting I am writing a config which can be either a standalone node or cluster and want to minimize duplication.  I believe that it would be more intuitive to simply ignore the value during the set command

I had a quick look at a fix: in MSFT_xSQLServerSetup.psm1 line 1160
```
    if ($null -ne $BrowserSvcStartupType)
    {
            $argumentVars += 'BrowserSvcStartupType'
    }
```
To:
```
    if ($null -ne $BrowserSvcStartupType)
    {
        if ($Action -in @('Install','InstallFailoverCluster','PrepareFailoverCluster','CompleteFailoverCluster'))
        {
            Write-Verbose "BrowserSVCStartupType Ignored as unsupported by SQL Installer"
        }
        else
        {
            $argumentVars += 'BrowserSvcStartupType'
        }
    }
```

I'm happy to create a PR if people are happy with the change

**The DSC configuration that is using the resource (as detailed as possible):**
```
xSQLServerSetup "InstallSQLServer"
{
Action = "InstallFailoverCluster"
InstanceName = $Node.SQLServerInstanceName
Features = "SQLENGINE"

FailoverClusterNetworkName = $Node.SQLServerClusterNetworkName
FailoverClusterIPAddress = $Node.SQLServerClusterIPAddress

BrowserSvcStartupType = "Automatic"

#DSCConfig
DependsOn = $FeatureResources
PsDscRunAsCredential = $Node.InstallCredential
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016
WMF 5.1
SQL 2016

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSQLServer
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
DEV

**Comment by johlju** [comment]
Thanks for submitting this issue!

I would like opinions from the community on this one. 

If we do this change, then we need to do all other variations as well. This would create a lot of logic for all kind of different setting options that are not permitted in all kind of different scenarios. That would become a lot of logic code and test code. If there would be logic for this, I would want to throw an error saying to the user that the configuration is not correct, not just skipping the problem.
But thinking about it I rather just add to the parameter description, in the README.md, that the parameter is not allowed when installing a failover cluster.

Lets hear what the community thinks before deciding.

**Comment by ld0614** [comment]
Looking at the code itself it looks like the majority of the fields already have the conditional inclusion which I describe.  A good example is the cluster network name [here](https://github.com/PowerShell/xSQLServer/blob/1e6c8405a568e1ac46ca43f93f3574b8ef89efa4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L964) or the inclusion of analysis services [here](https://github.com/PowerShell/xSQLServer/blob/1e6c8405a568e1ac46ca43f93f3574b8ef89efa4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L1236).

While I'm happy to defer to the wider community the inability to splat parameters into DSC resources would cause a massive code bloat for me as a resource would be required for each combination of feature and cluster type.  IMO this dynamic use of parameters is one of the strongest features of the entire Resource Pack.

**Comment by johlju** [comment]
When looking at this again I think those parameters that are ignored in the resource today is the wrong practice. I think if a property is assigned a value in a configuration it should be uphold. If it can't an error should be thrown. As it is now a configuration can have values that are just ignored and it looks like the configuration is set when it is not. 
I think a configuration should not contain properties that can't be set. I think the resource should throw an error message saying that the configuration can never be in desired state.

**Comment by ld0614** [comment]
The issue is that if you specify the value in the installer as automatic the installer will fail even though the installer actually configures it as automatic.  How about checking for the value and if set to automatic the parameter is dropped to allow it though and if it isn't then throw an invalid argument exception?

**Comment by johlju** [comment]
I think since the property is not an acceptable argument with that action (see [Integrated Install Failover Cluster Parameters](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-2017#integrated-install-failover-cluster-parameters)) I don't think we should add code that allows it to be passed. I rather is throws if the parameter is used when `/ACTION` is 'InstallFailoverCluster'.
