### ISSUE TITLE
SqlServerEndpointPermission: What permissions are needed, logon local right required?

### ISSUE THREAD

**Issue by gdbarron** [PowerShell/SqlServerDsc#841]
**Details of the scenario you tried and the problem that is occurring:**
I'm trying to permission an endpoint created with the resource and trying to understand what permissions are needed to make this happen.  If for PsDscRunAsCredential I use a domain account with local admin and sa rights this works.  If I use a **service account** which has those same rights, but is not allowed to logon locally to the server, I receive the following error:

> Logon failure: the user has not been granted the requested logon type at this computer

If I grant NT AUTHORITY\SYSTEM sa rights and do not provide a value for PsDscRunAsCredential, this works as well.  What permissions are needed to run this?  Is there a way to provide a sql login for this resource?

**The DSC configuration that is using the resource (as detailed as possible):**
```
xSQLServerEndpointPermission AddSqlServiceAccountEndpointPermissions {
            DependsOn    = '[xSQLServerEndpoint]' + $Node.NodeName
            Ensure       = 'Present'
            Name         = 'Hadr_endpoint'
            NodeName     = $Node.NodeName
            InstanceName = $Node.SqlInstanceName
            Principal    = $Node.InstallerServiceAccount.Username
            Permission   = 'CONNECT'
        }

```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows/SQL Server 2016

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
How do I find out exactly what module being used?

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
8.1.0.0

**Comment by johlju** [comment]
The service account needs to have permission in the Database Engine, on the endpoint, to be able to set permission. What permission does the service account have in the Database Engine?

**Comment by gdbarron** [comment]
Thanks for your reply and apologize for the delay.  I have provided sa rights in order to test, but the issue is not with permissions and is with how the run as credential functionality works.  The account provided requires the log on locally right and that's an issue with service accounts that purposefully have it blocked.  Looks like the way around is to grant that account the right it needs or grant the machine accounts, _Domain_ \ _ComputerName_$, access for all nodes.  I have chosen the latter and that is working well.

**Comment by johlju** [comment]
Okay, so what I understand is that you can't run the resource using `PsDscRunAsCredential = $SqlAdministratorCredential`, because the credential you provide in `$SqlAdministratorCredential` need local logon (user) permission and that is not allowed in your environment? 

Not sure we can do anything about it in this resource. So glad you solved it.

Closing this as solved. Please reopen if there are further questions or if there is as a bug or enhancement to be made here.
