### ISSUE TITLE
BREAKING CHANGE: SqlDatabaseRole: Should only handle database roles and not create database users

### ISSUE THREAD

**Issue by bozho** [PowerShell/SqlServerDsc#847]
xSQLServerDatabaseRole resource currently creates a DB user for an SQL login and assigns already existing roles to the user.

The related issue (#846) proposes renaming the resource to xSQLServerDatabaseUser.

We should then implement a new resource xSQLServerDatabaseRole, used to handle DB roles.

**Comment by johlju** [comment]
I changed the title on this issue to better reflect the change that should be done. Correct me if I'm wrong.
Also see issue #846.

I suggest we change this resource to use the same/similar schema.mof as xSQLServerRole.

**Comment by johlju** [comment]
@bozho Could you propose a schema.mof for this as well?
