### ISSUE TITLE
SqlRSSetup: New resource

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#865]
**Details of the scenario you tried and the problem that is occurring:**
In SQL Server 2017 Reporting Services are no longer a part of SQL Server, but a separate install [Microsoft SQL Server 2017 Reporting Services](https://www.microsoft.com/download/details.aspx?id=55252).

To be able to install this I think we should add a new resource that can correctly install this component. The other option is to extend xSQLServerSetup to be able to install this as well.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Microsoft SQL Server 2017 Reporting Services

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by randomnote1** [comment]
I think xSQLServerSetup should continue to only focus on the capabilities provided by setup.exe in the SQL Server installation media. Since SSRS has be split out into its own installer, I believe it should have its own resource.

**Comment by johlju** [comment]
I agree with @randomnote1.

**Comment by codykonior** [comment]
If you do a new SSRS 2017 resource please scope it to include its new cousin Power BI Reporting Services. It's the same code base and licensed with SQL Server Software Assurance. It's also a separate download, and the installer is basically exactly the same.

**Comment by yamezui** [comment]
I agree, SSRS 2017 should be considered together with PowerBI Report Server

**Comment by maroliict** [comment]
When is such a resource availlable?

**Comment by johlju** [comment]
@maroliict There are no one in the community working on this yet, as far as I know.

**Comment by johlju** [comment]
Working on this one. Does anyone know how to detect what editon of Reporting Services is installed? 
If I know that I can make `/EditionUpgrade` work.

**Comment by johlju** [comment]
This is being proposed in PR #1308, but I opened issue #1309 to track @codykonior suggestion. My first thought was to fix a resource for that in PR #1308, but it grow so big (lot of side issues detected) so I hold off on that.
