### ISSUE TITLE
SqlServerDsc: mixing xSQLServer resources with custom SQL Server resources

### ISSUE THREAD

**Issue by bozho** [PowerShell/SqlServerDsc#893]
I'm working on a set of partial configurations for configuring our Windows servers. One of the partial configurations is used to configure SQL Server (including SSRS and SSAS). It is a mix of xSQLServer resources and a few custom class-based DSC resources used to configure a few SQL things specific to our needs.

All this currently runs on Windows 2012 R2 server and SQL Server 2014 (so using SQLPS module), with PS 5.1.

The partial configuration runs fine when using xSQLServer 8.1.0.0. However, when I run it using 8.2.0.0, I get an error. The event log shows these entries (SQLServerProperties is one of our custom resources):

```
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x6. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [SQLServerProperties]SQLServerProps and Source Info is ::167::3::SQLServerProperties. Error Message is The Symplectic.Dsc.Resources PowerShell DSC resource is not a valid Desired State Configuration resource.
```

```
Job {BFFBB1A3-B80F-11E7-80C9-3E1DBB675B2A} : 
MIResult: 1
Error Message: The Symplectic.Dsc.Resources PowerShell DSC resource is not a valid Desired State Configuration resource.
Message ID: ProviderNotFound
Error Category: 7
Error Code: 6
Error Type: MI
```

If I comment out all of our custom resources, or comment out all of the xSQLServer's resources in the configuration, it runs fine on 8.2.0.0.

From xSQLServer's changelog, I can see that there were changes in SQL Server module and Microsoft.SqlServer.Smo loading. I'm guessing this is the cause of the problem, but I have no idea where to start debugging (and the error messages are not helpful at all :-)

Does anyone have an idea how to get to the bottom of this?

**Comment by bozho** [comment]
Update: This issue does not seem to be linked to module and SMO assembly loading.

I've trimmed down one of our custom class resources to bare methods and still experience the same problem.

I've cleaned out all configuration on the target node. The test partial configuration is this (SQLServerProperties being our bare-bones custom resource):

```
configuration Symplectic_SqlServer {
    Import-DscResource -ModuleName SQLServerProperties
    Import-DscResource -ModuleName xSQLServer

    Node $AllNodes.NodeName {
        xSQLServerLogin Disable_Sa {
            SQLServer = "localhost"
            SQLInstanceName = "MSSQLSERVER"
            Name = "sa"
            Ensure = "Present"
            LoginType = "SqlLogin"
            Disabled = $true
        }

        SQLServerProperties SQLServerProps {
            SQLInstanceName = "MSSQLSERVER"
        }
    }
}
```

This configuration works with 8.1.0.0, but fails with the error from the original post when using 8.2.0.0

When I create a bare-bones MOF-based custom resource, everything works as expected on both 8.1 and 8.2.

Here's the bare-bones class-based resource: [SQLServerProperties.zip](https://github.com/PowerShell/xSQLServer/files/1411204/SQLServerProperties.zip)

**Comment by johlju** [comment]
I have not tested this. But here's my thoughts. 

Don't really know whats going on. if you get this with a bare bones DSC Class-based resource, it must have something to do with that a class-based resource is involved. Does it load something (even as barebone) that makes things go wrong?
Don't know what could have changed between version that would make your configuration failed. Only thing I can think of is how the SMO assembly is loaded.
But since you only using one version of SQL Server (2014) it should not be SMO related. But just to clarify, the resource xSQLServerLogin do import the SMO differently in 8.2.0.0. The resource xSQLServerLogin calls the helper function `Connect-SQL` which in turn runs the helper function `Import-SQLPS` so that the correct SMO library is imported. If there are another SMO library imported then that will fail to import the correct version. For example if you custom resource is used first and loads another version of the SMO library (for example with LoadWithPartial() method). 

See issue #649. I ran this to see if more than one SMO library is used. 
```
[System.AppDomain]::CurrentDomain.GetAssemblies() | ? Location -like *SqlServer*
```

**Comment by bozho** [comment]
I've played with this a bit more, but to answer your questions first:

The custom bare-bones resource doesn't load any SMO-related assemblies. If I remove `xSQLServerLogin` from the configuration, it runs fine with 8.2.0.0 installed and if I add your code to the Test() method of the custom resource, there are no SMO assemblies loaded.

If I put `xSQLServerLogin` resource back into the configuration, it looks like the Test() method of my resource doesn't even run on 8.2.0.0 (there's no verbose output from it of any kind), even though DSC's verbose output makes it look like the Test() method has run before throwing the error.

If I reverse the order of resources in the configuration, it runs fine on 8.2.0.0 and the `GetAssemblies` output shows a dozen or so SQL server/SMO assemblies loaded.

Running the same thing on 8.1.0.0 shows only about 5-6 SMO-related assemblies. The configuration runs fine on 8.1.0.0 regardless of resource order in the configuration.

If I replace `LoadWithPartialName` call in `Connect-SQL` with `Import-SQLPSModule` call in 8.1.0.0, the configuration still works regardless of resource order, but `GetAssemblies` shows the same output as in 8.2.0.0, making me think that SMO loading is a red herring here :-)

Next, I'll try moving 8.2.0.0 code into my 8.1.0.0 installation and try to find a change that's causing this problem...

**Comment by bozho** [comment]
Ah... I found the problem. It's.... (dun-dun-duuuuunnn):

`$env:PSModulePath = [System.Environment]::GetEnvironmentVariable('PSModulePath', 'Machine')`

in `Import-SQLPSModule`.

It would seem that system-level PSModulePath on Windows Server 2012 R2 (with WMF 5.1 installed) only contains `C:\Windows\system32\WindowsPowerShell\v1.0\Modules\` (and `C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\` after installing SQL Server 2014).

`$env:PSModulePath` does include `C:\Program Files\WindowsPowerShell\Modules`, which is set by PS on startup, I assume. So, it would seem that resetting `$env:PSModulePath` with the system-wide PSModulePath effectively removes `C:\Program Files\WindowsPowerShell\Modules`, which I'm guessing breaks support for class-based resources (or even PS classes in general).

Would a proper fix here be to compare $env:PSModulePath and system-wide PSModulePath and only add paths that are missing?

**Comment by johlju** [comment]
Oh, my bad! This issue might break a a lot of people! 😞 Thank you for finding the problem! 👍 😃 

Yes it sounds like that would be the proper fix to get the path for SQLPS into the `$env:PSModulePath`. Labeling this as a bug!

Do you want to send in a PR for this? No worries if you don't have time, labeling this as 'help wanted' for the time being.

**Comment by bozho** [comment]
I probably won't have the time before next week, but I can give it a go then.

It would be tempting to fix this by simply appending `Machine` and `User` PSModulePaths, but it looks like PS adds more than that to `$env:PSModulePath`, as SYSTEM user's `User` PSModulePath is empty.

**Comment by johlju** [comment]
I think this was resolved a while ago.

https://github.com/PowerShell/SqlServerDsc/blob/4f9abeaf71b1d988df2be95c7bcd9bd27051720e/SqlServerDscHelper.psm1#L738
