### ISSUE TITLE
SqlServerDsc: Naming convention must be explained

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#909]
**Details of the scenario you tried and the problem that is occurring:**
When repository is renamed to SqlServerDsc and PR #902 is merged then 'Naming convention' section must be updated in CONTRIBUTING.md (based on issue #851).

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by randomnote1** [comment]
@johlju, I can take this one since I put together the issue.
