### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: Parameter "DatabaseName" should be case insensitive

### ISSUE THREAD

**Issue by nabrond** [PowerShell/SqlServerDsc#912]
**Details of the scenario you tried and the problem that is occurring:**
The property `DatabaseName` should not use a case-sensitive test to determine whether a database name matches the specified value or pattern.

**The DSC configuration that is using the resource (as detailed as possible):**
````powershell
Configuration SampleConfig 
{
    Import-DscResource -ModuleName xSQLServer -Name xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership

    Node localhost 
    {
        xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership 'TestAG-Database-Members'
        {
            AvailabilityGroupName = 'TestAG'
            BackupPath = 'C:\SQL\Backup'
            DatabaseName = 'MyDB'
            SQLInstanceName = 'MSSQLSERVER'
            SQLServer = 'localhost'
            Ensure = 'Present'
        }
    }
}
````
This configuration should match any combination of case for the name "MyDB". However, only database matching the exact case are considered.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Operating System:  Windows Server 2012 R2
PowerShell Version:  5.0

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
SQLPS (130)

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
8.2.0.0

**Comment by randomnote1** [comment]
Working this one.
