### ISSUE TITLE
SqlAGReplica: Rename parameters PrimaryReplicaSQLServer and PrimaryReplicaSQLInstanceName

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#922]
**Details of the scenario you tried and the problem that is occurring:**
The work renaming parameters in issue #308 does not mention the parameters 
`PrimaryReplicaSQLServer` and `PrimaryReplicaSQLInstanceName` in the resource SqlAGReplica.

https://github.com/PowerShell/SqlServerDsc/blob/9a1080c4da5d513eb4191388206cf37c16c0a0fd/DSCResources/MSFT_SqlAGReplica/MSFT_SqlAGReplica.schema.mof#L8-L9

I suggest we rename them to `PrimaryReplicaServerName` and `PrimaryReplicaInstanceName` respectively.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
@nabrond  @randomnote1 What do you think?

**Comment by randomnote1** [comment]
Yes, I agree these should be updated for consistency.

**Comment by johlju** [comment]
Working on this.
