### ISSUE TITLE
SqlRS: Rename parameters RSSQLServer and RSSQLInstanceName

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#923]
**Details of the scenario you tried and the problem that is occurring:**
The work renaming parameters in issue #308 does not mention the parameters 
`RSSQLServer` and `RSSQLInstanceName` in the resource SqlRS.

https://github.com/PowerShell/SqlServerDsc/blob/9a1080c4da5d513eb4191388206cf37c16c0a0fd/DSCResources/MSFT_SqlRS/MSFT_SqlRS.schema.mof#L5-L6

I suggest we rename them to `DatabaseServerName` and `DatabaseInstanceName` respectively.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
@nabrond @randomnote1 another one, what do you think?

**Comment by randomnote1** [comment]
Yes, I agree these should be updated for consistency.

**Comment by nabrond** [comment]
Concur.

**Comment by johlju** [comment]
Working on this.
