### ISSUE TITLE
SqlAG & SqlAGReplica: Remove parameter SQLServerNetName

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#924]
**Details of the scenario you tried and the problem that is occurring:**
The work renaming parameters in issue #308 does not mention the parameter 
`SQLServerNetName` in the resource SqlAG.

https://github.com/PowerShell/SqlServerDsc/blob/9a1080c4da5d513eb4191388206cf37c16c0a0fd/DSCResources/MSFT_SqlAG/MSFT_SqlAG.schema.mof#L23

I suggest we rename it to `NetName`.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
@randomnote1 @nabrond next one, what do you think?

**Comment by johlju** [comment]
I'm open for other names. Maybe `NetServerName` would be more appropriate?

**Comment by randomnote1** [comment]
NetName is the property off of the server object that is used. This is either the node name or the virtual computer object name of the FCI. `ServerNetName` would make sense to me.

**Comment by johlju** [comment]
`ServerNetName` works for me.

**Comment by nabrond** [comment]
Should we drop the parameter all together? It looks like it is only used in the Get and Test functions. Seems odd to have a parameter that cannot be set be part of the evaluation for a resource's compliance.

**Comment by johlju** [comment]
In the Get-TargetResource function we could also return the value of the `EndpointHostName` if the parameter is set. If it is not set then we return `$serverObject.NetName` (the above code).

**Comment by randomnote1** [comment]
Well, I'm not entirely sure why I chose to create a read-only property for `$serverObject.NetName`. I'm in favor of using `$EndpointHostName` and dropping `$SQLServerNetName`.

**Comment by johlju** [comment]
@randomnote1 The same logic seem to exist in SqlAgReplica as well. So changing that as well. 

Working on this now.

**Comment by randomnote1** [comment]
That makes sense. Thanks!
