### ISSUE TITLE
SqlServerDsc: Add a description to this repository

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#941]
**Details of the scenario you tried and the problem that is occurring:**
The [recommended community standards](https://github.com/PowerShell/SqlServerDsc/community) suggest that we should add a description to this repository.

I suggest we add the same information as in the README.md slightly modified; "**This module contains DSC resources for deployment and configuration of SQL Server.**"

**Comment by johlju** [comment]
@kwirkykat can you help me with this? I don't have access to this setting.

**Comment by kwirkykat** [comment]
@johlju Done. Let me know if you ever want it changed/updated.

**Comment by johlju** [comment]
@kwirkykat Awesome! Thank you, will do.
