### ISSUE TITLE
SqlServerDsc: Release to PowerShell Gallery

### ISSUE THREAD

**Issue by johlju** [PowerShell/SqlServerDsc#943]
We should release SqlServerDsc to PowerShell Gallery. 

These are the steps to do in order listed.

- [x] [High priority issues](https://github.com/PowerShell/SqlServerDsc/issues?q=is%3Aopen+is%3Aissue+label%3A%22high+priority%22) should be resolved and merged.
- [x] Release the first version of **SqlServerDsc** to PowerShell Gallery.
- [x] Update **xSQLServer** on PowerShell Gallery saying that it is deprecated and point to SqlServerDsc.

**Comment by mohamednazar** [comment]
@Johlju,

still we can use xSQLServer ?

Regards,
Mohamed Nazar

**Comment by johlju** [comment]
@mohamednazar Yes, it will not be removed from PS Gallery, but there will be no more updates for that module any longer. Going forward, all changes will be in the SqlServerDsc resource module in PS Gallery.

**Comment by johlju** [comment]
@kwirkykat when you have time, can I get your help with releasing SqlServerDsc to PowerShell Gallery? This is so we can get a new version out there that can compile configurations in Azure Automation. This would be an out-of-band release just to fix that problem.  

See the issue description for the steps I see needs to be done. I need help with step 2 and 3. Let me know if I can help in any way.

/cc @mgreenegit

**Comment by johlju** [comment]
@kwirkykat Can you let me know when you have released the minor release to xSQLServer, deprecating it. Or just close this issue when you are done.

**Comment by johlju** [comment]
@kwirkykat I think that CodeCov doesn't work - probably since we rename the resource. PR #969 doesn't get a CodeCov comment, and looking at an older PR which I just pushed commits to doesn't change [it's commen](https://github.com/PowerShell/SqlServerDsc/pull/145#issuecomment-310292798). Looking at the [Diff at CodeCov](https://codecov.io/gh/PowerShell/SqlServerDsc/pull/145/diff) for that PR says it doesn't track files.
Can you look at it please? 😄

**Comment by kwirkykat** [comment]
@johlju Is this still a problem? I see CodeCov on the more recent PRs. Is it incorrect? Or it just didn't update on older PRs?

**Comment by johlju** [comment]
@kwirkykat Yes it started behaving again a while back, I thought you fixed something. 😄 Maybe there was a problem with CodeCov before. I keep an eye out a let you know if i behaves strangely again. 

On an other note, have you been able to add a note to xSQLServer so we can close this issue? If not, can I do something to help you?

**Comment by kwirkykat** [comment]
@johlju Note has been added to xSQLServer and updated the project site to point to SqlServerDsc https://www.powershellgallery.com/packages/xSQLServer/9.1.0.0

**Comment by johlju** [comment]
@kwirkykat Thank you, the change is looking good! 😄  Closing this issue.

**Comment by mohamednazar** [comment]
Hi 

Is it still safe to use xSQLServer DSCResource?

Regards,
Mohamed Nazar

**Comment by johlju** [comment]
@mohamednazar You can use it if it works for your scenario, but there will be no bug fixes or enhancements to xSQLServer. All bug fixes and enhancements will only be released under SqlServerDsc. SqlServerDsc will quickly move further away from xSQLServer.
Going forward any bug reports with xSQLServer must be able to be reproduced with SqlServerDsc.
