### ISSUE TITLE
sqlServerDSC: Need help with examples on SQL Configuration

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#946]
sqlServerDSC: After I install SQL Server on target VM, I would like to configure SQL with below steps.

1) Ensure SQL Server Agent startup type to Automatic
2) Add few accounts to sysadminrole
3)Set data directories to different directory e.g. d:\
4) Verify certain account exists in security \logs ins. If it does not exist , add them to security log ins.

Appreciate your advise and guidance to achieve my target.

**Comment by rsganta** [comment]
I have seen some examples in sqlserverdsc module to add log in accounts and server roles to those accounts. Below are the modified code. Does it really need server and instance names ? 
SqlServerLogin Add_WindowsUser

        {

            Ensure               = 'Present'
            Name                 = @('domain\account1','domain\account2')           

            #LoginType            = 'WindowsUser'

            #ServerName           = 'TestServer.company.local'

            #InstanceName         = 'DSC'

            PsDscRunAsCredential = $SysAdminAccount

        }

 # Adding Serverole
 
 SqlServerRole Add_ServerRole_domainaccount1


        {

            Ensure               = 'Present'

            ServerRoleName       = @('dbcreator','securityadmin')

            #ServerName           = 'sqltest.company.local'

            #InstanceName         = 'DSC'

            PsDscRunAsCredential = $SysAdminAccount

        }

**Comment by rsganta** [comment]
I have tried to add log in account with SQLServerLogIn add_windowsuser {Name = 'domain\account1'} and it worked. Looks like I got an error when I pass multiple accounts.

**Comment by rsganta** [comment]
Can someone share insights on 1) how we can add multiple accounts( I was successful with one account) 2) how can we grant server roles to those accounts.

**Comment by johlju** [comment]
1. ServerName and InstanceName are keys so they should be set.
1. Since Name is a key you need to add a SqlServerLogin per login you are creating.
2. Please see the documentation for {SqlServerRole](https://github.com/PowerShell/SqlServerDsc#sqlserverrole) and some examples can be found [here](https://github.com/PowerShell/SqlServerDsc/tree/dev/Examples/Resources/SqlServerRole).

**Comment by rsganta** [comment]
Thank you .It worked when I added these login per login.  Roles also worked when I use Members property.
