### ISSUE TITLE
SqlSetup: failed to execute Set-TargetResource

### ISSUE THREAD

**Issue by goforebroke** [PowerShell/SqlServerDsc#948]
**Details of the scenario you tried and the problem that is occurring:**

Trying to install RS into an existing installation of SQL. Installation is failing

PowerShell DSC resource MSFT_SqlSetup  failed to execute Set-TargetResource functionality with error message: System.Exception: Test-TargetResource returned false after calling
Set-TargetResource.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : XXXXXX

**The DSC configuration that is using the resource (as detailed as possible):**

    if($Node.InstanceName)
        {
            SqlSetup $Node.NodeName 
            {
                  InstanceName = $Node.InstanceName
                SourcePath = $Setup_Configuration.InstallSSRS.SourcePath
                SourceCredential = $Node.InstallerAccount
                Features = $Setup_Configuration.InstallSSRS.Features
                InstanceDir= $Setup_Configuration.InstallSSRS.InstanceDir
                InstallSharedDir = $Setup_Configuration.InstallSSRS.InstallSharedDir 
                InstallSharedWOWDir= $Setup_Configuration.InstallSSRSsrp.InstallSharedWOWDir
                DependsOn='[WindowsFeature]NetFramework35Core', '[WindowsFeature]NetFramework45Core';
                PsDscRunAsCredential = $Node.InstallerAccount
            }
        }   

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

Windows Server 2016, SQL Server 2016 SP1-CU5, PowerShell5.1

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**

ModuleType Version    Name
---------- -------    ----
Manifest   1.0        SQLPS

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
DEV 9.0.0.0

**Comment by johlju** [comment]
@goforebroke The error means that Set-TargetResource called the Test-TargetResource function to validate that the installation was successful, b ut Test-TargetResource could not find the features installed.  

1. Can you please post the "...\Setup Bootstrap\Log\Summary.txt" if if contain any error information. 
2. Can you replace the variables names above with the actual values you assign the parameters? Obfuscate any sensitive information.

**Comment by goforebroke** [comment]
I figured out the issue. There was a pending reboot from a windows update once I looked at the summary log from the installer.  Thank you for your help. I did get another error with MSFT_SqlRS. I will open a separate issue.
