### ISSUE TITLE
SQLAlias throws error on 32 bit alias

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/SqlServerDsc#949]
**Details of the scenario you tried and the problem that is occurring:**
On line 165 of SQLAlias the registry key for the 32 bit alias is created. On a new test environment, the MSSQLServer key (and all child keys) didn't exist yet, resulting in an error when creating the key.

After some troubleshooting I found that New-Item only creates child keys when the parent exists. When the parent does not exist, an error is thrown. This can be resolved by adding the -Force parameter to the cmdlet.

This change is also required for line 152.

**The DSC configuration that is using the resource (as detailed as possible):**
SQLAlias Alias
{
            Ensure               = "Present"
            Name                 = "DBServer"
            ServerName       = "serverx.domain.com"
            Protocol             = 'TCP'
            TcpPort              = 1433
}

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSQLServer 9.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
9.0

**Comment by andikrueger** [comment]
I downloaded the modified file from (#950 ) and am still seeing an error:
```
VERBOSE: [sp05]:                            [[SqlAlias]SqlAlias] Operation 'Enumerate CimInstances' complete.
VERBOSE: [sp05]:                            [[SqlAlias]SqlAlias] Performing the operation "Setting the client alias
(32-bit)" on target "SQLSERVER".
Access to the registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\MSSQLServer\Client\ConnectTo' is denied.
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...lient\ConnectTo:) [], CimException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.NewItemCommand
    + PSComputerName        : localhost

Cannot find path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\MSSQLServer\Client\ConnectTo' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (HKLM:\SOFTWARE\...lient\ConnectTo:) [], CimException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCommand
    + PSComputerName        : localhost

```

Is this error related to this issue? @ykuijs @johlju

**Comment by mthoger** [comment]
even on latest build with the -force parameter the error persist.
