### ISSUE TITLE
SQL Azure DSC AlwaysOn Availability Group Setup

### ISSUE THREAD

**Issue by raxso1** [PowerShell/SqlServerDsc#952]
Hi

I am using xSQLServer 9.0.0.0 DSC version in Azure. I have 2 questions to ask:

1. When creating the windows cluster computer object. The cluster object needs permission over the AD OU to create child objects for AOAGs, where in the DSC can you set this permission?

2. In Azure you need to create ILB and probe ports for AOAGs to work. The probes need to be then configured in for the AOAG cluster resource to allow connection to the AOAG listener. Where is the parameters in the DSC to set this?

Are there any examples for setting AOAG with DSC in Azure??

Regards

Rax

**Comment by johlju** [comment]
1. Please see the resources in [xActiveDirectory](https://github.com/PowerShell/xActiveDirectory)  - but currently there are no resource that I know of to set that permission.
2. Please see the resources in [xFailOverCluster](https://github.com/PowerShell/xFailOverCluster) as well as the SqlAGListener resource in this module. Not sure the resources support this yet though. Looking into it my self.

There are no examples as of yet. So please help us create some. 
Also, please file issues in the different repos when you find that the resources lack some functionality.
