### ISSUE TITLE
Ask: Help wanted to install .net framework 4.7

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#953]
The below code to install .net 4.7 does not work. 

WindowsFeature 'NetFramework47' {
               Name = 'NET-Framework-47-Core'
               Ensure = 'Present'
}

What would be the other options to install .net framework 4.7 ?  Using script ?

**Comment by johlju** [comment]
I used to install WMF51 manually like this on older OS versions. Maybe you can use something similar to build script using the Script resource. 

```
Copy-Item '\\fileserver.company.local\Updates\WMF51\Win8.1AndW2K12R2-KB3191564-x64.msu' "\\$computerName\c$\DSCTemp" -Force -Verbose
$InstallWFM51 = {
    Start-Process -FilePath 'wusa.exe' -ArgumentList "C:\DSCTemp\Win8.1AndW2K12R2-KB3191564-x64.msu /extract:C:\DSCTemp\" -Wait -Verbose
    Start-Process -FilePath 'dism.exe' -ArgumentList "/online /add-package /PackagePath:C:\DSCTemp\WindowsBlue-KB3191564-x64.cab /quiet /norestart" -Wait -Verbose
    Restart-Computer -Verbose -Force
}
Invoke-Command -ComputerName $computerName -ScriptBlock $InstallWFM51
```

Closing this issue since it is not related to SQL Server resources. If you feel that is wrong then please reopen.
