### ISSUE TITLE
SqlSetup: How can i create multiple instance in using single DSC configuration on single server ?

### ISSUE THREAD

**Issue by ashishrajcyg** [PowerShell/SqlServerDsc#957]
`
xSQLServerSetup SCOMSQLServerSetup

		{   
            DependsOn = $DependsOn        
            SourcePath = $PackagePath
            SourceCredential = $FileShareCreds           
            PsDscRunAsCredential  = $AdminCreds
			SQLSvcAccount = $SQLServiceCreds
            AgtSvcAccount = $SQLAgentCreds
			SAPWd = $SQLSAAccountCreds		
			InstanceName =  $SQLInstanceName
			InstanceDir = $SQLInstanceDir
            SQLUserDBDir = $SQLDataPath
            SQLUserDBLogDir = $SQLLogPath
            SQLTempDBDir = $SQLTempPath
            SecurityMode =  $SecurityMode 
            SQLSysAdminAccounts =  @($SQLSysAdminAccounts)
			UpdateSource = $UpdateSource 
     		InstallSharedDir = $InstallSharedDir
            InstallSharedWOWDir = $InstallSharedWOWDir
			Features = $Features 
			UpdateEnabled =  $UpdateEnabled 
        }
`

Currently i am using xSQLServerSetup for installing one named instance, i need to install other two instance on the same server. I have tried using same xSQLServerSetup syntax with different value for InstanceName but it fails. May i know what parameters i should be avoiding for just another instance ?

**Comment by johlju** [comment]
You should use `InstanceName` with different values to install multiple instances on the same target node.
What error message are you seeing?

**Comment by johlju** [comment]
Closing this issue due to lack of inactivity. I assume this has been resolved, if not, then please reopen the issue.
