### ISSUE TITLE
Log in to SQL Instance fails using Servername/Adminisrator accout

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#958]
Issue: Log in to sql instance using local administrator account fails.  

Steps: Installed SSMS  & SQL Server  on one of the onpremvm. 

Working scenario: If I launch SSMS with my domain admin account, I am able to log into sql instance using windows authentication.

Not working scenario : If I Launch SSMS with local administrator  account, it throws an error log in fails to connect to sql instance. 

Below are the configs for sql & firewall set ups.

Any help would be greatly appreciated.

#region xSQLServerSetup SQLSetup
        SqlSetup 'InstallDefaultInstance'
        {
            InstanceName = "MSSQLServer"
            SourcePath = $AllNodes.SQLBinaryPath
            Features = "SQLENGINE"
            #SQLSysAdminAccounts = @('Administrators')
            SQLSysAdminAccounts  = $AllNodes.SPSysAdminAccount            
            SQLSvcAccount        = $SqlSysAdmincreds 
            AgtSvcAccount        = $SqlSysAdmincreds                                
            PSDscRunAsCredential = $domjoincreds
            InstallSharedDir     = $AllNodes.InstallSharedDir 
            InstallSharedWOWDir  = $AllNodes.InstallSharedWOWDir 
            InstanceDir          = $AllNodes.InstanceDir 
            InstallSQLDataDir    = $AllNodes.InstallSQLDataDir 
            SQLUserDBDir         = $AllNodes.SQLUserDBDir 
            SQLUserDBLogDir      = $AllNodes.SQLUserDBLogDir 
            SQLTempDBDir         = $AllNodes.SQLTempDBDir 
            SQLTempDBLogDir      = $AllNodes.SQLTempDBLogDir 
            SQLBackupDir         = $AllNodes.SQLBackupDir 
            DependsOn = @("[xFirewall]SQLFirewallRule","[WindowsFeature]NetFramework45")
        }

xFireWall SQLFirewallRule
        {
            Name = "AllowSQLConnection"
            DisplayName = 'Allow SQL Connection'
            Group = 'DSC Configuration Rules'
            Ensure = 'Present'
            Enabled = 'True'
            Profile = ('Domain') 
            Direction = 'InBound'
            LocalPort = ('1433') 
            Protocol = 'TCP'
            Description = 'Firewall Rule to allow SQL communication'

        }

**Comment by johlju** [comment]
You have to make sure your local administrator are allowed to connect to the SQL instance. You could do that by either adding the user as a `SQLSysAdminAccounts` during setup, or after by adding the user as login (`SqlServerLogin`) and adding the user to the correct role (`SqlServerRole`).

**Comment by rsganta** [comment]
thanks johlju. It did not work by adding through sqlsysadminaccounts. I will have to try the second option suggested.

**Comment by johlju** [comment]
Okay, or try to manually add the necessary permissions to the instance so that the account can log on, then you know what you need to add to the configuration.

**Comment by johlju** [comment]
Closing this as it's not as much related to SqlServerDsc but more to Ops of SQL Server. Please reopen if you get more information that this is being a bug in either code or documentation.
