### ISSUE TITLE
How to ensure SQL Service ,sqlagent service is running 

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#960]
I have a config that ensures two services (Databaseengine and  SQLServerAgent) are running under the given service account.  However, noticed couple of observations

1. Validation of SQLServerAgent  always fails . I learnt that there is a known bug . Do you know when this will be fixed. Are there any alternative resource to validate SQLServerAgent service?

2. Sporadically, I have noticed these two services are not running though they were set to Automatiic . I am under impression restartservice = $true would restart the service if it is stopped. If not , can you please redirect me to the resource which would help to restart the service if it is not running.

I have used the reference link https://github.com/PowerShell/SqlServerDsc/blob/dev/Examples/Resources/SqlServiceAccount/1-ConfigureServiceAccount-UserAccount.ps1

My config:
```
# region sql services 
        SqlServiceAccount SetServiceAcccount_SQLService 
        { 
             ServerName     =  $Node.NodeName 
             InstanceName   = 'MSSQLSERVER' 
             ServiceType    = 'DatabaseEngine' 
             ServiceAccount = $SqlSysAdmincreds 
             RestartService = $true 
         } 

        SqlServiceAccount SetServiceAcccount_SQLAgent 
        { 
             ServerName     = $Node.NodeName 
             InstanceName   = 'MSSQLSERVER' 
             ServiceType    = 'SQLServerAgent' 
             ServiceAccount = $SqlSysAdmincreds 
             RestartService = $true 
         } 
     # end region sql services
```

**Comment by johlju** [comment]
1. @nabrond recently got a PR merged that fixed bugs. Please test the dev-version if that solves your problem. If not, please open a new issue with the problem you are seeing.
1. `RestartService` does only restart the service if a change was needed. It does not monitor if the service is running. The parameter description is a bit confusing here, I will get that fixed. Currently only the [Service](https://github.com/PowerShell/PSDscResources) resource make sure a service is always started.
