### ISSUE TITLE
Follow up on issue #960 to valdate sqlserver agent service running under given account.

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#972]
Can I take the latest version of SQLServiceDSC module to address the below issue ?

Config:
  SqlServiceAccount SetServiceAcccount_SQLAgent 
        { 
             ServerName     = $Node.NodeName 
             InstanceName   = 'MSSQLSERVER' 
             ServiceType    = 'SQLServerAgent' 
             ServiceAccount = $SqlSysAdmincreds 
            

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows 2016, Sql Server 2017, WMF 5.0

SQLSERVER DSC and  I believe currently I have dev version 9.0.0.0

**Comment by johlju** [comment]
Please see comment https://github.com/PowerShell/SqlServerDsc/issues/960#issuecomment-353719442 of issue #960. Please download the Dev version, if you have problem then please open an issue with the configuration and an error description. 😄 
Closing this as this has been answered in issue #960.
