### ISSUE TITLE
SQLServiceAccount_SQLAgent running under sysaccount still fails with devversion.

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#978]
As asked in my previous question, I have tested the scenario of SQLAgent service running under sysadminaccount still fails with dev version. Can this issue be open active  until this is resolved at my end and also to avoid duplicate issues on the same root cause issue. Thank you for your patience .

I took the dev version today and uploaded to azure automation (did not delete the previous version but overwrite the existing module) but still fails. Please find the configuration below and LCM verbose for both setserviceaccount_sqlservice and SetServiceAccount_sqlagent

This is configuration 

```
SqlServiceAccount SetServiceAcccount_SQLAgent 
        { 
             ServerName     = $Node.NodeName #'$($node.nodename)'#'DSC-SP3' 
             InstanceName   = 'MSSQLSERVER' 
             ServiceType    = 'SQLServerAgent' 
             ServiceAccount = $SqlSysAdmincreds #$ServiceAccountCredential 'OfficeDog\SP997DB' #
             RestartService = $true 
         } 
```
Error:
```
VERBOSE: [DSC-SP11]: LCM:  [ Start  Resource ]  [[SqlServiceAccount]SetServiceAcccount_SQLService]
VERBOSE: [DSC-SP11]: LCM:  [ Start  Test     ]  [[SqlServiceAccount]SetServiceAcccount_SQLService]
VERBOSE: [DSC-SP11]:                            [[SqlServiceAccount]SetServiceAcccount_SQLService] Information: PowerShell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [DSC-SP11]:                            [[SqlServiceAccount]SetServiceAcccount_SQLService] Importing PowerShell module SQLPS.
VERBOSE: [DSC-SP11]:                            [[SqlServiceAccount]SetServiceAcccount_SQLService] 2017-12-29_17-51-14: Connecting to WMI on 'DSC-SP11'.
VERBOSE: [DSC-SP11]:                            [[SqlServiceAccount]SetServiceAcccount_SQLService] 2017-12-29_17-51-15: Current service account is 'OfficeDog\SP997DB' for DSC-SP11MSSQLSERVER.
VERBOSE: [DSC-SP11]: LCM:  [ End    Test     ]  [[SqlServiceAccount]SetServiceAcccount_SQLService]  in 1.5460 seconds.
VERBOSE: [DSC-SP11]: LCM:  [ Skip   Set      ]  [[SqlServiceAccount]SetServiceAcccount_SQLService]
VERBOSE: [DSC-SP11]: LCM:  [ End    Resource ]  [[SqlServiceAccount]SetServiceAcccount_SQLService]
VERBOSE: [DSC-SP11]: LCM:  [ Start  Resource ]  [[SqlServiceAccount]SetServiceAcccount_SQLAgent]
VERBOSE: [DSC-SP11]: LCM:  [ Start  Test     ]  [[SqlServiceAccount]SetServiceAcccount_SQLAgent]
VERBOSE: [DSC-SP11]:                            [[SqlServiceAccount]SetServiceAcccount_SQLAgent] Information: PowerShell module SqlServer not found, trying to use older SQLPS module.
VERBOSE: [DSC-SP11]:                            [[SqlServiceAccount]SetServiceAcccount_SQLAgent] Importing PowerShell module SQLPS.
VERBOSE: [DSC-SP11]:                            [[SqlServiceAccount]SetServiceAcccount_SQLAgent] 2017-12-29_17-51-15: Connecting to WMI on 'DSC-SP11'.
VERBOSE: [DSC-SP11]: LCM:  [ End    Test     ]  [[SqlServiceAccount]SetServiceAcccount_SQLAgent]  in 0.7500 seconds.
PowerShell DSC resource MSFT_SqlServiceAccount  failed to execute Test-TargetResource functionality with error message: 
System.Exception: The SQLServerAgent service on DSC-SP11\MSSQLSERVER could not be found. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

**Comment by johlju** [comment]
@rsganta thank you for testing this and providing the verbose logs!

**Comment by rsganta** [comment]
Thank you.  Any possible solutions ?

**Comment by johlju** [comment]
I created an integration tests for this resource over at PR #987. The configuration do work there, see [AppVeyor test run](https://ci.appveyor.com/project/PowerShell/sqlserverdsc/build/9.0.101.0#L8060).
I did fix one bug in the resource for the integration tests to pass (see PR description), but that issue should not have cause the above problem. 

Are you sure you are using the Dev version on you target node? Was the resource module replaced on the target node when the configuration ran again? 

If you want to use the same code which is tested in the integration tests that was created, you can download the resource code from my working branch, eventually the code will be merged into dev.
Here is the code in PR that is run in the integration tests: https://github.com/johlju/SqlServerDsc/tree/SqlServiceAccount-integration-tests/DSCResources/MSFT_SqlServiceAccount

**Comment by rsganta** [comment]
I have checked  version of the dsc resources . Below is the dev version I am using. Please let me know if you want me to replace any files.
 
C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\9.0.0.0\DSCResources\MSFT_SqlServiceAccount>dir
 Volume in drive C has no label.
 Volume Serial Number is 48EE-511B

 Directory of C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\9.0.0.0\DSCResources\MSFT_SqlServiceAccount

12/28/2017  11:12 PM    <DIR>          .
12/28/2017  11:12 PM    <DIR>          ..
12/28/2017  11:12 PM    <DIR>          en-US
12/09/2017  09:43 PM            11,429 MSFT_SqlServiceAccount.psm1
12/09/2017  09:43 PM             1,033 MSFT_SqlServiceAccount.schema.mof
               2 File(s)         12,462 bytes
               3 Dir(s)  240,239,423,488 bytes free

**Comment by johlju** [comment]
It seems that you are using the v9 and not the v10 on the target node - still the released version 10 does not contain the fix you are looking for.

There are not unfortunately not possible to see a file date or version number when using the Dev version. File date is when the written to disk, and version number stays the same for dev version between versions.You need to check that either the code fix is in there, or if an entry in the change log has updated, on the target node.
In your case, you should be interested if this entry is in the [CHANGELOG.md under the Unreleased section](https://github.com/PowerShell/SqlServerDsc/blob/dev/CHANGELOG.md#unreleased) on the target node. If it is not, then you probably still using the released version.

```
- Changes to SqlServiceAccount
  - Default services are now properly detected (issue #930).
```

**Comment by rsganta** [comment]
Looks like I do not see the above content in the unreleased section.  Do I need to upload delete the existing module in azure portal and upload the dev version ?

**Comment by rsganta** [comment]
@johlju  
As I need to close on this pending issue, do you want me to delete the existing dev version module and upload the new dev version?  Appreciate your inputs

**Comment by johlju** [comment]
You need to make sure that the correct module, the correct code (the latest Dev-version), is both in Azure Automation and on the target node. For testing this, you can just replace the resource module manually directly on the target node.

**Comment by johlju** [comment]
Also, if it fails, make sure the code on the target nod actually has change log entry mentioned above. 😄

**Comment by johlju** [comment]
Did you update the module and successfully ran the configuration?

**Comment by rsganta** [comment]
@johlju , I will try to test today.

**Comment by rsganta** [comment]
When I replace the DSC Resources on the target node, I am hitting the below error.

Also I tried to upload the latest dev version which is coming as 10,0.0.0 , it fails with different error to download this version . The only way I have to test this to create a new vm for sql again and test it. I will update you once I test with new vm


VERBOSE: [DSC-SP13]:                            [] Applying the new configuration(s) pulled.
Importing module MSFT_SqlSetup failed with error - File C:\Program 
Files\WindowsPowerShell\Modules\SqlServerDsc\9.0.0.0\DscResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1 cannot be loaded. The file 
C:\Program Files\WindowsPowerShell\Modules\SqlServerDsc\9.0.0.0\DscResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1 is not digitally 
signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, 
see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : localhost

**Comment by johlju** [comment]
It seems you have a mix och v9 and v10? You have the module version as v9.0.0.0, but you have a resource from v10.0.0.0. 

Okay, the error `MSFT_SqlSetup.psm1 is not digitally signed` was a new one. I never seen that error before. PowerShell don't like you running the module for some reason. Did you copy the module to the folder as I said? Maybe that's my bad, maybe Azure Automation does not like that, and it might need to download the module correctly for it to be signed properly (did not know that). I actually never copied it on an Azure VM, there I push a "config" every time so it downloads the module.

**Comment by johlju** [comment]
@rsganta is this one resolved?

**Comment by rsganta** [comment]
@johlju , I did not get a chance to work on the dev version. May be I will test it once it get released to main.

**Comment by johlju** [comment]
I will close this issue since the integration tests work. If you see any problem with version 11 once it is released (in a couple of weeks I think) then please reopen this issue.

**Comment by cnilak** [comment]
I am getting the same error, any idea? how to resolve it: 
Importing module MSFT_SqlSetup failed with error - File C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\SqlServerDsc\11.2.0.0\DscResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1 cannot be 
loaded. The file C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\SqlServerDsc\11.2.0.0\DscResources\MSFT_SqlSetup\MSFT_SqlSetup.psm1 is not digitally signed. You cannot run this script on 
the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed

**Comment by johlju** [comment]
@cnilak Could you please open a new issue for this error?
