### ISSUE TITLE
Get script for SSMS installation does not return proper data

### ISSUE THREAD

**Issue by rsganta** [PowerShell/SqlServerDsc#997]
Details of the scenario:
I am trying to install ssms with the below configuration. It used to work fine the registry check in getscript. However today , I noticed on one of my SQL, this registry key does not exist and hence It should return false and SSMS.ps1 should be called.  In LCM verbose, it is not reporting any error.
I have a workaround to remove the registry check but want to know what could be the reason , it is not being called.

The DSC configuration that is using the resource (as detailed as possible):
Script InstallSSMS
        {
        
            GetScript =
            {
                # Do Nothing
                $RegistryPath = "hklm:\SOFTWARE\Microsoft\Microsoft SQL Server\140\Tools\Setup\SQL_SSMS_Adv" 
                $IsKeyExist = Test-Path $RegistryPath                
            
            }

            SetScript = 
            {
       
                $installSSMS =  C:\SXS\SSMS.PS1 
                   
            }

            TestScript = 
            {
        
                #$false

                $IsExists = $GetScript
                if ($IsExists) {return $true} else {return $false} 

                #Test-Path "hklm:\SOFTWARE\Microsoft\Microsoft SQL Server\140\Tools\Setup\SQL_SSMS_Adv"
            }

            DependsOn = "[SqlSetup]InstallDefaultInstance"           

       }

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
windows 2016 with wmf 5.1
sql 2017

Version of the DSC module : 
9.0.0.0 with some dev changes

**Comment by rsganta** [comment]
Does any changes occur to Script ?

**Comment by rsganta** [comment]
This seems to be related #970 . Do we need to use Start-Process instead of GetScript ?

**Comment by rsganta** [comment]
Content in the Set-Script  is correct? Appreciate your inputs.

**Comment by johlju** [comment]
This issue is not related to this resource module, the Script resource is not part of this resource. But to answer your question, you should debug what happens with the resource when you run it. Run it alone and turn on debugging (see [Debugging DSC resources](https://docs.microsoft.com/en-us/powershell/dsc/debugresource)), or add `Write-Verbose` output to see what it sees. 

Closing this issue since it is not related to this resource module.
